### ISSUE TITLE
Inconsistent YAML documentation

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/azure-pipelines-yaml#104]
The YAML schema described on this repo [here](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/pipeline-resources.md#examples-3) differs from the YAMl schema on the Microsoft site [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#pipeline). Which is it?

From Microsoft site
```
name: string  # build numbering format
resources:
  containers: [ containerResource ]
  repositories: [ repositoryResource ]
variables: { string: string } | [ variable ]
trigger: trigger
pr: pr
jobs: [ job | templateReference ]
```

From this repo
```
resources:
  pipelines: [ pipeline ]  
  builds: [ build ]
  repositories: [ repository ]
  containers: [ container ]
  packages: [ package ]
```

I've found that "pipelines" isn't recognized on Azure Pipelines
<img width="488" alt="image" src="https://user-images.githubusercontent.com/3119513/51279571-83e12200-1992-11e9-872a-c9823cb6deae.png">

**Comment by samiyaakhtar** [comment]
Also, according to this repo, repository supports "connection" as follows:
```
resources:          # types: pipelines | repositories | containers | packages
  repositories:
  - repository: string # identifier for the repository resource      
    type: enum # type of the repository source like AzureRepos, GitHub etc. In future this can extend to other source types
    connection: string # service connection to connect to the source, defaults to primary source connection
    source: string  # source repository to fetch
    ref: string  # ref name to use, defaults to 'refs/heads/master'
```

But according to the docs, it's called endpoint and there's no such thing as "connection". Also, the same for "source" and "name":
```
resources:
  repositories:
  - repository: string  # identifier (A-Z, a-z, 0-9, and underscore)
    type: enum  # see below
    name: string  # repository name (format depends on `type`)
    ref: string  # ref name to use, defaults to 'refs/heads/master'
    endpoint: string  # name of the service connection to use (for non-Azure Repos types)
```
