### ISSUE TITLE
PowerShell Task: Unexpected value 'pwsh'

### ISSUE THREAD

**Issue by MiYanni** [microsoft/azure-pipelines-yaml#105]
In the visual editor, there is a checkbox:
![image](https://user-images.githubusercontent.com/17788297/51282861-31583380-199b-11e9-9dc4-30d0392cf143.png)

This checkbox adds `pwsh: true` to the yml when you hit the 'View YAML' button:
```yml
steps:
- powershell: 'Install-Module platyPS -Force -Confirm:$false -Scope CurrentUser'
  pwsh: true
  displayName: 'Install-Module platyPS'
```

However, if you put this into a yml file, when attempting to run the build on a Windows worker (VS2017), this error occurs in the pipeline:
![image](https://user-images.githubusercontent.com/17788297/51282989-91e77080-199b-11e9-8c56-7ef0ccf6ff26.png)

Is there some other way to identify the use of pwsh (PowerShell Core 6) in this task in the yml?

**Comment by ericsciple** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#pwsh

**Comment by MiYanni** [comment]
@ericsciple The 'View YAML' button still generated the yml incorrectly... So, this is still an issue. If the documentation you linked is correct, it should have generated:
```yml
steps:
- pwsh: 'Install-Module platyPS -Force -Confirm:$false -Scope CurrentUser'
  displayName: 'Install-Module platyPS'
```
