### ISSUE TITLE
CopyFiles@2 fails on broken symlink even for a single file copy

### ISSUE THREAD

**Issue by fgervais** [microsoft/azure-pipelines-yaml#107]
This task fails because somewhere deep in $(Build.SourcesDirectory)/... is a broken symlink.

```
- task: CopyFiles@2
    inputs:
      sourceFolder: $(Build.SourcesDirectory)
      contents: 'MLO'
      targetFolder: $(Build.ArtifactStagingDirectory)
```

> Unhandled: Failed find: ENOENT: no such file or directory, stat '/__w/1/s/arm-buildroot-linux-gnueabihf_sdk-buildroot/arm-buildroot-linux-gnueabihf/sysroot/bin/systemd-resolve'

I would not expect this task to fail on broken symlink but even less in this case because my content pattern resolves to a single file.

Anybody else think this is not the correct behavior?

How should I work around this given I cannot get rid of the symlink?
