### ISSUE TITLE
[question] Why do we have the "Job" suffix after the job's display name

### ISSUE THREAD

**Issue by kittaakos** [microsoft/azure-pipelines-yaml#115]
Copied from https://github.com/Microsoft/azure-pipelines-agent/issues/2010#issue-389778968

----

Super minor thing: why do we have the "Job" suffix after the job's name when the corresponding `condition` was true. Otherwise, it is not there.

Note, the `displayName` was explicitly set.

Thank you!

----

`azure-pipelines.yml`:
```yml
jobs:
- job: rolling_macOS
  displayName: 'Rolling Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  condition: and(ne(variables['Build.Reason'], 'Manual'), ne(variables['Build.Reason'], 'Schedule'))
  steps:
    - template: rolling-build-steps.yml

- job: release_macOS
  displayName: 'Release Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'Schedule'))
  steps:
    - template: release-build-steps.yml

- job: release_windows
  displayName: 'Release Build (Windows)'
  pool:
    vmImage: 'vs2017-win2016'
  condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'Schedule'))
  steps:
    - template: release-build-steps.yml
```

----

![screen shot 2018-12-11 at 14 57 27](https://user-images.githubusercontent.com/1405703/49805386-41a24080-fd55-11e8-9c3d-8a87bf01e19e.jpg)

![screen shot 2018-12-11 at 14 57 19](https://user-images.githubusercontent.com/1405703/49805387-41a24080-fd55-11e8-9174-6665edb4797c.jpg)

Edit: I have updated the pipeline configuration.
