### ISSUE TITLE
Expand variables in displayName (for Phase and script)

### ISSUE THREAD

**Issue by tjaffri** [microsoft/azure-pipelines-yaml#116]
I would like to use some variables (set at queue time) as part of the display name for the phase as well as script. In the snippet below, these variables are ``$(System.datasetName)``, ``$(System.datasetVersion)``, and ``$(Build.BuildNumber)``.

When the job is queued and I look at the build detailes page, these variables are not expanded... I see the actual literal strings below instead of the variable values in the displayName.

```yml
resources:
- repo: self

variables:
  python.version: '3.6'
  log_group_name: $(System.datasetName)_$(System.datasetVersion)_$(Build.BuildNumber)

phases:

- phase: Phase_1
  displayName: 'Run $(log_group_name)'
  condition: succeeded()
  queue:
    name: testqueue
    timeoutInMinutes: 60

  steps:
  - script: |
      echo "Hello World"
    displayName: 'Build Summary $(log_group_name)'
```

For what it's worth, the same works in displayName for task... see below

```yml
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
```
