### ISSUE TITLE
Trigger path exclusion

### ISSUE THREAD

**Issue by stannynuytkens** [Microsoft/azure-pipelines-yaml#124]
It should be made **clear** that trigger exclusions for a combination of paths should be on 1 line.

```
trigger:
  branches:
    include:
      - feature/cd-trigger
  paths:
    exclude:
      - .azure-pipelines/*;readme.*
```

instead of

```
trigger:
  branches:
    include:
      - feature/cd-trigger
  paths:
    exclude:
      - .azure-pipelines/*
      - readme.*
```

When I had a PR where changes to both exclusions were made, the CD kicked in, which was unexpected...

I didn't find this in the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml) but with perseverance.
