### ISSUE TITLE
Expanding variables in service container env declarations

### ISSUE THREAD

**Issue by flcdrg** [microsoft/azure-pipelines-yaml#130]
I am trying (without success) to use variables to set values in a resources/containers block.. eg.

```
variables:
  sa.password: 'yourStrong(!)Password'

resources:
  containers:
  - container: my_container
    image: something:latest
  - container: sql
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    env:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: $(sa.password)
    ports:
    - 1433:1433
```

When this runs, it hasn't replaced `sa.password` - instead the password is set to the literal value "$(sa.password)" (obviously not what I wanted).

Is this supported, and if not, can it be?

**Comment by cor3ntin** [comment]
I'm interested in that too !

**Comment by samuel-begin** [comment]
Useful for image names as well
```yaml
variables:
  DOCKER_IMAGE_FULL_NAME: my-docker-image

resources:
  container: my-container
    image: $(DOCKER_IMAGE_FULL_NAME)

jobs:
- job: Build-my-container
  steps:
  - task: Docker@1
    inputs:
      command: build
      imageName: $(DOCKER_IMAGE_FULL_NAME)

- job: Test-my-container
  services:
    my-container: my-container
```
