### ISSUE TITLE
Regression: matrix builds with vmImage broke recently.

### ISSUE THREAD

**Issue by carllerche** [Microsoft/azure-pipelines-yaml#134]
Doing the following results in all matrix jobs using the ubuntu vm:

```yaml
jobs:
- job: foo
  displayName: foo
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.13
      Windows:
        vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)
```

This regression happened recently within the past (couple of days)?

Example project: https://github.com/tokio-rs/tokio

Discussion: https://www.reddit.com/r/rust/comments/aw4b1g/azure_pipelines_for_rust_projects/ehjs7so/?st=jsqeps9x&sh=6cefea12
