### ISSUE TITLE
Missing GUI option: Create git tag after successful build

### ISSUE THREAD

**Issue by steved0x** [microsoft/azure-pipelines-yaml#139]
@bouke From https://github.com/MicrosoftDocs/vsts-docs/issues/3471

The current visual build pipelines allow to tag a git commit after the build has succeeded. I can't seem to find this option in the new yaml builds.

**Comment by tomstreet** [comment]
Is it possible to do this right now? Can't find any info about this and it doesn't appear to be in the road map.

**Comment by DeluxZ** [comment]
Really missing this feature. I'm creating YAML builds to move away from the designer but really missing this option at the moment. I'm on the point of creating a powershell script to create the tag manually...

**Comment by johnazariah** [comment]
Is this possible yet? Is there a plan to get this feature back?

**Comment by tomstreet** [comment]
This is how I work around it:
```yaml
- powershell: |
    Write-Host "Tagging Build: $env:BuildNumber"

    git tag $env:BuildNumber
    git push origin $env:BuildNumber
  env:
    BuildNumber: $(Build.BuildNumber)
```
