### ISSUE TITLE
InvokeRESTAPI: Cannot use secret variable for serviceConnection

### ISSUE THREAD

**Issue by mikeharder** [microsoft/azure-pipelines-yaml#140]
Assume a pipeline contains a variable `ServiceConnection` and uses the following YAML:

```yaml
- job: 'foo'
  pool: server
  steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: '$(ServiceConnection)'
```

If the variable is non-secret, the pipeline works as expected.  However, if the variable is secret, the pipeline fails to queue with the following error:

```
Job Trigger: Step  input serviceConnection references service connection  which could not be found.
```

From the error message, it appears the value of the secret variable was empty.
