### ISSUE TITLE
Support regular expressions for branch triggers

### ISSUE THREAD

**Issue by bryevdv** [microsoft/azure-pipelines-yaml#149]
## Problem Statement

Currently Azure Pipelines branch triggers [only support basic glob wildcards](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#branches
), e.g.:

```yaml
# specific branch build
trigger:
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/old*
```

By contrast, TravisCI branch conditions [may contain regular full expressions](https://docs.travis-ci.com/user/customizing-the-build/#using-regular-expressions):

```yaml
branches:
  only:
  - master
  - /^deploy-.*$/
```

## Request

Ability to specify branch triggers on Azure pipelines as regular expressions (similar to capability on TravisCI). 

## Motivation

The [Bokeh project](https://github.com/bokeh/bokeh) would like to migrate its CI automation from TravisCI to Azure Pipelines. We currently use the regular expression capability on TravisCI to condition our build stages to perform additional build/release automation on release version tags. Our version tagging scheme cannot be expressed by a simple wildcard, and we are not in a position to change the existing scheme due to the high risk and effort it would entail (the version couples to separately released JS resources on a CDN, e.g.)
