### ISSUE TITLE
Parallel jobs fail

### ISSUE THREAD

**Issue by diegobernardes** [Microsoft/azure-pipelines-yaml#154]
I don't know what I could be doing wrong, but the 'jobs' command really don't work with me.

```yml
pool:
  vmImage: Ubuntu 16.04

jobs:
  - job: job1
    steps:
      - script: echo 1

  - job: job2
    steps:
      - script: echo 2

  - job: job3
    steps:
      - script: echo 3
```

The error is always the same:
```
/misc/azure/pipelines.yml (Line: 4, Col: 1): Unexpected value 'jobs'
```

**Comment by ericsciple** [comment]
@diegobernardes pool is a job-level setting

try:

```yaml
 jobs:
  - job: job1
    pool:
      vmImage: Ubuntu 16.04
   steps:
      - script: echo 1

  - job: job2
   pool:
      vmImage: Ubuntu 16.04
    steps:
      - script: echo 2

  - job: job3
   pool:
      vmImage: Ubuntu 16.04
    steps:
      - script: echo 3
```
