### ISSUE TITLE
The service connection name 00000000-0000-0000-0000-000000000000 is ambiguous.

### ISSUE THREAD

**Issue by bariscaglar** [microsoft/azure-pipelines-yaml#169]
When I try to queue a build for an Azure DevOps Pipeline that refers to a GitHub hosted azure-pipelines.yml file that refers to another such yml file, I get this error. This exact setup used to work.

We have several projects that refer to a single yml file in Microsoft/IIS.Common repository. Builds queued to the azure-pipelines.yml file in this common repo succeeds. 

As an example, we have the Microsoft/IIS.Compression repository with a simple azure-pipelines.yml file that refer to the one in common:

```
resources:
  repositories:
    - repository: Microsoft/IIS.Common
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS

jobs:
- template: azure-pipelines.yml@Microsoft/IIS.Common  # Template reference
```

When I create a build pipeline for this yaml, I always get the "The service connection name 00000000-0000-0000-0000-000000000000 is ambiguous." error when I try to queue it.
