### ISSUE TITLE
[BUG?] Trigger paths not working for specific file extension

### ISSUE THREAD

**Issue by michaelw85** [microsoft/azure-pipelines-yaml#190]
I would like to specify a trigger for markdown and related documentation files to be able to generate and deploy my documentation site. 

Example below does not work as expected (similar setup in exclude doesn't work either).

```yaml
trigger:
  branches:
    include:
      - master
  batch: true
  paths:
    include:
      - doc
      - src/**/*/*.doc.ts
      - src/**/*/*.doc.html
      - src/**/*/*.md
```

Related issues: 
- https://github.com/MicrosoftDocs/vsts-docs/issues/3925
- https://github.com/Microsoft/azure-pipelines-tasks/issues/9235
- https://github.com/Microsoft/azure-pipelines-yaml/issues/124
- https://github.com/Microsoft/azure-pipelines-yaml/issues/149

**Comment by michaelw85** [comment]
If anyone stumbles upon this issue I managed to work around it creating a pre-commit hook using a glob setup to do the filtering. This pre-commit hook writes a timestamp to a specific file which I've used in my trigger paths. It's not an ideal solution unfortunately but it's something.

**Comment by vtbassmatt** [comment]
@davidstaheli to consider whether we should accept minimatch paths.

@michaelw85 I don't believe we support `**` in a path. A bare `*` should match multiple path segments, if I remember right:

```yaml
trigger:
  branches:
    include:
      - master
  batch: true
  paths:
    include:
      - doc
      - src/*.doc.ts
      - src/*.doc.html
      - src/*.md
```

**Comment by michaelw85** [comment]
@vtbassmatt I also tried the setup you suggest, the minimatch setup was my last attempt both fail to work.
I double checked by using the following setup:

```yaml
# CD build:
  paths:
    exclude:
      - src/*.md

# DOC build:
  paths:
    include:
      - src/*.md
```
I added a line inside `src/doc/build-and-test.md` and pushed.
This results in a CD build and not a DOC only build.

I think the following [documentation ](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#wildcards)explains why it's not working:
> You may not include * in the middle of a path filter, and you may not use ?.
