### ISSUE TITLE
name property not incrementing $(Rev)

### ISSUE THREAD

**Issue by devhawk** [microsoft/azure-pipelines-yaml#191]
I just tried queueing two jobs and they got the same $rev number:
* https://dev.azure.com/msft-xlang/public/_build/results?buildId=1959
  * job name: public_1959.19.0429.119.1
* https://dev.azure.com/msft-xlang/public/_build/results?buildId=1960
  * job name: public_1960.19.0429.119.1

[pipeline YAML file](https://github.com/Microsoft/xlang/blob/devhawk/apartments/src/package/pywinrt/projection/pipeline-public.yml):

``` yaml
name: $(System.TeamProject)_$(BuildID).$(Date:yy).$(Date:MMdd).$(DayOfYear)$(Rev:.r)
jobs:
- template: AzurePipelinesTemplates/job-build-pywinrt.yml

- template: AzurePipelinesTemplates/job-build-projection.yml

- template: AzurePipelinesTemplates/job-package-projection.yml
  parameters:
    dependsOn: build_projection
```
