### ISSUE TITLE
Pass --build-arg argumento to DockerCompose - action: 'Build services'

### ISSUE THREAD

**Issue by fabriciols** [microsoft/azure-pipelines-yaml#197]
I'm trying to set an --build-arg on docker-compose command using the DockerCompose task without success...

I did in a very very tricky way, but i guess the DockerCompose task should have a parameter to be able to set the --build-arg

The way i did

```
- task: DockerCompose@0
  inputs:
    action: 'Build services'
    includeLatestTag: true
    additionalImageTags: $(Build.SourceVersion)
    containerregistrytype: Azure Container Registry
  displayName: 'Docker build image'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker-compose build --build-arg TAG=$(Build.SourceVersion)
    
    docker tag image image:$(Build.SourceVersion)
    '
  displayName: 'Docker build image - set build-arg'
```
