### ISSUE TITLE
Unable to use step templates in Multi stage Deployment

### ISSUE THREAD

**Issue by jabbera** [microsoft/azure-pipelines-yaml#199]
I'm trying to use a step template with a multi stage deployment as announced at build and it will not queue. It fails to queue with the following error:

> An error occurred while loading the YAML build pipeline. Unable to cast object of type 'Microsoft.TeamFoundation.DistributedTask.Pipelines.TaskTemplateStep' to type 'Microsoft.TeamFoundation.DistributedTask.Pipelines.TaskStep''

How should I use a step template with deployments? I don't want to have to copy and paste my steps for each environment that should be exactly the same. 

```
jobs:
  - deployment: BLAH
    pool:
      name: Pool
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: /pipeline-templates/environment-deployment.yaml
```
