### ISSUE TITLE
Add cross-product matrix strategy

### ISSUE THREAD

**Issue by mikeharder** [microsoft/azure-pipelines-yaml#20]
By "cross-product matrix", I mean the scenario where you want to use the `matrix` strategy on a cross-product of multiple dimensions.  For example, say you want to run tests on 2 OS (Linux, Windows) and 2 versions of Python (3.6, 3.7).  Currently, you'd need to manually create a matrix with all the combinations:

```yaml
strategy:
  matrix:
    Linux_Python36:
      VM_IMAGE: 'ubuntu-16.04'
      PYTHON_VERSION: '3.6'
    Linux_Python37:
      VM_IMAGE: 'ubuntu-16.04'
      PYTHON_VERSION: '3.7'
    Windows_Python36:
      VM_IMAGE: 'vs2017-win2016'
      PYTHON_VERSION: '3.6'
    Windows_Python37:
      VM_IMAGE: 'vs2017-win2016'
      PYTHON_VERSION: '3.7'
```

While this isn't too bad with a small number of dimensions and a small number of variables in each dimension, it can quickly become unmaintainable as the dimensions and variables grow.  It would be nice if there was a way to express this more succinctly, something like:

```yaml
strategy:
  cross-product:
    PYTHON_VERSION: [ '3.6', '3.7' ]
    VM_IMAGE: [ `ubuntu-16.04`, `vs2017-win2016` ]
```

**Comment by vtbassmatt** [comment]
The concept is good. A handful of issues to think on.

I need to predictably generate job names (in the current unrolled syntax, `Windows_Python37` is the job name) for downstream dependencies and accessing output variables. I don't love "Job1" - "JobN" but that seems to be the most straightforward. We could define and document what order we generate them in.

I also need to handle exceptions as a subkey of `cross-product`. So the syntax might end up more like:
```yaml
strategy:
  cross-product:
    vars:
      PYTHON_VERSION: [ '3.6', '3.7', '2.7' ]
      VM_IMAGE: [ 'ubuntu-16.04', 'vs2017-win2016' ]
    except:
    - PYTHON_VERSION: '2.7'  # skip Python 2.7 on Windows
      VM_IMAGE: 'vs2017-win2016'
```

**Comment by vtbassmatt** [comment]
Hmm, I need to think more about `dependsOn`. I thought you could "reach into" the matrix and depend on a single resulting job, but if not, then no reason to introduce that here. (In fact, this would likely be implemented as syntactic sugar on top of `matrix`, so we'd get the exact same level of support.)

Regarding a name: we have restrictions on what you can name jobs (most obvious one, no spaces) but wouldn't want to restrict values that way. I guess if we added some new functions - maybe `make_job_name(string)` - that you could manipulate the values with, that might cover it.

**Comment by mikeharder** [comment]
A default job name would be sufficient for our needs -- I was just throwing out the idea of a format string.  I also agree this should be syntactic sugar on top of `matrix` to minimize the number of fundamental concepts.

**Comment by jbergstroem** [comment]
Shameless bump! This would be a very good quality-of-life feature.

**Comment by sylveon** [comment]
This would also be very useful for compiling programs using multiple architectures and build configurations:

```yaml
strategy:
  cross-product:
    PLATFORM: [ "ARM", "ARM64", "x86", "x64" ]
    CONFIGURATION: [ "Debug", "Release" ]
```

**Comment by t-eckert** [comment]
@vtbassmatt I'm going to subscribe to this. I ran into this (like you did) when moving Click to Azure Pipelines.

**Comment by DonJayamanne** [comment]
I know this may not be what everyone is after, however I've gone with the following approach:
```yaml
parameters:
  jobs: []
  pythonVersions: ["3.7", "3.6", "3.5", "2.7"],
  operatingSystems: ["....."]

jobs:
- job: xxx
  strategy:
    matrix:
      ${{ each job in parameters.jobs }}:
        ${{ each py in parameters.pythonVersions }}:
            ${{ each os in parameters.operatingSystems }}:
              ${{ format('{0}{1}', py, os) }}:
```

You still get the matrix from where the template is used by passing parameters as such (this will basically override what was setup in the template):
```yaml
- template xyz.yaml
  parameters
    pythonVersions: [...]
    operatinSystem: [...]
```

**Comment by AsValeO** [comment]
@vtbassmatt
> Hmm, I need to think more about `dependsOn`. I thought you could "reach into" the matrix and depend on a single resulting job, but if not, then no reason to introduce that here...

Is this not available now?
For example this matrix job builds for windows and linux:
```
- job: Build
    strategy:
      matrix:
       Windows:
        os: 'windows'
       Linux:
        os: 'linux'
```
and I want then to deploy only Windows result in next stage:
```
- stage: Deploy
  dependsOn: Build Windows
```
causes

> "Stage Deploy depends on unknown stage BuildJob Windows."

Now deploy stage wait for whole matrix to complete with `dependsOn: Build`

**Comment by janpio** [comment]
As an additional data point here: GitHub Actions (which seems to be based on Azure Pipelines a bit) has native support for this: https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-9 (second example)

**Comment by vtbassmatt** [comment]
We made some changes to the parser to support this in Actions. It's still on my radar for Azure Pipelines as well.

**Comment by JustinGrote** [comment]
I spent too much time overthinking this and trying to get @DonJayamanne's example to work. Ended up just using a powershell script to generate it. Here's an example for building Powershell on all OS, but don't try to build Windows Powershell on linux systems:

```powershell
$os = @(
    'windows-latest'
    'vs2017-win2016'
    'ubuntu-latest'
    'macOS-latest'
)

$psversion = @(
    'pwsh'
    'pwsh-preview'
    'powershell'
)

$exclude = 'ubuntu-latest-powershell','macOS-latest-powershell'

$entries = @{}
foreach ($osItem in $os) {
    foreach ($psverItem in $psversion) {
        $entries."$osItem-$psverItem" = @{os=$osItem;psversion=$psverItem}
    }
}

$exclude.foreach{
    $entries.Remove($PSItem)
}

$entries.keys | sort | foreach {
    "      $PSItem`:"
    "        os: $($entries[$PSItem].os)"
    "        psversion: $($entries[$PSItem].psversion)"
}

```

# Output
```
      macOS-latest-pwsh:
        os: macOS-latest
        psversion: pwsh
      macOS-latest-pwsh-preview:
        os: macOS-latest
        psversion: pwsh-preview
      ubuntu-latest-pwsh:
        os: ubuntu-latest
        psversion: pwsh
      ubuntu-latest-pwsh-preview:
        os: ubuntu-latest
        psversion: pwsh-preview
      vs2017-win2016-powershell:
        os: vs2017-win2016
        psversion: powershell
      vs2017-win2016-pwsh:
        os: vs2017-win2016
        psversion: pwsh
      vs2017-win2016-pwsh-preview:
        os: vs2017-win2016
        psversion: pwsh-preview
      windows-latest-powershell:
        os: windows-latest
        psversion: powershell
      windows-latest-pwsh:
        os: windows-latest
        psversion: pwsh
      windows-latest-pwsh-preview:
        os: windows-latest
        psversion: pwsh-preview
```

@vtbassmattt Github Actions does make this so much easier, would love to see this backported to Azure PIpelines.

**Comment by JustinGrote** [comment]
@vtbassmatt Update check, you said this was integrated into Github Actions and was on the roadmap for Azure PIpelines 6 months ago. Any progress update?

**Comment by JustinGrote** [comment]
Also @DonJayamanne do you have a concrete example of your method? I've taken a second pass and can't get it to work at all, it appears each is for iterative addition, you have to still specify every job individually. I checked your repositories and don't see any with devops pipelines yaml.

**Comment by vtbassmatt** [comment]
@JustinGrote no progress on this one unfortunately.

**Comment by JustinGrote** [comment]
After a *lot* of trial and error, here's a concrete example of @donJayamanne's method working. It just echos powershell scripts but it gives you an idea. Gonna try to work exclusions in with "if"

### matrix.yml
```yaml
parameters:
  platform: ['x86','x64']
  test: ['test1','test2']
  testlevel2: ['test1','test2']

jobs:
  - ${{ each platform in parameters.platform }}:
    - ${{ each test in parameters.test }}:
      - ${{ each testlevel2 in parameters.testlevel2 }}:
        - job: ${{ platform }}_${{ test }}_${{ testlevel2 }}
          steps:
          - task: Powershell@2
            displayName: '${{ platform }}-${{ test }}-${{ testlevel2 }}'
            inputs:
              targettype: inline
              script: echo '${{ platform }}-${{ test }}-${{ testlevel2 }}'
```

### azure-pipelines.yml
```
jobs:
  - template: matrix.yml
```

### Result
![image](https://user-images.githubusercontent.com/15258962/75202209-68148780-571f-11ea-8ccb-2cdde1a48f70.png)
