### ISSUE TITLE
Using expression for container image name

### ISSUE THREAD

**Issue by flcdrg** [microsoft/azure-pipelines-yaml#206]
I'd like to be able to use an expression to set the image property for a job container. eg. given a variable `containerResource`, do similar to:

``` yaml
  container: 
    image: $[ variables['containerResource'] ]
```

Currently, if an expression / variable is supplied, it is not expanded.

**Comment by samuel-begin** [comment]
Same here, but I would be fine with pipeline variables
```yaml
variables:
  DOCKER_IMAGE_FULL_NAME: my-docker-image

resources:
  container: 
    image: $(DOCKER_IMAGE_FULL_NAME)
```
