### ISSUE TITLE
how to Resources repositories from other project ?

### ISSUE THREAD

**Issue by gabrielfsousa** [microsoft/azure-pipelines-yaml#208]
how to Resources repositories from other project ?
tried this, but didnt work.

```
resources:
  repositories:
  - repository: PipelineTemplates
    type: git
    name: PipelineTemplates
    source: https://dev.azure.com/..../otherproject
```

**Comment by mamen2022** [comment]
Hi,
I have exactly the same problem! But the only difference is that I want to download another repository from the same project. Is this possible? 

There isn't any documentation online about how to do this. We can achieve this with shell script but we have to set the repo credentials in the yaml file, and that is not the best approach at all.

**Comment by jdkemme** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories

See:
name: Contoso/BuildTemplates    <------ project/reponame
or
name: BuildTemplates    <----- same project, different repo

**Comment by GeromeRen** [comment]
Any advice on this?

**Comment by SanderHolvoet** [comment]
@GeromeRen 

A bit late to the party, but the following worked for me.

**Project containing templates:**
```yaml
# Project: BuildTemplates
# Repo: BuildTemplates
# File: templates/steps.yml (notice the "templates" subdirectory, which holds my YAML file)

steps:
- bash: echo "Running bash script from template"
  displayName: bash script
```

**Main project, which will consume the template(s):**
```yaml
# File: azure-pipelines.yml

resources:
  repositories:
  - repository: scripts # can be anything, is later used in the @ statement
    type: git # git = Azure DevOps / #github = GitHub
    name: BuildTemplates/BuildTemplates # ProjectName/RepoName

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: templates/steps.yml@scripts
```
