### ISSUE TITLE
Use variable or parameter in demands

### ISSUE THREAD

**Issue by timwebster9** [microsoft/azure-pipelines-yaml#21]
Is it possible to use a variable or parameters in agent pool demands?  Something like this:
```
variables:
  projectName:my-vsts-project
  agentName: '$(projectName)-$(Build.BuildId)'

jobs:
- job: JavaBuild
  dependsOn: LaunchAgent
  pool:
    name: 'mgmt-aks-sandbox'
    demands:
    - agent.name -equals $(agentName)
```

It doesn't seem to work, as I end up getting like this:
```
##[Error 1]
No agent found in pool mgmt-aks-sandbox which satisfies the specified demands:
     agent.name -equals $(projectName)-$(Build.BuildId)
     java
     Agent.Version -gtVersion 2.140.2 
```

I've also tried with parameters and template expressions, and those don't work either:
```
##[Error 1]
No agent found in pool mgmt-aks-sandbox which satisfies the specified demands:
     agent.name -equals ${{ parameters.agentName }}
     java
     Agent.Version -gtVersion 2.140.2 
```

It looks like this guy managed to do it via the UI (see comments at the end), but is there a way to do it in YAML?
https://www.noelbundick.com/posts/serverless-vsts-build-agents-with-azure-container-instances/
