### ISSUE TITLE
Matrix job shows up as single job on GitHub, unless there is a dependency

### ISSUE THREAD

**Issue by rly** [microsoft/azure-pipelines-yaml#211]
Currently, separate jobs show up as separate checks in GitHub on the Pull Request page. But a single job that uses a matrix strategy to run multiple jobs shows up at a single Check in GitHub. I would like those multiple jobs to show up as separate Checks. I can make that happen using an ugly workaround below. 

e.g. with this matrix job description:
```
- job: 'Test'
  displayName: "Test"

  strategy:
    matrix:
      Windows-py3.7:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.7'
        testToxEnv: 'py37'
        coverageToxEnv: 'coverage-py37'
        buildToxEnv: 'build-py37'
        testWheelInstallEnv: 'wheelinstall-py37'

      Windows-py3.6:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.6'
        testToxEnv: 'py36'
        coverageToxEnv: 'coverage-py36'
        buildToxEnv: 'build-py36'
        testWheelInstallEnv: 'wheelinstall-py36'

      Windows-py3.5:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.5'
        testToxEnv: 'py35'
        coverageToxEnv: 'coverage-py35'
        buildToxEnv: 'build-py35'
        testWheelInstallEnv: 'wheelinstall-py35'

      Windows-py2.7:
        imageName: 'vs2017-win2016'
        pythonVersion: '2.7'
        testToxEnv: 'py27'
        coverageToxEnv: 'coverage-py27'
        buildToxEnv: 'build-py27'
        testWheelInstallEnv: 'wheelinstall-py27'
```
Currently results in one Check in GitHub:
![image](https://user-images.githubusercontent.com/310197/58212484-c8176280-7ca3-11e9-86ad-a8e50330b5f5.png)

But ideally would yield four separate Checks in GitHub:
![image](https://user-images.githubusercontent.com/310197/58212433-a322ef80-7ca3-11e9-8d1b-f957cd7c2a4e.png)

See also the report and comments on https://stackoverflow.com/questions/52374098/how-to-report-individual-jobs-of-pipeline-as-github-checks-for-azure-pipelines

**Workaround**: Make the matrix job dependent on a dummy job:
```
- job: 'Dummy'
  displayName: 'Dummy'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
    displayName: 'Install build dependencies'
    
  - script: |
      python --version
    displayName: 'Check Python version'

- job: 'Test'
  displayName: "Test PyNWB"
  dependsOn: Dummy

  strategy:
    matrix:
      Windows-py3.7:
         ...
```
