### ISSUE TITLE
DownloadPipelineArtifact task: Could not find any pipeline artifacts in the build.

### ISSUE THREAD

**Issue by timmkrause** [microsoft/azure-pipelines-yaml#215]
I'd like to migrate from YAML builds to multi-stage YAML pipelines.

So I took a working template from our CI build and added stages/tasks for an integration deployment.
At first I had to realize that I need to download a published artifact "manually" (which makes sense, but wasn't obvious to me).
I am using sub-templates, the following example is "copied together".

The problem is that `PublishBuildArtifacts@1` from the build logs `File upload succeed.`, but `DownloadPipelineArtifact@1` then errors out with `Could not find any pipeline artifacts in the build.`.

```
1##[debug]Evaluating condition for step: 'DownloadPipelineArtifact'
2##[debug]Evaluating: SucceededNode()
3##[debug]Evaluating SucceededNode:
4##[debu
g]=> True
5##[debug]Result: True
6Starting: DownloadPipelineArtifact
7==============================================================================
8Task         : Download Pipeline Artifact
9Description  : Download Pipeline Artifact
10Version      : 1.1.3
11Author       : Microsoft Corporation
12Help         : Download named artifact from a pipeline to a local path.
13==============================================================================
14Download from the specified build: #3968
15Download artifact to: d:\a\1\a
16##[error]Could not find any pipeline artifacts in the build.
17##[debug]Processed: ##vso[task.logissue type=error;]Could not find any pipeline artifacts in the build.
18##[debug]Processed: ##vso[task.complete result=Failed;]
19##[debug]   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.DownloadAsync(AgentTaskPluginExecutionContext context, PipelineArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken)
20   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
21   at Agent.PluginHost.Program.Main(String[] args)
22Finishing: DownloadPipelineArtifact

```

The example:

```
trigger:
  batch: true
  branches:
    include:
    - develop

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-2019
      demands:
      - msbuild
      - visualstudio
      - vstest
    steps:
    # Build steps...
    - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: FooBar'
    inputs:
        ArtifactName: 'FooBar'
- stage: INT
  jobs:
  - deployment: INT_Deployment
    pool:
      vmImage: windows-2019
    environment: 'INT'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
            artifactName: 'FooBar'
            targetPath: $(System.DefaultWorkingDirectory)
          # Deployment steps...
```

**Comment by ds-ms** [comment]
You could use it this way instead: https://github.com/microsoft/azure-pipelines-yaml/blob/master/templates/deploy-to-existing-kubernetes-cluster.yml#L46

Your yaml for publishing artifacts could look something like this:
```yaml
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'FooBar'
        targetPath: 'artifacts'
```

And also, if you add a `dependsOn` step to your `deployment` it would download the artifacts by default. You wouldn't need an extra `DownloadPipelineArtifact` step

**Comment by efzwo** [comment]
You have to differentiate between Build Artifacts and Pipeline Artifacts. The correct task you need for multi-stage YAML pipelines is [PublishPipelineArtifact](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact) and DownloadPipelienArtifact.

**Comment by timmkrause** [comment]
Thanks for pointing that out @efzwo. Also understood pipeline artifacts as a successor over build artifacts regarding perf. and everything. Additionally publish and download have to be of the same kind, using Publish**Build**Artifact and Download**Pipeline**Artifact or vice versa will not work.

Unfortunately it is still not working for me.

```
- task: PublishPipelineArtifact@0
  displayName: 'Publish Artifact: FooBar'
  inputs:
    artifactName: 'FooBar'
    targetPath: '$(Build.ArtifactStagingDirectory)'
```

First I needed to find out that I have to set the `targetPath` to the staging directory which is set by default for the `PublishBuildArtifact` task. Now the artifacts package looks good.

Unfortunately I am not able to deploy my MSDeploy package (which is part of the artifacts package) because the ZIP file could not be found:

`##[error]Error:` No package found with specified pattern: d:\a\1\s\**\FooBar.Web.zip`

But prior to this the download of the artifact was successful:

```
##[section]Starting: Download Artifact
==============================================================================
Task         : Download Pipeline Artifact
Description  : Download Pipeline Artifact
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : Download named artifact from a pipeline to a local path.
==============================================================================
Download from the specified build: #1234
Download artifact to: d:\a\1/
Downloading 1 pipeline artifacts...
Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session {some-guid}
Information, Start downloading artifact - FooBar
Information, Minimatch patterns: [**]
Information, Filtered 1540 files from the Minimatch filters supplied.
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 540.0 MB (0%).
Information, Downloaded 231.4 MB out of 540.0 MB (43%).
Information, Downloaded 471.4 MB out of 540.0 MB (87%).
Information, Downloaded 540.0 MB out of 540.0 MB (100%).
Information, 
Download statistics:
Total Content: 540.0 MB
Physical Content Downloaded: 327.6 MB
Compression Saved: 212.4 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 7,539
Nodes Downloaded: 0

Information, Download completed.
Downloading artifact finished.
##[section]Finishing: Download Artifact
```

I tried both ways as @ds-ms stated. Implicitly via `dependsOn` and explicitly via `DownloadPipelineArtifact`. Weird enough to say that when I tried the explicit way I had two download tasks: "Download Artifact" and "DownloadPipelineArtifact" (and yes, `dependsOn` was commented out...).

Can you tell me if this is correct for deploying the wep app?

          - task: AzureRmWebAppDeployment@3
            displayName: 'Deploy FooBar'
            inputs:
              azureSubscription: 'Foo/Bar/Project ({some-guid})'
              WebAppName: 'int-foobar-web'
              DeployToSlotFlag: true
              ResourceGroupName: 'INT-foobar'
              SlotName: 'some-valid-slot'
              Package: '$(System.DefaultWorkingDirectory)/**/FooBar.zip'
