### ISSUE TITLE
Set job's parallel strategy using queue variable

### ISSUE THREAD

**Issue by vlad-zuga** [microsoft/azure-pipelines-yaml#218]
We currently have a problem trying to implement a dynamic behavior for parallel jobs.
We try to use a queue variable (settable at queue-time) to control the number of parallel jobs (`$(NumberOfAgents)`). This variable is to be passed as a parameter to a job template and used for the `parallel` option.

`.vsts-ci.yml`:
```
- template: run-tests.yml
  parameters:
    numberOfAgents: $(NumberOfAgents)
```

`run-tests.yml`:
```
parameters:
  numberOfAgents: null

jobs:
- job: JobName
  strategy:
    parallel: ${{ format('{0}', parameters.numberOfAgents) }}
```
There have been several modifications attempted (get rid of `format`, use directly `$(NumberOfAgents)` in the template, etc.), all having the same output:
` Expected an integer value. Actual value: '$(NumberOfAgents)'`

It seems that the variable expansion is done at run-time, while the YML syntax check is done at queue-time, hence the error. Is there any way to fix/bypass this?

**Comment by Polad10** [comment]
Same issue.

**Comment by vlad-zuga** [comment]
@Polad10 we've managed to make this work by using `$[ variables['NumberOfAgents'] ]` instead of `$(NumberOfAgents)`, where `NumberOfAgents` is a UI added pipeline variable.

`.vsts-ci.yml`:
```
- template: run-tests.yml
  parameters:
    numberOfAgents: $[ variables['NumberOfAgents'] ]
```
`run-tests.yml`:
```
parameters:
  numberOfAgents: null

jobs:
- job: JobName
  strategy:
    parallel: ${{ parameters.numberOfAgents }}
```

**Comment by Polad10** [comment]
Thanks!

**Comment by Polad10** [comment]
I found another workaround:

```yaml
...
jobs:
- job: JobName
  strategy:
    parallel: $[ coalesce(variables['numberOfAgents'], 1) ]
```
