### ISSUE TITLE
Variable/List from file?

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/azure-pipelines-yaml#219]
Hello,

I'm working on a devops pipeline for azure functions. With the azure functions host, there is a file you can define called .funcignore which excludes certain files from function deployment.

I'd like to bring the exclusions from this file into my CopyFiles task but I can't figure out how to parse it.

For example, I want the end result of:
```
pool:
  name: Hosted Windows 2019 with VS2019
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to Staging'
  inputs:
    Contents: |
     **/*
     !.git/**/*
     !.vscode/**/*
     !.azurefunctions/**/*
     !**/Tests/**/*
     !**/
    TargetFolder: '$(Build.StagingDirectory)'
```

I imagine it would be something like  https://github.com/Microsoft/azure-pipelines-yaml/pull/2 but I have no idea how to get the variable list from the file first.

```
pool:
  name: Hosted Windows 2019 with VS2019
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to Staging'
  inputs:
    Contents: |
     ${{ each exclusion in file('my/exclusion/filepath'}}:
       - ${{ exclusion }}
```

Is this possible or do I need to manually/script the sync of this exclude list to the pipeline?
