### ISSUE TITLE
Simple example to build Dockerfile in container

### ISSUE THREAD

**Issue by basickarl** [microsoft/azure-pipelines-yaml#225]
Hi!
It would be super cool if there was a template to show how I can build Dockerfiles in a job. 

I have a Dockerfile in the root of my project. And when I push to my repo on Azure I'd like a job to run a Linux container which has Docker installed on it (this image fits the bill docker:18.09.6 from docker hub). I'd then in that container run the command in bash: docker build -t test .

As stated. There is no simple example as of today!

(to make it clear. I do not wish to use a VM at any stage)

**Comment by efzwo** [comment]
Just use a Microsoft-hosted agent and run the ubuntu-16.04 image which has docker installed

Example yaml:
```yaml
# https://aka.ms/yaml

trigger:
- master

variables: {
  DockerRegistry: 'my.registry.com'
}

stages:
- stage: dockerize
  jobs: 
  - job: buildDocker
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - bash: |
        docker build -t $(DockerRegistry)/imagename:tag .
        docker push $(DockerRegistry)/imagename:tag
```
