### ISSUE TITLE
Download task appears to ignore path

### ISSUE THREAD

**Issue by dmeyer573** [microsoft/azure-pipelines-yaml#226]
I have inserted a download step into my pipeline yaml template so I can control the path used to download the pipeline artifacts, but it appears the step is ignoring the path value. I am using our own agent running on Windows Server 2016 for this job, and it is still downloading the artifact to the default location represented by $(Pipeline.Workspace). This doesn't work for us since we need to be responsible for cleaning up artifacts off the agent machine and intend to have multiple pipelines utilizing this same logic on the agent machine. 

Let me know if there is something we are missing or if there is any additional information we can provide to assist in troubleshooting. In the meantime we will be manually cleaning up the artifacts on the agent machine.

YAML Template
```
parameters:
  agentPoolName: ''

stages:
- stage: DeployPackages
  displayName: 'Deploy Packages'
  jobs:
  - deployment: DeployPackages
    pool:
      name: ${{ parameters.agentPoolName }}
    environment: 'Legacy Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            path: 'Artifacts/$(Build.Repository.Name)/$(Build.BuildId)/'
```

Here is a log for this step with debug turned on:

```
##[debug]Evaluating condition for step: 'Download'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Download
==============================================================================
Task         : Download Pipeline Artifact
Description  : Download Pipeline Artifact
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : Download named artifact from a pipeline to a local path.
==============================================================================
Download from the specified build: #451
Download artifact to: E:\agent\_work\1/
Downloading 1 pipeline artifacts...
Information, Minimatch patterns: [**]
Information, Start downloading artifact - Choco_Ipc.Scheduler.Service
Information, Filtered 1 files from the Minimatch filters supplied.
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 3.6 MB (0%).
Information, Downloaded 3.6 MB out of 3.6 MB (100%).
Information, Download completed.
Information, 
Download statistics:
Total Content: 3.6 MB 
Physical Content Downloaded: 3.6 MB
Compression Saved: 0.0 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 45

Downloading artifact finished.
Finishing: Download
```
