### ISSUE TITLE
Run build with conditional demands

### ISSUE THREAD

**Issue by ivan-nosar** [microsoft/azure-pipelines-yaml#228]
Good day!

I really need to specify conditional demand inside yaml-file. But I found out that there is no documented examples of how I can do it. My own tries wasn't successful at all =(.
For example:

build.yml:
```
jobs:
- job: 'Build job'
  pool: 
    name: 'My pool (Hosted OR Self-Hosted)'
    ${{ if eq(variables.conditionalVariable, 'true') }}:
      demands:
      - ConditionalDemand -equals $(variables.DemandValue)
  steps:
  - template: steps.yml
```

steps.yml:
```
steps:
  - bash: 'echo "Step #1"'
    displayName: 'Step#1'
```

I guess that `{{ ... }}` - is a parse-time expressions and `variables` does not accessible here. I have also tried to define `if` condition inside the `[ ... ]` condition and tried to move values from `variables` to the `parameters` inside `steps.yml` like this:

build.yml
```
jobs:
- template: steps.yml
  parameters: 
    conditionalParam: $[ variables.conditionalVariable ]
    demandValue: variables.DemandValue
```

steps.yml
```
parameters:
  conditionalParam: ''
  demandValue: ''

jobs:
- job: 'Build job'
  pool: 
    name: 'My pool (Hosted OR Self-Hosted)'
    ${{ if eq(parameters.conditionalParam, 'true') }}:
      demands:
      - ConditionalDemand -equals $(parameters.demandValue)
  steps:
  - bash: 'echo "Step #1"'
    displayName: 'Step#1'

```

but this doesn't work for me.

In general, I need to queue build and use demand `demandValue` only if `conditionalParam` is defined during queue (build will be queued through API) and equals to `true`. if `conditionalParam` is not defined or not equals to `true`, build can be assigned to any machine.
Could you please give me an example of how can I reach this out, if this is possible?

**Comment by max-lobanov** [comment]
Also we have tried something like that:
```
jobs:
- job: TestJob
  pool:
    name: $[ coalesce(variables.macos, 'Hosted macOS') ]
    demands: $[ coalesce(variables.mydemand, 'agent.os') ]
  condition: contains(variables.targetPools, 'Hosted macOS')
  steps:
  - bash: pwd
    displayName: TestTask
```

`demands: ${{ coalesce(variables.mydemand, 'agent.os') }}`
if `mydemand` is defined - it will be used. If it is not defined - demand `agent.os` will be used and this demand exists on all machines.
But it fails with error: 
```
Invalid demand '$[ coalesce(variables.mydemand, 'agent.os') ]'. The demand should be in the format '<NAME>' to test existence, and '<NAME> -equals <VALUE>' to test for a specific value. For example, 'VISUALSTUDIO' or 'agent.os -equals Windows_NT'.
```
