### ISSUE TITLE
Error on DownloadPipelineArtifact@1 since today - The given key 'system.jobId' was not present in the dictionary.

### ISSUE THREAD

**Issue by mdmoura** [microsoft/azure-pipelines-yaml#230]
I have the following Pipeline which was working 2 days ago:

```
- job: Prepare
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  # Build and Test tasks omitted
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: Artifacts 
      targetPath: '$(Build.ArtifactStagingDirectory)'
- deployment: Release
  dependsOn: Prepare
  condition: succeeded()
  pool:
    vmImage: Ubuntu-16.04
  environment: production
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadPipelineArtifact@1
          displayName: Artifacts
          inputs:
            artifactName: Artifacts
        # Deployment tasks omitted
```

I now get the following error on DownloadPipelineArtifact@1 task:

    The given key 'system.jobId' was not present in the dictionary.

Is this a bug or something changed in Azure Pipelines?
