### ISSUE TITLE
Invalid yaml triggers pipeline

### ISSUE THREAD

**Issue by dza89** [microsoft/azure-pipelines-yaml#231]
When I do a git push to Azure DevOps of a random feature branch containing the following yaml it triggers my pipeline definition although it's not run on the master branch.

Please investigate

```yaml
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - docs
queue:
  name: Hosted Ubuntu 1604
steps:
- checkout: none
- bash: |
    echo "dummy"


test test
```

Please note that test test is not an error but should be included in the yaml.
