### ISSUE TITLE
./ not being handled correctly

### ISSUE THREAD

**Issue by basickarl** [microsoft/azure-pipelines-yaml#239]
My YAML file:
```
          - task: CopyFiles@2
            displayName: 'YEHAW Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
                sourceFolder: '$(Build.SourcesDirectory)'
                contents: './_buildOutput/**/*'
                targetFolder: '$(Build.ArtifactStagingDirectory)'
```
Azure pipeline output:
```
##[debug]pattern: './_buildOutput/**/*'
##[debug]rooted pattern: '/azp/agent/_work/1/s/./_buildOutput/**/*'
```

As you can see, it includes the ```./``` in the final path. It should resolve to  ```'/azp/agent/_work/1/s/_buildOutput/**/*'```
