### ISSUE TITLE
YAML Azure Pipelines Schedule Trigger Display Name

### ISSUE THREAD

**Issue by jpreese** [microsoft/azure-pipelines-yaml#246]
I have a YAML pipeline in Azure DevOps that has a scheduled trigger.

```yaml
schedules:
- cron: "0 9 * * *"
  displayName: Morning Validation
  branches:
    include:
    - master
```

Though when the trigger is run, I'm not seeing the `displayName` having any impact anywhere. My assumption was that `displayName` in this scenario was the text in the build pipelines history. 

However, it just displays the last commit message in `master`.
![image](https://user-images.githubusercontent.com/6980197/60518637-e2cff480-9caf-11e9-9735-46eb9602fcc0.png)
(I expected "Add cron" to say "Morning Validation")

Is this expected? Did I misunderstand what `displayName` does?
