### ISSUE TITLE
How to give permission to scripts to run git commands

### ISSUE THREAD

**Issue by cdmihai** [microsoft/azure-pipelines-yaml#248]
I need to run a powershell script that runs various git read operations (clone, checkout, etc) on external public github repos (not the repo running the CI job). This does not seem to work, and documentation seems outdated: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml

What makes it work in the old style non-yaml pipeline is ticking "allow scripts to access the OAuth token", but I have no idea how to do this with yaml.

yaml failing output:
```
git : Note: checking out '7bd12afef8fe3b88d0798974c6e060f76f043b8e'.
At line:1 char:1
+ git checkout 7bd12afef8fe3b88d0798974c6e060f76f043b8e
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Note: checking ...060f76f043b8e'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
##[debug]Exit code: 1
##[debug]Leaving Invoke-VstsTool.
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.logissue type=error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed]Error detected
##[debug]Leaving D:\a\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.151.1\powershell.ps1.
```

old style pipeline:
```
Note: checking out '7bd12afef8fe3b88d0798974c6e060f76f043b8e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7bd12afe Integrate solution dependencies in static graph
```

**Comment by cdmihai** [comment]
I tried the suggestion in https://github.com/microsoft/azure-pipelines-agent/issues/1833 but it still does not work, same failure.

```
variables:
  system.accesstoken: $(System.AccessToken)
```

**Comment by matteotumiati** [comment]
Have you tried with this?

```
- task: MyTask'
  inputs:
    ...
  env:
    SYSTEM_ACCESSTOKEN: $(system.accesstoken)
```

**Comment by cdmihai** [comment]
Yes, but not luck.

**Comment by matteotumiati** [comment]
In the first post you mention that you need to do operations on "external public github repos", so I don't think you need the access token from the build agent. 

I made this yaml template and it's running fine on my own agent:

```
steps:
  - task: PowerShell@2
    displayName: Clone repository
    inputs:
      targetType: inline
      script: |
        cd "C:\Program Files\Git\cmd\"
        git.exe clone https://github.com/microsoft/azure-pipelines-yaml.git "$(Build.SourcesDirectory)\Azure-Pipelines\" -q

  - task: PowerShell@2
    displayName: Show repo root content
    inputs:
      targetType: inline
      script: |
        cd "$(Build.SourcesDirectory)\Azure-Pipelines\"
        Get-ChildItem -Path .
```

The first powershell task is just cloning this repository and the second one is checking that all the files from the root folder are actually there.
