### ISSUE TITLE
Sprint 154 seems to have broken my library variables in my deployment job

### ISSUE THREAD

**Issue by ed-sparkes** [microsoft/azure-pipelines-yaml#250]
Until 1st July 2019 (when sprint 154 was released) the following yaml was working great, the aws vars were being set from my library vars and the aws cli was working fine. Now the env vars dont seem to be set. The sprint 154 [release note](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-154-update#deployments-in-yaml-pipeline) suggests there have been some changes to deploy steps and vars but the documentation doesnt seem to have been updated to reflect this, last update was in May ? 

Confused and would like my deployment pipeline to start working again asap, please advise 

Note the echo of the Key in the script below is not printing out the value and getting an error from the aws cli saying `credentials not found`

Thanks, Ed

```yaml
- stage: Deploy_to_DEV
  jobs:
    - deployment: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        - group: AWS Credentials
        - name: WEB_BUCKET
          value: redacted
        - name: DISTRIBUTION_ID
          value: redacted
      environment: 'redacted'
      strategy:
        # default deployment strategy
        runOnce:
          deploy:
            steps:
              - task: UsePythonVersion@0
                inputs:
                  versionSpec: '3.6'
                  architecture: 'x64'
              - script: | 
                  sudo pip3 install --upgrade pip
                  pip3 install awscli --upgrade --user
                  export PATH="/home/vsts/.local/bin:$PATH"
                  aws --version
                  echo What
                  echo $AWS_ACCESS_KEY_ID
                displayName: 'Install AWS CLI'
                env:
                  AWS_ACCESS_KEY_ID: $(nonprod.AWS_ACCESS_KEY_ID)
                  AWS_SECRET_ACCESS_KEY: $(nonprod.AWS_SECRET_ACCESS_KEY)
              - script: | 
                  echo $AWS_ACCESS_KEY_ID
                  export PATH="/home/vsts/.local/bin:$PATH"
                  aws s3 sync --acl public-read --sse --delete /home/vsts/work/1/cj-client-build s3://$WEB_BUCKET
                displayName: 'Deploy to S3'
                env:
                  AWS_ACCESS_KEY_ID: $(nonprod.AWS_ACCESS_KEY_ID)
                  AWS_SECRET_ACCESS_KEY: $(nonprod.AWS_SECRET_ACCESS_KEY)
              - script: | 
                  export PATH="/home/vsts/.local/bin:$PATH"
                  aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
                displayName: 'Invalidate CloudFront Cache'
                env:
                  AWS_ACCESS_KEY_ID: $(nonprod.AWS_ACCESS_KEY_ID)
                  AWS_SECRET_ACCESS_KEY: $(nonprod.AWS_SECRET_ACCESS_KEY)
```
