### ISSUE TITLE
Unable to use a variable for the environment value in a deployment

### ISSUE THREAD

**Issue by alexmg** [microsoft/azure-pipelines-yaml#251]
It is not possible to use a variable for the value of the `environment` property within a `deployment`. It is possible to use variables for other properties within a `deployment` such as `pool.vmImage`.

In the example YAML below the `$(vmImageName)` variable is expanded but the `$(myEnvironment)` variable is treated as verbatim text and becomes the name of an automatically created environment.

```yaml
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName) # This is expanded
    environment: $(myEnvironment) # This is not expanded
```

It seems strange that this particular property cannot be set using a variable given that having multiple environments is rather common.
