### ISSUE TITLE
top level variables are not replaced in a multi-stage pipeline

### ISSUE THREAD

**Issue by vigneshmsft** [microsoft/azure-pipelines-yaml#255]
I am trying to setup a multi-stage pipeline to run on a private agent.
I believe top-level variables aren't getting replaced in subsequent stages as in the example below.

``` yaml
name: 'BuildName-$(date:yyyy.M)$(rev:.r)'

trigger:
- master

variables:
  pool: 'MyBuildAgent' #other global variables defined below

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        pool: $(pool) #works as expected and job runs on MyBuildAgent
        continueOnError: 'false'
       steps: # Build steps defined here

  - stage: Deploy
    displayName: Deploy
    jobs:
      - deployment:
        environment: 'UAT'
        pool: $(pool) # fails; #Line 5#
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo $(pool) # prints MyBuildAgent if $(pool) in Line 5 is removed or $(pool) replaced with hard coded name in Line 5 

```

If I let the 'Deploy' stage run on a hosted agent by omitting to set the pool property, the $(pool) name is expanded correctly as set in the global variable.

Could be related to #251

**Comment by vigneshmsft** [comment]
It works on the correct agent, If I replace the special deployment task with a job like below.
So maybe it a problem only on custom jobs like `deployment`

``` yaml
  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: Deploy
        pool: $(pool)
        steps:
          - script: echo $(pool)
```

**Comment by robert-skarzycki** [comment]
I have a similar issue when setting self-hosted pool on deployment job. I have a multi-stage pipeline like this:
```
trigger:
[... omitted...]
variables:
  agentImageName: 'ubuntu-latest'  
  selfHostedPoolName: 'My build agents pool'

stages:
- stage: Build
  displayName: Build
  jobs:
- stage: Build
  displayName: Build
  jobs:
  - job: Build_UI
    displayName: Build UI
    pool:
      vmImage: $(agentImageName)    
    steps:
    [... omitted ...]
  - job: Build_Backend
    displayName: Build Backend
    pool: $(selfHostedPoolName)    
    steps:
    [... omitted - it's dotnet build & publish ...]

- stage: Deploy
  displayName: Integration deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy_UI
    displayName: 'Deploy UI'
    environment: 'integration'    
    pool:
      vmImage: $(agentImageName)
    strategy:
      [... omitted ...]           
  
  - deployment: Deploy_Backend
    displayName: 'Deploy Backend'
    environment: 'integration'    
    pool: $(selfHostedPoolName)
    strategy:
      [... omitted ...]              
```

Both build jobs - one on Microsoft-hosted and one on self-hosted agents - are going fine. But deployment job runs fine only when using Microsoft-hosted agent, job that runs on self-hosted one, just returns an error message:
```
##[error]No pool found with ID 0.
```

The self-hosted agent runs on Ubuntu VM on Azure and was configured today, i.e. created with `vsts-agent-linux-x64-2.154.1.tar.gz` package.

**Comment by vigneshmsft** [comment]
Update: I have raised this issue in their forums and the dev team have acknowledged it.
I am not sure about when it will be fixed but hopefully soon.

**Comment by AlbertBrand** [comment]
It also seems that
```
pool:
  name: $(poolName)
```
doesn't work. The only expansion that does work is of `vmImageName`.
The workaround for us is hardcoding the agent name.

**Comment by razidare** [comment]
Same issue for me when trying to pass the pool to a template as a parameter and then use it inside the template for a `- deployment` job
``` 
   ##[error]No pool found with ID 0.   
   Started: Just now 
   Duration: 56s
```

**Comment by TroySchmidt** [comment]
It seems that the ONLY expansion that works is at the job level.  Testing it for jobs or stage results in incorrect expansion of the value set at runtime.
```
- job: 'Individual Job'
  variables:
    mine: $(buildOne)
  steps:
    - task: ANY
      condition: eq(variables.mine, 'test')
     
```

**Comment by josheinstein** [comment]
I was beating my head against my desk trying to find the right Google search to figure out why this was happening. As of 2019-09-18, the problem still exists. Using the default template for Azure Functions deployment, the build stage is happening on Windows, and the Deploy stage is happening on Ubuntu, despite Ubuntu not being specified anywhere. So, hard coding it is...

**Comment by timmkrause** [comment]
Even without expansion it doesn't work for me. I just want to set the `vmImage` on the special `deployment` job and I can't get it to work:

```
variables:
  vmImageName: 'windows-2019'
  
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      # Seems to work with any quote/non-quote combination
      vmImage: $(vmImageName)
      demands:
      - ...
    variables:
      ...
    steps:
    - ...
- stage: TA
  jobs:
  - deployment: Deployment
    pool:
      # Fallback to Ubuntu16.
      vmImage: $(vmImageName)
```

Build stage/job successfully uses:

```
Pool: Hosted Windows 2019 with VS2019
Agent: Hosted Windows 2019 with VS2019 2
```

TA stage/deployment job always falls back to:

```
Pool: Azure Pipelines
Image: Ubuntu16
```
