### ISSUE TITLE
Re-run/deploy a stage on YAML pipeline

### ISSUE THREAD

**Issue by scabana** [microsoft/azure-pipelines-yaml#260]
There doesn't seem to be a way to re-run a stage in a multi-stage yaml pipeline. 

The scenario is the following: 
1. Build 1.0
2. Deploy 1.0
3. Build 2.0
4. Deploy 2.0
5. Deployment failure
6. Deploy 1.0 (Rollback in the end)

Today, from the UI, the only way I've seen this possible would be to rebuild from 1.0 commit. This could be problematic if the build fetches external resources that have been updated in time for example.

I tried with something that looks like this: 

```
azure-pipelines.yml
trigger:
  branches:
    include:
    - master
    - story-*
    - bug-*

stages: 
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/automatedtests.run.yml

azure-pipelines/build.yml
stages:
- stage: Build
  jobs: 
  - job: Build
  **more stuff here to do the build**

azure-pipelines/automatedtests.run.yml
stages:
- stage: RunAutomatedTests
  jobs: 
  - deployment: RunAutomatedTests
    pool:
      name: Clearance 
    environment: 'AutomatedTests'
    strategy:
      runOnce:
        deploy:
        **more stuff here to run the automated tests**
```

Haven't found any way to re-run the automated tests part (I guess this would also apply to a specific prod environment later on).
