### ISSUE TITLE
Multi-Stage pipeline variable sharing

### ISSUE THREAD

**Issue by scabana** [microsoft/azure-pipelines-yaml#264]
Within a yaml pipeline, if the pipeline contains two stages, in the first stage, a script task does this: ```echo "##vso[task.setvariable variable=SomeVariableName;]SomeValue"```, the variable does not seem to be expanded on the next stage. Is this expected?

**Comment by goel-sunny** [comment]
Yes the syntax you wrote here is for sharing the variable among steps of same Job. and if you want to share the variable among different Jobs then you have to use the **isOutput=true** syntax for sharing the variable among different jobs of same stage but if you want to share the variable among different stages then you have to define the variable at the top of stages.

**Comment by matteotumiati** [comment]
This is not something supported out-of-the-box unfortunately, so I had to implement something myself which is kind of a hack (and probably not even the best good-looking code), but it works. 

Just a rough explaination: my idea is to create two templates, one used in "Stage A" to create a JSON file where all my <Variable,Value> are stored, the last used in "Stage B" to read the same JSON and re-create properties.

This template is called `write-props-across-stages.yml`

```yaml
parameters:
- name: properties
  type: object
  default: []

steps:

- task: PowerShell@2
  displayName: 'Prepare variables for share across stages' 
  env:
    ${{ each item in parameters.properties }}:
      ${{ format('SCRIPT_PARAM_{0}_KEY', item.index) }}: ${{ item.name }}
      ${{ format('SCRIPT_PARAM_{0}_VAL', item.index) }}: ${{ item.value }}
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
    
      Write-Host "Starting auto-discovery for variables..."
      
      # Initialize the dictionary that will host key-value pair of variables
      $propList = @{}

      # Start an almost-infinite loop, so to discover variables
      For ($i=0; $i -le 1000; $i++) {
        # Get the variable names
        $keyName = "SCRIPT_PARAM_$($i)_KEY"
        $keyValue = "SCRIPT_PARAM_$($i)_VAL"

        # Get the variables value
        $keyName = (Get-Item env:$($keyName) -ErrorAction SilentlyContinue).Value
        $keyValue = (Get-Item env:$($keyValue) -ErrorAction SilentlyContinue).Value

        # If we cannot find a value associated to the key,
        # then it's because we reached the end already
        if ([string]::IsNullOrEmpty($keyName)) {
          Write-Host "Reached the end of pre-defined variables."
          break  
        }

        # Add the found key to the dictionary
        $propList.Add($keyName, $keyValue)        
      }

      # Save the dictionary as JSON into a shared path of the pipeline workspace
      # so it can be taken up later to be read
      $propList | ConvertTo-JSON | Set-Content -Path $(Pipeline.Workspace)/variables.json

- publish: $(Pipeline.Workspace)/variables.json
  artifact: variables
  displayName: 'Share variables'
```

You can invoke the template quite simply:
```yaml
- template: Eng/Pipelines/Templates/write-props-across-stages.yml
  parameters:
    properties:
    - name: 'myVariableName'
      value: $(MyVariableName)
      index: 0
```

Then you need to read the JSON and re-create all the variables from the second stage, and for this you can use `read-props-across-stages.yml`:

```yaml
- job: PreBuildVariablesJob
  displayName: Setup Variables from previous stage
  steps:
  - download: current
    artifact: variables
    displayName: 'Download shared variables'

  - pwsh: |
      $json = Get-Content $(Pipeline.Workspace)/variables/variables.json | ConvertFrom-Json -AsHashtable
 
      ForEach ($prop in $json.Keys) {
        echo "##vso[task.setvariable variable=$prop;isOutput=true]$($json["$prop"])"
      }
    displayName: 'Build variables across stages'
    name: 'prebuildVariables'
```

All the variables passed from Stage A will then be accessible, because produced by the job `PreBuildVariablesJob`:

```yaml
- stage: B
  jobs:
  - template: Eng/Pipelines/Templates/read-props-across-stages.yml

  - job: build
    displayName: build
    dependsOn: PreBuildVariablesJob
    variables:
      myVariableName: $[ dependencies.PreBuildVariablesJob.outputs['prebuildVariables.MyVariableName'] ]
    steps:
    - script: echo $(myVariableName)
```

Again, as you can see, even if the code works it's not so easy and it has also some limitations:
1. I specified a limit of 1000 variables, but that can be increased/decreased;
1. You have to specify the index when creating the variables in Stage A, which is an always increasing number and must be unique for each variable you are adding;
1. It's not "perfect" with secrets....
1. For all the stages where you need to use the same set of variables created in Stage A you will have to do the same approach and copy-paste the template everywhere;
1. You need to explicitly set the `dependsOn` attribute every time you need to read a variable, so that you are 100% sure that the `read-props-across-stages.yml` file is executed first to have variables available in the job.

I haven't investigated any improvements to be honest because this was sufficient to me, but this could get way better simply using custom tasks and pipeline decorators (pre-job or post-job tasks):
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops

I'm also open to suggestions, so if you have a better solution I'm all ears 😃
