### ISSUE TITLE
Is there some examples for service container?

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/azure-pipelines-yaml#266]
I wanna to use a sidecar container for my test, I'm trying to use it in the linux build agent `ubuntu-16.04`,with pipeline config as follows: 

``` yaml
trigger:
- '*'

jobs:
- job: Linux

  pool:
    vmImage: 'ubuntu-16.04'
  
  resources:
    containers:
    - container: redis
      image: redis

  services:
    redis: redis
    ports:
      - 6379/tcp

  steps:
  - bash: ./build.sh
    displayName: 'Build Script'

- job: Windows

  pool:
    vmImage: 'windows-2019'

  steps:
  - script: dotnet --info
    displayName: 'dotnet info'

  - powershell: ./build.ps1
    displayName: 'Build Script'
    env:
      Nuget__ApiKey: $(nugetApiKey)
      Nuget__SourceUrl: $(nugetSourceUrl)
```

but got two errors:  

``` 
/azure-pipelines.yml (Line: 15, Col: 3): Unexpected value 'resources'
/azure-pipelines.yml (Line: 23, Col: 7): A sequence was not expected 
```

build details:<https://weihanli.visualstudio.com/Pipelines/_build/results?buildId=852&view=results>

reference:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml#single-job
