### ISSUE TITLE
Container Resource Trigger does not fire

### ISSUE THREAD

**Issue by tedescomicchidev** [microsoft/azure-pipelines-yaml#270]
Based on this article https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md, when an ACR based Container Resource in a YAML pipeline is defined, I expect the trigger fires every time a new tag has been added to the repository if no filters (include or exclude) are defined.
Unfortunately my YAML Pipelines does not start when a tag has been created in ACR.
Here my sample pipeline:
pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
  - container: c1  
    type: ACR
    subscription: 'pipelinetriggerdemo1 - Azure'
    registry: pipelinetriggerdemo1acr.azurecr.io
    image: pipelinetriggerdemo1

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

**Comment by ondrejhlavacek** [comment]
+1 here, my yaml is

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources: 
  containers:
  - container: connection
    type: ACR
    subscription: 'Keboola DEV'
    registry: 'connection.azurecr.io'
    image: connection
    trigger:
      tags:
      - production-*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
```

**Comment by BzSpi** [comment]
Same here with this configuration.
Really don't know where to find support ...

```
trigger:
  - master

resources:
  containers:
    - container: acr_hook
      type: ACR
      AzureSubscription: <sensitive>
      resourcegroup: <sensitive>
      registry: <sensitive>
      repository: <sensitive>
      trigger:
        tags:
          include:
            - latest

variables:
  - group: deployment-variables

stages:
  - stage: build
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-18.04'

        steps:
          - bash: 'env'
            displayName: 'Debug'
```
