### ISSUE TITLE
Template Job Inserting Template step 

### ISSUE THREAD

**Issue by SuperHugh** [microsoft/azure-pipelines-yaml#271]
I think I have encountered an issue while trying to re-use template job and template steps.
My azure-pipeline.yaml file:
```
resources:
  repositories:
    - repository: templates
      type: git
      name: shared-azure-deployment
      ref: refs/heads/test/template-insertion

trigger: none   # CI builds are disabled
pr: none        # PR builds are disabled

jobs:
- template: .pipelines/jobs/test-template-job-insertion.yml@templates
  parameters:
    insertedSteps:
      - template: .pipelines/steps/test-template-steps-insertion.yml
        parameters:
          displayName: 'Test template steps insertion'
```

My job template (in shared-azure-deployment repo):
```
parameters:
  insertedSteps: []

jobs:
- job: testTemplateInsertion
  steps:
  # run inserted steps
  - ${{ parameters.insertedSteps }}
```

My step template:
```
parameters:
  displayName: 'Inserted steps'

steps:
- script: echo ${{ parameters.displayName }}
```

When I queue a new build, I get the following error message:
> /.pipelines/jobs/test-template-job-insertion.yml@templates: File /.pipelines/jobs/.pipelines/steps/test-template-steps-insertion.yml not found in repository [replaced]/_git/shared-azure-deployment branch refs/heads/test/template-insertion version b180feb7db8a947477b052bc8068028eed0d5ff2.

When I look at my shared-azure-deployment repo, the test-template-steps-insertion.yml file commit is b180feb7 in branch test/template-insertion (thus it exists).

I have looked at other posts and found nothing about this issue, hoping this is not a duplicate.

Thanks!
