### ISSUE TITLE
System.PullRequest.SourceBranch not usable for build number

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/azure-pipelines-yaml#274]
For PR builds, having $(Build.SourceBranchName) be "merge" is kind of useless.

It would be awesome if $(System.PullRequest.SourceBranch) was usable by the yaml build.

my yaml attempt (which outputs `MyApp_merge_2019.07.30.1`)
```yaml
name: 'MyApp_$(branchName)_$(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)'

trigger:
- master
- release/*

variables:
  branchName: ${{coalesce(variables['System.PullRequest.SourceBranch'], variables['Build.SourceBranchName'])}}
```

Based on the pipeline, it looks like this is due to the variable being set at queue time?

![image](https://user-images.githubusercontent.com/19917677/62168699-bd083080-b2eb-11e9-930f-6e17c757c1ef.png)
