### ISSUE TITLE
Pick one of two strings in an expression, ternary operator style

### ISSUE THREAD

**Issue by tomduncalf** [microsoft/azure-pipelines-yaml#278]
Is there a way using expressions to evaluate to one string if something is true, or another string if something is false?

My use case is selecting a different AppCenter distribution group ID based on the branch being built, what I'd like to do is something like:

`distributionGroupId: ternary(eq(Build.SourceBranch, 'develop'), 'groupId1', 'groupId2')`

and it would evaluate arg 1 and select arg 2 or 3 depending on whether arg 1 == True or not. 

I tried this:

`distributionGroupId: coalesce(and(eq(Build.SourceBranch, 'develop'), 'groupId1), 'groupId2')`

But it didn't seem to work properly.

For now I've duplicated the entire step with `eq`/`ne` conditions on each, but this involves a fair bit of duplication.

Suggestions welcome! Thanks

**Comment by JoeBrockhaus** [comment]
Conditional execution of _the entire step_ is a big hammer. 


If you're after a single mapping, what about a [conditional insertion](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#conditional-insertion)? _(3rd example)_

```yaml

props:
  ${{ if eq(Build.SourceBranch, 'develop') }}:
    distributionGroupId: groupId1
  ${{ if ne(Build.SourceBranch, 'develop') }}:
    distributionGroupId: groupId2

```

For _a set_ of properties, I think you can also create a mapping 'object' as a variable, parameter, etc, then 'index' into it using the value: `${{ parameters.mapper[Build.SourceBranch] }}`.
