### ISSUE TITLE
Cannot trigger build via push to another repository in a YML Pipeline

### ISSUE THREAD

**Issue by tylermurry** [microsoft/azure-pipelines-yaml#291]
I have the following repositories:
* `my-app-repo` - Contains the code for the app
* `pipeline-repo` - A collection of pipelines that build my-app-repo as well as others

I'm trying to build a yml pipeline within `pipeline-repo` that will be triggered on a commit to `my-app-repo`.

According to [the official Repository Triggers section of the design](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md#repositories), it sounds possible - but then the docs double back and say:

> However, triggers are not enabled on repository resource today. So, we will keep the current behavior and in the next version of YAML we will enable the triggers by default.

I'm not sure how to interpret Repository Triggers now. Either way, here's what I've tried:

**pipeline-repo/my-app-repo-build.yml**
```yml
resources:         
  repositories:
  - repository: target_repo      
    type: git
    name: my-project/my-app-repo
    trigger:
      branches:
        include:
        - master

jobs:
  - job: 
    steps:
      - script: echo "Should be triggered from a push to my-app-repo!"
```

The build is not triggering when I push to `my-app-repo`. It only kicks off for commits to the *source* repo (`pipeline-repo`) which I cannot change since that holds the yml definition.

Am I missing something easy?

**Comment by adriantorrie** [comment]
From what I can tell you're doing it around the wrong way. The app repo needs to reference the pipeline repo. [from here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories):

```yaml
# Repo: my-project/my-app-repo
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: git
      name: my-project/pipeline-repo

jobs:
- template: common.yml@templates  # Template reference
```

```yaml
# Repo: my-project/pipeline-repo
# File: common.yml
parameters:
  vmImage: 'ubuntu 16.04'

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: npm install
  - script: npm test
```
