### ISSUE TITLE
Artifact is being removed between jobs

### ISSUE THREAD

**Issue by marcinma** [microsoft/azure-pipelines-yaml#294]
I have 2 job
Each of them is executed on same agent
Job1: DownloadBuildArtifacts
```
Downloading release-artifacts/release-image to /home/user/Downloads/myagent/_work/14/a/release-artifacts/release-image
Successfully downloaded artifacts to /home/user/Downloads/myagent/_work/14/a
```

Job2: tries to read downloaded artifact
```
cat: /home/user/Downloads/myagent/_work/14/a/release-artifacts/release-image: No such file or directory
```
I would expect artifact to persist during pipeline

excerpt from yaml:
```yml
  jobs:  
  - job: Read 
    pool: Default
    displayName: Read
    steps:
    - task: DownloadBuildArtifacts@0
     #... rest of code
  - deployment: Build
    dependsOn: Read
    pool: Default    
    strategy:
      runOnce: 
        deploy:
          steps:
          - script: 
              cat $(System.ArtifactsDirectory)/release-artifacts/release-image
```
