### ISSUE TITLE
Support agent variables in template conditions

### ISSUE THREAD

**Issue by kzu** [microsoft/azure-pipelines-yaml#297]
> Related issue: https://github.com/Microsoft/azure-pipelines-yaml/issues/30#issuecomment-435927695

So, according to [that comment](https://github.com/Microsoft/azure-pipelines-yaml/issues/30#issuecomment-435927695) system variables work and indeed I see it [in other](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/common/templates/stages/build-test-publish-repo.yml#L36) [templates](https://github.com/dotnet/corert/blob/master/eng/xplat-job.yml#L38) where I assume it's because because they just use [system variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables)? 

It would be *great* if support for [agent variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables) could be added too. I understand it would mean template expansion would be closer to the [job orchestration](https://github.com/microsoft/azure-pipelines-yaml/issues/30#issuecomment-435927695) phase in a way, since you'd need to know the agent that will run a certain stage before expansion with agent variables can be performed, but I think it would be extremely valuable.

Here's a concrete example I'm trying to implement (and failing since I think it's sort of by design), which would benefit from this support:

template:

```
# Installs PowerShell Core
parameters:
  version: '6.2.2'

steps:
- ${{ if eq(variables['Agent.OS'], 'Darwin') }}:
  - template: /provision.yml
    parameters:
      displayName: Provision PowerShell Core v${{ parameters.version }} for Mac
      item: 'https://github.com/PowerShell/PowerShell/releases/download/v${{ parameters.version }}/PowerShell-${{ parameters.version }}-osx-$(Agent.OSArchitecture).pkg"'

- ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
  - template: /provision.yml
    parameters:
      displayName: Provision PowerShell Core v${{ parameters.version }} for Windows
      item: 'https://github.com/PowerShell/PowerShell/releases/download/v${{ parameters.version }}/PowerShell-${{ parameters.version }}-win-$(Agent.OSArchitecture).msi'

- ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=PATH;]$($env:PATH + ';' + $env:ProgramFiles + '\PowerShell\' + '${{ parameters.version }}'.Substring(0, 1))"
    displayName: Add PowerShell Core to PATH
```

pipeline:

```
- stage: Windows
  dependsOn: []
  jobs:
  - job: Windows
    pool: 
      vmImage: windows-2019
    steps:
    - checkout: none
    - template: install-pwsh/v1.yml
    - pwsh: write-host PowerShell $PSEdition $PSVersionTable.PSVersion
```

NOTE: I *know* I can do run-time condition checking in this case, but to me the benefit of this approach (if it worked) is that the job log would be much more streamlined if all the steps that don't apply at all depending on system/built-in variables don't show up at all in the execution "plan", rather than having a mixture of run and skipped steps.
