### ISSUE TITLE
Allow to define varialbles as objects

### ISSUE THREAD

**Issue by marcinma** [microsoft/azure-pipelines-yaml#298]
Currently If I would like to accept parameters in template like:

```yaml
parameters:
  images: [
                  {
                      name: "example",
                      version: "1",
                  },
  ]
```
there is no way for me to define it once in top of pipeline yaml or in template like:
```yaml
variables:
  images: [
                  {
                     name: "real-image",
                      version: "1.10",
                  },
  ]
- template: image-build.template.yaml
      parameters:
         images: $(images)
- template: image-push.template.yaml
      parameters:
        template: "my-image-variables.yaml"
```
instead I need to repeat this set per each template step
