### ISSUE TITLE
Support conditions for templates

### ISSUE THREAD

**Issue by TingluoHuang** [Microsoft/azure-pipelines-yaml#30]
copy from: https://github.com/Microsoft/azure-pipelines-agent/issues/1749

Have you tried trouble shooting?
Queuing a build generates an error. Unexpected value 'condition'.

Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...

OS of the machine running the agent? Windows

VSTS Type and Version
VSTS

If VisualStudio.com, what is your account name? https://fsmb.visualstudio.com

What's not working?
I am trying to set up a YAML build. We have a lot of builds and our existing definitions use task groups. I am moving the task group logic into a template so they can be shared across build definitions. The templates are stored in a separate repository. All this is working correctly.

There is one step that shouldn't execute when it is a PR build so I tried to do this.

- template: sharedstep.yml@templates
  parameters:
     value: true
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
The build won't queue because of the error - Unexpected value 'condition'.

It would be nice if templates could be conditional like tasks are. Right now the workaround would be to either use a parameter or specify the condition inside the template but the template may not always know the correct condition to use.

Agent and Worker's Diagnostic Logs
It is not queuing so there is no log.

Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

Tasks Repository - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue here.
Hosted Agent Image Repository - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue here.
If you are hitting a generic issue about VSTS/TFS, please report it to the Developer Community

**Comment by ericsciple** [comment]
conditions are evaluated at runtime, not during plan compilation. I dont think we should mix the two

**Comment by vtbassmatt** [comment]
Either the template should be taught the right condition (most common case?) or it should be parameterized if the user of the template needs to be in control.

**Comment by CoolDadTx** [comment]
@ericsciple, Are you saying that a -template is effectively a #include of the underlying template into the existing YAML file? If so then why, on the original issue, did you say the syntax (I'm trying to use below) is supported?

@vtbassmatt, Why was this issue closed when the original issue this was based upon (before the migration) is still valid and still not working? What do you mean by "taught the right condition"? Based upon your second statement of "parameterized" it seems like you're trying to suggest that a template should have some sort of "enabled" parameter that should be set by the code. That doesn't make sense to me because none of the existing tasks do this because they support the condition clause. The ask on this issue is that we can use condition on a template. Why is this different than an existing task? Even if it currently doesn't support it, the recommended solution of using a template expression isn't working for people, myself included. When I try this (from Eric's original solution under the original issue).

```yaml 
variables:
   someVar: true
steps:
- ${{ if ne(variables['someVar'], 'true') }}:
   - template: mytemplate.yml
```

I get the error:
The directive 'if' is not allowed in this context. Directives are not supported for expressions that are embedded within a string. Directives are only supported when the entire value is an expression.

**Comment by ericsciple** [comment]
what does your template look like?

**Comment by ericsciple** [comment]
When I run this:

```yaml
pool: hosted ubuntu 1604
variables:
   someVar: true
steps:
- ${{ if ne(variables['someVar'], '') }}:
   - template: mytemplate.yml
- script: echo hi
```

I don't get any error. I think the error about the directive not allowed must be coming from your template file.

I would expect the error to include the file name and line and column. Does it not?

**Comment by CoolDadTx** [comment]
@ericsciple I think you're right. I have been updating the templates to use the inline template expression stuff and I finished updating them all. I had temporarily commented out that expression to get past it. I added it back and I don't get the error anymore. I cannot confirm it is working as expected yet because the build is failing in an earlier step but it queues now. Thanks.

**Comment by vtbassmatt** [comment]
Think of template expansion like a Jinja or Handlebars template (though it doesn't operate on pure text - it operates on the DOM of the YAML file). The conditional-inclusion stuff there is `${{ if ... }}` as you and Eric have been talking about. The `condition` directive is a runtime concept. That's what I don't want to mix.

Both of them support roughly the same capabilities in the expression language. If we're missing something there, let us know so we can schedule it.

**Comment by CoolDadTx** [comment]
@vtbassmatt , the template expression stuff is mostly hacky to me. I would argue that the goal should be to be able to copy/paste as much existing logic from a YAML file to a template and it still work. As such I would expect to be able to reference parameters inside a condition just like I can reference variables and env vars. I don't believe templates currently support variable declarations but if they did I would expect to be able to use them just like any other non-template YAML file. 

As a user of YAML I shouldn't have to be concerned with how the parser is implemented just to use it for "normal" things. My focus should be on getting my standalone scripts running inside the engine. That is hard enough as it is without the added complexity of figuring out the rules of the YAML parser.

**Comment by carct** [comment]
guys, i seem to encounter a bit of an issue with a condition, which i tried setting in multiple ways :)

my current approach on setting it on a template yaml reference is as you said above:

`jobs:
- ${{ if in(variables['TestRun'], 'SmokeTests', 'AllTests') }}:
  - template: ".\\my-template.yml"`

indentation seems to be fine, the template line is one tab more to the right that the condition line and the condition lines starts at the same indentation as the 'jobs' line

the thing is that i don't get any error, but it doesn't execute either, although i'm sure that i do have a variable 'TestRun' (settable at queue time, but it has a default value on it) // does it influence that this variable is declared in the UI side of the Build Definition and not in the YAML (i know that some time ago you couldn't declare in the yaml that the variable should be settable at queue time) ?

i tried in a few other ways with basically the same main expression 'in(variables['TestRun'], 'SmokeTests', 'AllTests')', but the above seemed to get me most far :) only that it is always false :)

btw, is it normal behavior that if the condition set a on a template reference evaluates to false to not even see that phase in the Build Execution ? (as opposed to the message 'skipped' that i can see when a condition is not met on a specific step)

appreciate any kind of help, thank you!

**Comment by vtbassmatt** [comment]
@carct `variables` aren't visible at template expansion time. I'm working on a doc to make this more clear. As a user of the YAML build system, there are 3 execution times to consider:
- template expansion
- job orchestration
- agent-side runtime

Template expansion is just a DOM-manipulation step. Think of text templating like Jinja or C preprocessor macros, slightly enlightened about YAML structures so that you don't have to worry as much about spacing. It's not aware of most of the other features of the YAML syntax, including variables. It only considers `parameters` which are explicitly for the template expansion step.

**Comment by carct** [comment]
@vtbassmatt it is a bit confusing: "variables aren't visible at template expansion time"
but above, @ericsciple used it basically the same way, or the important difference is that his template is seen as a step of a phase and not as a whole job, as in my case ?

also, your line is again confusing as I successfully manage to pass parameters values to the template with the help of variables

another thing that i did notice while working with these YAML Templates is that **inside a template** i used in the condition of a step the following line "condition: eq(variables['myVar'], 'true')", nothing weird until now, just that 'myVar' is actually a parameter of the template and does not exist as a Var, so again.. a bit confusing :)

coming back to my issue, what would your suggestion be regarding it ? 
i confirmed that the only issue is that the variable is not expanded at that level

thanks for your time !

**Comment by vtbassmatt** [comment]
Hey, sorry, I was wrong about what's in scope in the various steps. Can you paste in your whole YAML (or if not comfortable sharing here, you can email me: mattc at xbox dot com)?

**Comment by carct** [comment]
well, i did manage to make it work as per my latest edit to the post

the only thing is that it was a bit confusing and to be frank with you, i would like to still be able to set such a condition on Jobs Template
i don't find it too useful to have this kind of structure available:
```
jobs:
 - ${{ if in('something', 'opt1', 'opt2') }}:
   - template: ".\my-jobs-template.yml"
     parameters:
...........................
```
but unable to actually use some variables in that if execution condition :)

in my current case, i can be ok with the conversion to a Steps Template, but in other future cases i might not be so keen on that :))

if you think that we can get around the discussed limitations, we can take this to private, but from what i understood from you this is kinda' the way to do it...

**Comment by vtbassmatt** [comment]
Thanks. This is something we'll consider for a future enhancement. I don't know if there's a good reason why variables aren't available in that context, or if it's just an implementation quirk.

**Comment by kittaakos** [comment]
> For the completeness; the `if ne(variables['someVar'], '')` condition (from [above](https://github.com/Microsoft/azure-pipelines-yaml/issues/30#issuecomment-435505731)) works.

I am a bit puzzled; the [example](https://github.com/Microsoft/azure-pipelines-yaml/issues/30#issuecomment-435505731) for the conditional templates ~works~ does not cause parser errors, but it never runs. I have the following configuration files:

`azure-pipelines.yml`:
```yml
pool: hosted ubuntu 1604
variables:
   someVar: true
steps:
- script: echo someVar is $(someVar)
  displayName: 'Check someVar Script'

- script: 'echo someVar is $(someVar) in a conditional script'
  condition: ne(variables['someVar'], '')
  displayName: 'Conditional Script (Should run)'

- script: 'echo someVar is $(someVar) in a conditional script'
  condition: eq(variables['someVar'], '')
  displayName: 'Conditional Script (Should NOT run)'

- ${{ if ne(variables['someVar'], '') }}:
   - template: mytemplate.yml

- script: echo hi
  displayName: 'Always Run Script'
```

`mytemplate.yml`:
```yml
steps:
- script: echo from mytemplate.yml
  displayName: 'Template Script'
```

And the build steps from the template are not executed:
![screen shot 2018-12-11 at 11 28 57](https://user-images.githubusercontent.com/1405703/49794762-a69b6d80-fd38-11e8-8fa3-76f8a34e9d05.jpg)

Can someone please help me figure out what's wrong with [my build](https://dev.azure.com/kittaakos/first-test/_build/results?buildId=108)? Thank you!

**Comment by kittaakos** [comment]
There is another problem, perhaps this could go to a separate GH issue.

-----
Let assume, I would like to run different jobs when the build is manually triggered or scheduled (CRON) than when it is a rolling (individual commits/pushes plus the batched ones).

Formally: 
 - run the release build when `Build.Reason` is `Manual` or `Scheduled`.
 -  run a fast build when `Build.Reason` is **NOT** `Manual` **AND NOT** `Scheduled`.


----
> the thing is that i don't get any error, but it doesn't execute either

Since the conditions (`{{  }}`) [do not work for the `template`](
https://github.com/Microsoft/azure-pipelines-yaml/issues/30#issuecomment-435924766), I declared the condition for the `job` instead. (See the _LATER EDIT x2_ [here](
https://github.com/Microsoft/azure-pipelines-yaml/issues/30#issuecomment-436198371).)

I ended up having the following configuration:

`azuere-pipelines.yml`:
```yml
jobs:
- job: rolling_macOS
  displayName: 'Rolling Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  condition: notIn(variables['Build.Reason'], 'Manual', 'Schedule'))
  steps:
    - template: rolling-build-steps.yml

- job: release_macOS
  displayName: 'Release Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  condition: in(variables['Build.Reason'], 'Manual', 'Schedule'))
  steps:
    - template: release-build-steps.yml

- job: release_windows
  displayName: 'Release Build (Windows)'
  pool:
    vmImage: 'vs2017-win2016'
  condition: in(variables['Build.Reason'], 'Manual', 'Schedule'))
  steps:
    - template: release-build-steps.yml
```

`release-build-steps.yml`:
```yml
steps:
- script: echo release build
  displayName: 'Release Build Script'
````

`rolling-build-steps.yml`:
```yml
steps:
- script: echo rolling build
  displayName: 'Rolling Build Script'
```

Error:
```
An error occurred while loading the YAML build pipeline. Unexpected symbol: ')'. Located at position 55 within expression: notIn(variables['Build.Reason'], 'Manual', 'Schedule')). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996
```

-----
A working solution 🎉:

Transform the `notIn(variables['Build.Reason'], 'Manual', 'Schedule'))` and `in(variables['Build.Reason'], 'Manual', 'Schedule'))` expressions into _another_ format. It seems, it cannot parse [`notIn`](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=vsts#notin).

`azure-pipelines.yml`:
```yml
jobs:
- job: rolling_macOS
  displayName: 'Rolling Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  condition: and(ne(variables['Build.Reason'], 'Manual'), ne(variables['Build.Reason'], 'Schedule'))
  steps:
    - template: rolling-build-steps.yml

- job: release_macOS
  displayName: 'Release Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'Schedule'))
  steps:
    - template: release-build-steps.yml

- job: release_windows
  displayName: 'Release Build (Windows)'
  pool:
    vmImage: 'vs2017-win2016'
  condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'Schedule'))
  steps:
    - template: release-build-steps.yml
```

When the build is triggered by a push:
![screen shot 2018-12-11 at 13 37 29](https://user-images.githubusercontent.com/1405703/49801953-e7e94880-fd4b-11e8-954d-2ce9d562e6f4.jpg)

When the build is triggered manually:
![screen shot 2018-12-11 at 13 37 48](https://user-images.githubusercontent.com/1405703/49801936-ddc74a00-fd4b-11e8-94cb-a4faaaa4d5f9.jpg)

**Comment by CoolDadTx** [comment]
@kittaakos the error about the ) is correct. You have a single paren on the left and 2 parens on the right so it is invalid. Try this.

```yaml
steps:
- ${{ if in(variables['Build.Reason'], 'Manual', 'Schedule') }}:
```
And in last post you have the same issue. 

```yaml
condition: notIn(variables['Build.Reason'], 'Manual', 'Schedule')
```

The parens are for the notIn function. You have an extra paren that isn't needed.

For the template expression around your template the syntax looks correct. I have a similar expression and it is working fine. I have noticed that YAML is picky about spacing though. Indentation is important and the docs make it clear that you should avoid tabs. So I would recommend that you remove all the whitespace from the template line and then add enough spaces until the - lines up with the $ above it. I'm not sure it is the cause of the issue here but I've had problems with indentation in my YAML.

**Comment by kittaakos** [comment]
> You have a single paren on the left and 2 parens on the right so it is invalid

This. Sorry for the noise, I was blind.

**Comment by kzu** [comment]
So, according to [this comment](https://github.com/Microsoft/azure-pipelines-yaml/issues/30#issuecomment-435927695) system variables *should* work. It doesn't for me though :(

template:

```
# Installs PowerShell Core
parameters:
  version: '6.2.2'

steps:
- ${{ if eq(variables['Agent.OS'], 'Darwin') }}:
  - template: /provision.yml
    parameters:
      displayName: Provision PowerShell Core v${{ parameters.version }} for Mac
      item: 'https://github.com/PowerShell/PowerShell/releases/download/v${{ parameters.version }}/PowerShell-${{ parameters.version }}-osx-$(Agent.OSArchitecture).pkg"'

- ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
  - template: /provision.yml
    parameters:
      displayName: Provision PowerShell Core v${{ parameters.version }} for Windows
      item: 'https://github.com/PowerShell/PowerShell/releases/download/v${{ parameters.version }}/PowerShell-${{ parameters.version }}-win-$(Agent.OSArchitecture).msi'

- ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=PATH;]$($env:PATH + ';' + $env:ProgramFiles + '\PowerShell\' + '${{ parameters.version }}'.Substring(0, 1))"
    displayName: Add PowerShell Core to PATH
```

pipeline:

```
- stage: Windows
  dependsOn: []
  jobs:
  - job: Windows
    pool: 
      vmImage: windows-2019
    steps:
    - checkout: none
    - template: install-pwsh/v1.yml
    - pwsh: write-host PowerShell $PSEdition $PSVersionTable.PSVersion
```

Results in:

![image](https://user-images.githubusercontent.com/169707/62732405-9ab49800-b9fa-11e9-8c30-30ca9b5e685d.png)

I would have expected the template to run the two steps that apply for `Windows_NT` agent OSes. What am I missing?

NOTE: I *know* I can do run-time condition checking in this case, but to me the benefit of this approach (if it worked) is that the job log would be much more streamlined if all the steps that don't apply at all depending on system/built-in variables don't show up at all in the execution "plan", rather than having a mixture of run and skipped steps.

**Comment by denravonska** [comment]
I'm sorry, but I still can't get this to work.

```
parameters:
  clean: false

steps:
  - ${{ if eq(variables['clean'], 'true') }}:
    - template: clean.yml
```

Gives me in vscode:
> Unexpected property ${{ if eq(parameters['clean'], 'true') }}:
> The first property must be a task

**Comment by vtbassmatt** [comment]
The VS Code extension doesn't understand template syntax. Your YAML looks correct to me.

**Comment by ata18** [comment]
```
parameters:
- name: publishNow
  type: string
    
steps: 
- task: Bash@3
  displayName: 'PublishNow'
  inputs:
    targetType: 'inline'
    script: |
        echo publishNow in templates: ${{ parameters.publishNow }}  

- ${{ if eq(parameters.publishNow, 'true') }}:
  - template: create-resource-group.yml
  - template: prepare-azure-packer-cfg.yml 
  - template: build-image.yml
  - template: delete-resource-group.yml
```

@vtbassmatt Sorry for posting on a closed issue. But this looks very relevant.

In the above yaml, PublishNow task prints the value of `parameters.publishNow' correctly as `true` but the  condition `eq(parameters.publishNow, 'true')` never evaluates to true. What is wrong here?

**Comment by vtbassmatt** [comment]
@ata18 that's unexpected. Could you please file a ticket on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)?

**Comment by hvandenborn** [comment]
i have the same as ATA18

**Comment by satano** [comment]
@ata18, @hvandenborn 

Try removing the apostrophes arount `true`. I have found somewhere, that this can cause troubles in YAML, because one value is treated as boolean, while `'true'` is treated as string and it is evaluated to boolean `false`.

**Comment by sl-NZ** [comment]
Was working through this example based on the value of
 `- ${{ if eq(variables['Agent.JobStatus'], 'Failed') }}:`

- Could not achieve my desired result due to the evauluation of the if statement above seems to be done prior to all steps and not during runtime 

I wanted to send a different slack message based on a failure of a previous step or not as per below examples:

**Happy State**, send happy message when all previous steps are successful
```
  - template: ../SlackMessageTasks/send-slack-message.yml@templates
    parameters:
      slack_message: 'Deploy to `${{ parameters.test_env_num }}` Completed for ClientLogin, Build `$(Build.BuildNumber)`, Branch `$(Build.SourceBranch)` for `$(Build.RequestedFor)` success! :check:'
      SlackChannelConfig: 'test-environments-$(EnvNum)'
      slack_step_tite: 'Success ${{ parameters.test_env_num }}'
```

**UnHappy State**, send message if one of the previous steps have failed 
```
  - ${{ if eq(variables['Agent.JobStatus'], 'Failed') }}:
    - template: ../SlackMessageTasks/send-slack-message.yml@templates
      parameters:
        slack_message: ':x-cross: Deploy to `${{ parameters.test_env_num }}` failed for ClientLogin, Build `$(Build.BuildNumber)`, Branch `$(Build.SourceBranch)` for `$(Build.RequestedFor)`'
        SlackChannelConfig: 'test-environments-$(EnvNum)'
        slack_step_tite: 'Failed ${{ parameters.test_env_num }}'
```

**Comment by denravonska** [comment]
> Was working through this example based on the value of
> `- ${{ if eq(variables['Agent.JobStatus'], 'Failed') }}:`
> 
> * Could not achieve my desired result due to the evauluation of the if statement above seems to be done prior to all steps and not during runtime
> 
> I wanted to send a different slack message based on a failure of a previous step or not as per below examples:

You will need to add two steps to the pipe and provide a "condition":

```
- template: ../SlackMessageTasks/send-slack-message.yml@templates
    parameters:
      slack_message: 'Deploy to `${{ parameters.test_env_num }}` Completed for ClientLogin, Build `$(Build.BuildNumber)`, Branch `$(Build.SourceBranch)` for `$(Build.RequestedFor)` success! :check:'
      SlackChannelConfig: 'test-environments-$(EnvNum)'
      slack_step_tite: 'Success ${{ parameters.test_env_num }}'
      run_if: ne(variables['Agent.JobStatus'], 'Failed')
```
And then inside your template:

```
step: PrintToSlack
   condition: ${{ parameters.run_if }}
```

I know it's not elegant and it will always show one step as skipped, but it's the only thing I could get working.

**Comment by sl-NZ** [comment]
Hey @denravonska, thanks for your suggestion but unfortunately no luck on this
Got below errors when passing the boolean, the pipelines try's to expand the value yaml of AgentStatus as soon as you try to run the pipeline and does not recognise the values

Pipeline run start errors:
```
/Templates/DeployTasks/deploy-clientlogin-test.yml@templates (Line: 82, Col: 15): The 'run_if' parameter value 'eq(variables['Agent.JobStatus'], 'Succeeded')' is not a valid Boolean.

/Templates/DeployTasks/deploy-clientlogin-test.yml@templates (Line: 82, Col: 15): The 'run_if' parameter value 'succeeded()' is not a valid Boolean.
```

This would essentially explain why:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#context

Thanks for your help regardless, I will place the task step for failure directly into my pipeline for now.

**Comment by denravonska** [comment]
@sl-NZ 

Strange, I use that very setup myself:

```
////////////////
// pipeline.yml
- template: build-sdk.yml
   parameters:
   condition: eq(variables['buildSdk'], 'true')

////////////////
// build-sdk.yml
parameters:
   condition: True

- bash: |
    # Build if needed
   condition: and(succeeded(), ${{ parameters.condition }})
```

**Comment by sl-NZ** [comment]
@denravonska A possibility could be that the template I am consuming is in a different repository from the Primary pipeline?

**Comment by denravonska** [comment]
@sl-NZ I don't think it matters. If I understand it correctly the template parameter expansion just pastes whatever is passed to it into where it's used. So the final, expanded results should be

```
condition: succeeded()
```

Did you put quotes around the condition?
```
condition: '${{ parameters.run_if }}'
```

instead of:
```
condition: ${{ parameters.run_if }}
```
? Not sure if it matters though.

**Comment by CoolDadTx** [comment]
@sl-NZ template expressions are evaluated at "compilation" time and not while the pipeline is running. To me they are glorified #if statements. This [diagram](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline) shows the process.

If you want to change the parameters passed to a task based upon parameters at compile time then you can do that with a single step and use template expressions to conditionally include/exclude values. Something like this (not tested).

```yaml
- template: ../SlackMessageTasks/send-slack-message.yml@templates
   parameters:
      slack_message: ':x-cross: Deploy to `${{ parameters.test_env_num }}` failed for ClientLogin, Build `$(Build.BuildNumber)`, Branch `$(Build.SourceBranch)` for `$(Build.RequestedFor)`'
      SlackChannelConfig: 'test-environments-$(EnvNum)'
      - ${{ if ne(variables['Agent.JobStatus'], 'Failed') }}:
        slack_step_tite: 'Success${{ parameters.test_env_num }}'
      - ${{ if eq(variables['Agent.JobStatus'], 'Failed') }}:
        slack_step_tite: 'Failed ${{ parameters.test_env_num }}'
```
In my experience if you have only a single value to swap then it isn't bad. If the task itself changes you need multiple steps. Alternatively I tend to prefer variables when possible (templates make this hard). So instead of using template expressions everywhere I'll define a variable (if possible) or step(s) that set env vars that later steps just use directly. So, in your example, I'd probably use a variable for the messages and then have a single template expression above this to set the values I want to use in the task. Again, this isn't always possible. Templates in particular don't currently allow variables to be declared so I tend to use env variables (ugly but it works). If you only need the values once though then inline template expressions are easier.

**Comment by denravonska** [comment]
@CoolDadTx That won't work as the job status is not available at template compile time. He needs to pass an evaluation expression to the template, as in my example, so the task is able to evaluate and conditionally run or skip itself at runtime.

**Comment by CoolDadTx** [comment]
@denravonska I wasn't focusing on the expression itself. I was addressing the posters comment about when template expressions are evaluated and the need for multiple steps. For the very specific case of checking the status of the agent then condition is fine.

**Comment by denravonska** [comment]
@CoolDadTx No, your example is faulty :) You cannot do a static expression on a dynamic condition.

**Comment by CoolDadTx** [comment]
@denravonska I don't know what you mean by dynamic condition but  template expressions can reference any values that can be determine at the point the template is "compiled". That includes build variables and template parameters. We do this heavily in our highly customized YAML builds and we have no problems whatsoever. Of course getting all this debugged and working was entirely different story but you can use some variables like build variables in template expressions. Variables whose values change during the build won't work correctly however so you have to switch to env variables (or perhaps YAML variables).

Nevertheless your experience may be different than mine and what works for our builds might not work for yours. This is one of the currently annoying features of YAML in that it is very finicky. Even in our own templates we have found that certain expressions or syntax works fine in one template but not in another. Although most of our issues are related to how the PS tasks are generated. Still I've shared my feedback on this issue and I'm not going to argue with you about what does and doesn't work. This is a closed topic anyway. The OP should open a new one if they are having issues with template expressions.

**Comment by patdaman** [comment]
ugh, how about just a 'condition:' line under "- template: xxxxx' ??
Other tasks can do this, why not templates? The are expanded at compile time and show up as a step, then the steps within get skipped.

**Comment by sl-NZ** [comment]
Hi Just a update from my experience which is working smoothly for me now.

- I am using the `run_if` option suggested above. 
- The key for me was to ensure that the value `run_if` is passed as a string into the template parameter type.
- The end goal for me was to pass values into the template conditions based on previous step outputs My Example below

**=========== Pipeline Definition =============**
```
steps:
- powershell: |
       Write-Host("##vso[task.setvariable variable=azureDevopsTestRunFailedResultCount;isOutput=true]0")
   name: RetrieveResults

- template: ./doSomething.yml
  parameters:
    run_if: and(eq(variables['RetrieveResults.azureDevopsTestRunFailedResultCount'], 0), eq(variables['RetrieveResults.azureDevopsTestRunIgnoredResultCount'], 0))
```
**=========== YML Template =============**
```
parameters:
  - name: run_if
    default: true

steps:
- task: PowerShell@2
  condition: |
    and
    (
      ${{ parameters.run_if }},
      succeeded()
    )
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "DoSomething"
```

**Comment by spygi** [comment]
Just want to point out to folks reaching this point, [this comment](https://github.com/microsoft/azure-pipelines-yaml/issues/30#issuecomment-435927695) here was very helpful for me.

@vtbassmatt is your doc available somewhere? User-defined variables are part of the runtime execution right?

**Comment by vtbassmatt** [comment]
@spygi the doc was published a while ago here: https://docs.microsoft.com/azure/devops/pipelines/process/runs. Sorry that wasn't clear!

**Comment by andrzej-jedrzejewski** [comment]
> @denravonska I don't know what you mean by dynamic condition but template expressions can reference any values that can be determine at the point the template is "compiled". That includes build variables and template parameters. We do this heavily in our highly customized YAML builds and we have no problems whatsoever. Of course getting all this debugged and working was entirely different story but you can use some variables like build variables in template expressions. Variables whose values change during the build won't work correctly however so you have to switch to env variables (or perhaps YAML variables).
> 
> Nevertheless your experience may be different than mine and what works for our builds might not work for yours. This is one of the currently annoying features of YAML in that it is very finicky. Even in our own templates we have found that certain expressions or syntax works fine in one template but not in another. Although most of our issues are related to how the PS tasks are generated. Still I've shared my feedback on this issue and I'm not going to argue with you about what does and doesn't work. This is a closed topic anyway. The OP should open a new one if they are having issues with template expressions.

Hi @CoolDadTx,
Can you please provide an example of working condition in template parameters?

I'm trying to use sth like that:
`  - template: /templates/template.yaml
    parameters:
      build: ${{ parameters.param1}}
      repo: ${{ variables.var1 }}
      ${{ if eq(variables['VARIABLE2'], 'True') }}:
        extraparam: 0`

I would like to be able to pass extraparam to template as parameter when VARIABLE2==True.

Thanks,
Andrzej

**Comment by CoolDadTx** [comment]
@andrzej-jedrzejewski You're trying to apply a condition on a parameter to a template. We don't do that so I cannot confirm it'll work. Personally I don't think it makes sense to conditionally include a parameter or not because the template defines the parameters it needs anyway. So making it conditional when calling it doesn't change the template itself. What we do is just set the parameter to a value. If the parameter cannot have a reasonable default value then we include an extra parameter indicating whether to use it or not. For example in our master YAML file we have a template that initializes our build process but must support .NET Framework and Core apps, publishing, etc so we make these parameters to the template. Since we are at the master YAML level we can set the values directly but you could use template expressions if you wanted I suspect.

```yaml
- template: yaml/initialize-build.yml@templates
  parameters:
      packageBuild: true
      publishBuild: true
```

We do have a couple of templates we only want to call if certain conditions are set.

```yaml
- ${{ if eq(parameters.metadataEnabled, 'true') }}:
  - template: add-props-metadata.yml
    parameters:      
       assemblyTypeName: ${{ parameters.metadataTypeName }} 
       isPublic: ${{ parameters.metadataIsPublic }}
```

I suspect your issue is that you're trying to use `var2` as the condition but your template is defining and possibly changing that value. IIRC template condition expressions are evaluated at the point the template is called and so any adjustments to the variable wouldn't be seen in the condition because it is too early in the template process. Of course if the variable is an external variable then it will work just fine as when the template gets "loaded" the variable is already set. Switching to just using the current variable value and optionally including a "use this parameter" indicator to the template would probably resolve the issue as I mentioned earlier.

```yaml
- template: /templates/template.yaml
  parameters:
     extraparam: 0
     useextraparam: ${{ eq(variables.var2, 'true') }}
```
