### ISSUE TITLE
Support variables in template filepaths for reusage of same YAML definition

### ISSUE THREAD

**Issue by nuno-barreiro** [microsoft/azure-pipelines-yaml#302]
I'm trying to reuse the same pipeline definition for running against multiple environments. For each one of those I have a templated variables file in the same folder as the pipeline definition. Currently I'm trying the following:

``` yaml
name: $(Source.BranchName)$(Revision:.r)

trigger: none
pr: none

stages:
  - stage: WorkWithVariables
    displayName: Work with $(environmentCode) Variables
    variables:
      - template: variables.$(environmentCode).yml
    jobs:
      - job: OutputLoadedVariables
        displayName: Check $(environmentCode) Variables
        pool:
          vmImage: ubuntu-latest
        variables:
          - name: JobEspecificVar
            value: JobRunningIn_$(environmentCode)
        steps:
          - script: printenv | sort
            displayName: Output ENV for $(environmentCode)
            env:
              VARIABLE_CONFIG_ENVNAME: ${{ variables.EnvironmentName }}
              VARIABLE_JOB_ESPECIFIC: ${{ variables.JobEspecificVar }}
```

and when running the pipeline I'm passing the variable as such;
![Run pipeline screen](https://user-images.githubusercontent.com/114126/62928692-ed9e9e80-bdb0-11e9-8c9b-5ed71fbc5f38.png)

Unfortunately this doesn't seem to work and I'm always getting the error: 

> /reuse_yaml_with_pipeline_vars/azure_pipelines.yml: File /reuse_yaml_with_pipeline_vars/variables.$(environmentCode).yml not found in repository 

Is de-referencing of variables in the template filename not supported?
