### ISSUE TITLE
Combine demands with strategy matrix

### ISSUE THREAD

**Issue by LokiMidgard** [microsoft/azure-pipelines-yaml#303]
I have a build job, that gets a list of machines where tests should run.
In phase 1 the VMs are reseted and prepared
Phase two is a matrix strategy where each build will get one of the specified machines.

Since the test agents are configured with the correct computer name I wan't to specify those in the demand.

But the variable get not replaced with the correct value. 

```log
##[Error 1]
No agent found in pool tester which satisfies the specified demands:
     Agent.ComputerName -equals $(currentMachine)
     vstest
     Agent.Version -gtVersion 2.144.2 

```

A minimum sample:

```yaml
jobs:
- job: Phase_1
  displayName: Configure Test Agents

  condition: succeeded()
  pool:
    name: Default
    demands: SCVMMAdminConsole

#Ihre Buildpipeline verweist auf die Variable "testMachine", die gemäß Ihrer Einstellung bei Einreihung in die Warteschlange festgelegt wird. Erstellen oder bearbeiten Sie die Buildpipeline für diese YAML-Datei, definieren Sie die Variable auf der Registerkarte "Variablen", und aktivieren Sie dann die Option zur Festlegung bei Einreihung in die Warteschlange. Siehe https://go.microsoft.com/fwlink/?linkid=865971.
  steps:
  - powershell: |  
       # Write your powershell commands here.
       $machines = "$(testMachine)".Split(',')
       Write-Host "Test machine is $machines"
       
       
        $matrix = '{'

       foreach ($machine in $machines) {
       $machine = $machine.Trim()
       Write-host "[$machine]"
           if($matrix.length -ne 1){
            $matrix += ", "
           }
         $matrix += "'$machine':{'currentMachine':'$machine'}"
       }
       $matrix += "}"
       
       Write-Host "##vso[task.setvariable variable=testMachineMatrix;isOutput=true]$matrix"

    displayName: 'PowerShell Script'
    name: machineGeneration

 


- job: Phase_2
  displayName: Test-Phase2

  dependsOn: Phase_1
  condition: succeeded()
  pool:
    name: Default
  strategy:
    matrix: $[ dependencies.Phase_1.outputs['machineGeneration.testMachineMatrix'] ]
  steps:
  - powershell: |  
       # Write your powershell commands here.
       Write-Host "$(currentMachine)"

- job: Phase_3
  displayName: Test-Phase
  strategy:
    matrix: $[ dependencies.Phase_1.outputs['machineGeneration.testMachineMatrix'] ]
  dependsOn: 
    - Phase_1
    - Phase_2
  condition: succeeded()

  pool:
    name: tester
    demands: 'Agent.ComputerName -equals $(currentMachine)'


```

* phase **one** seperates the list of machines.
* phase **two** checks if it will work without demands
* phase **three** trys to define the correct machine name in demands
