### ISSUE TITLE
Can't Authorize YAML Build Task to Use Service Connection

### ISSUE THREAD

**Issue by TingluoHuang** [microsoft/azure-pipelines-yaml#31]
copy from: https://github.com/Microsoft/azure-pipelines-agent/issues/1809

When I try to build my source using the yaml below;

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'xxxredactedxxx'
  projectfolder: 'xxxredactedxxx'

steps:
- script: docker build -f $(projectfolder)/Dockerfile -t $(imageName):$(build.buildId) -t $(imageName):latest .
  displayName: 'docker build'

- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
  displayName: 'Push Image: '
  inputs:
    awsCredentials: 'AWS'
    regionName: 'eu-west-1'
    sourceImageName: '$(imageName)'
    repositoryName: '$(imageName)'
    autoCreateRepository: true
I get the following error;

Job phase1: Step input awsCredentials references service connection AWS which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz

I confirm I have a service connection named AWS.

I tried reading the link in the error message. However, the article doesn't show any directions on how to authorize the build to use the service conneciton.

**Comment by CesarRN** [comment]
Hello @TingluoHuang 

I can't solve my problem
https://github.com/Microsoft/azure-pipelines-agent/issues/1809#issuecomment-434274247

Thanks

**Comment by TingluoHuang** [comment]
@CesarRN can you share your AzurePipeline(VSTS) account name or the pipeline definition url that facing the problem? i can try check our telemetry see what error i can find.

**Comment by ericsciple** [comment]
@vijayma ?

**Comment by chrismade** [comment]
I came across the same issue and posted in [stackoverflow](https://stackoverflow.com/questions/53401927/vsts-anybody-managed-to-use-secure-file-in-azure-pipelines-yml/53488887) - assuming that this is an intended behaviour or a bug that won't fix easily - is there a chance to extend the troubleshooting section here https://aka.ms/yamlauthz - this is the shortcut which appears in the error message - so that people using build pipelines have a chance to fix it - e.g. by adding or changing variables ?

**Comment by DerAlbertCom** [comment]
Is there any way to authorize and serverEndpoint for a FtpUpload@1 in a JobTemplate? I cannot get this to work with all the known workarounds.

**Comment by tsuga** [comment]
Any update?

**Comment by chris31389** [comment]
Any movement on this? 

I've just tried adding this task to my build.yml and i'm getting an error in by PR Build `Unable to queue Build`

```
Job Job: Step input azureSubscription references service connection My Subscription which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.
```

```
- task: AzureResourceGroupDeployment@2
  displayName: 'Validate ARM Template'
  inputs:
    azureSubscription: 'My Subscription'
    resourceGroupName: 'dev'
    location: 'West Europe'
    csmFile: 'src/Arm/azuredeploy.json'
    csmParametersFile: 'src/Arm/azuredeploy.parameters.json'
    deploymentMode: Validation
```
