### ISSUE TITLE
Path Does Not Exist when Publishing Pipeline Artifacts in container from outside build folder

### ISSUE THREAD

**Issue by ruffsl** [microsoft/azure-pipelines-yaml#310]
The docs state that publish should work for absolute paths:

> The path of the file or folder to publish is required. It can be absolute or relative to $(System.DefaultWorkingDirectory).
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#publishing-artifacts

However, for containers, when attempting to publish artifacts located in the container, but not necessarily in agent's build directory, `e.g. /__w/1`, then the path is not found:

``` yaml
parameters:
  key: 'underlay'
  workspace: '/opt/underlay_ws'

steps:
- task: PublishPipelineArtifact@1
  inputs:
    path: ${{ parameters.workspace }}/checksum.txt
    artifact: ${{ parameters.key }}_checksum
```

```
##[section]Starting: PublishPipelineArtifact
==============================================================================
Task         : Publish pipeline artifact
Description  : Publish (upload) a file or directory as a named artifact for the current run
Version      : 1.0.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
==============================================================================
##[error]notFound:PathDoesNotExist
##[section]Finishing: PublishPipelineArtifact
```

**Comment by egeskov** [comment]
I get the same error, but I am not using containers.

After building a netcoreapp and a DacPac my artifact directory (C:\agent\_work\23\a) contains the following two sub-directories:
- Database
- WepAPI

I try to publish two distinct pipeline artifacts by referencing each sub-directory in turn. First the Web API:

```yaml
- task: PublishPipelineArtifact@1
  displayName: Publish Web API Artifact
  inputs:
    targetPath: $(build.artifactstagingdirectory)\WebAPI
    artifact: 'MigrationManager.WebAPI'
```

This fails as follows:
```
Starting: Publish Web API Artifact
==============================================================================
Task         : Publish pipeline artifact
Description  : Publish (upload) a file or directory as a named artifact for the current run
Version      : 1.0.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
==============================================================================
Artifact name input: MigrationManager.WebAPI
##[error]notFound:PathDoesNotExist
Finishing: Publish Web API Artifact
```
In the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables) an example of the value of Build.ArtifactStagingDirectory is given as `c:\agent_work\1\a`. So I have tried different options using slash, backslash, no slash. But no luck.
It works if I use the Build.ArtifactStagingDirectory variable without the sub-directory.
