### ISSUE TITLE
Dinamically populate resources.repository.ref based on variables/parameters

### ISSUE THREAD

**Issue by razidare** [microsoft/azure-pipelines-yaml#311]
Hello, this is not an issue, nor a bug but more of a question of "can this be achieved".

We use the following declaration on our pipelines:

```
resources:
  repositories:
    - repository: self
    - repository: devops
      type: git
      name: devops
      ref: /refs/heads/master
```

So far so good, so this pipeline will always rely on templates I have created in the `devops` repo, `master` branch.

But what we want to achieve is to have a 1:1 relationship between branches in the development repo and branches in the devops repo.

I.E.

Development branches from master to develop
We, devops would branch from master to develop as well
The `pipeline.yml` would sit in the development repo and because it comes from the master branch, it will still pull templates from the master branch of the devops repo instead of the `develop` branch.

What we would want to have is:

```
resources:
  repositories:
    - repository: self
    - repository: devops
      type: git
      name: devops
      ref: $(Build.BranchName)
```

or

```
parameters:
  repoBranch:  $(Build.BranchName)

resources:
  repositories:
    - repository: self
    - repository: devops
      type: git
      name: devops
      ref: ${{ parameters.repoBranch }}
```

Unfortunately, none of this methods worked for me, since variables are only evaluated in build context and parameters are not allowed in that context.

Is there a way to achieve such a behavior?
