### ISSUE TITLE
Each expression for matrix does not work

### ISSUE THREAD

**Issue by toorog** [microsoft/azure-pipelines-yaml#317]
I have the following template

```
parameters:
  environments: []

jobs:
    - job: test
      strategy:
        matrix:
          ${{ each env in parameters.environments }}:
             path: '/foo/bar' 
```
I am consuming the template with
```
- template: mytemplate.yml
    parameters:
      environments: 
        - techname: first
        - techname: second 
```

This fails with the error 
```
mytemplate.yml (Line: 9, Col: 18): Unexpected value '/foo/bar',mytemplate.yml (Line: 9, Col: 13): 'path' is already defined`
```

Any workarounds?
