### ISSUE TITLE
Specify container when using template jobs

### ISSUE THREAD

**Issue by fgervais** [microsoft/azure-pipelines-yaml#320]
To specify the container of a job when using templates, it seem that both of these work.

Specify the container alias as a job parameter:

```
----------------azure-pipeline.yml------------------
resources:
  containers:
  - container: build_container
    image: build-container-image:latest

jobs:
- template: azure-templates/build.yml
  parameters:
    container: build_container
----------------------------------------------------

------------azure-templates/build.yml---------------
parameters:
  container: ''

jobs:
- job: job_name
  pool:
    vmImage: 'ubuntu-16.04'

  container: ${{ parameters.container }}
----------------------------------------------------
```

Just use the container alias directly inside the template:

```
----------------azure-pipeline.yml------------------
resources:
  containers:
  - container: build_container
    image: build-container-image:latest

jobs:
- template: azure-templates/build.yml
----------------------------------------------------

------------azure-templates/build.yml---------------
jobs:
- job: job_name
  pool:
    vmImage: 'ubuntu-16.04'

  container: build_container
----------------------------------------------------
```

Is one way considered better than the other?
