### ISSUE TITLE
Pipeline unable to dynamically load variables 

### ISSUE THREAD

**Issue by mazmrini** [microsoft/azure-pipelines-yaml#322]
Given the following snippet : 
```
parameters:
  environmentVariableGroup: ''

jobs:
  - job: X
    pool:
      vmImage: $(poolVmImage)
    variables:
      - group: ${{ parameters.environmentVariableGroup }}
    steps:
      - template: deploy-x.yml
        parameters:
          azureResourceGroup: $(azureResourceGroup)
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          kubernetesCluster: $(kubernetesClusterName)
```

The result in the pipeline is : 
![image](https://user-images.githubusercontent.com/15892091/64436260-fe7dbf80-d091-11e9-8c68-563e9293e2ff.png)

The pipeline won't even start. When, instead of using the `$(azureSubscriptionEndpoint)` variable, I use a hard coded value, everything runs smooothly. 

Also, when I run the following, the variable is printed out and contains the expected value:
```
parameters:
  environmentVariableGroup: ''

jobs:
  - job: X
    pool:
      vmImage: $(poolVmImage)
    variables:
      - group: ${{ parameters.environmentVariableGroup }}
    steps:
      - bash: echo $(azureSubscriptionEndpoint)
```

I feel like the variable is not evaluated before the service connection check and the pipeline fails because of that. Any ideas ?

EDIT: After reading the [doc on expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops), I have a strong feeling that what I want to achieve can't be done because the variable groups are loaded dynamically.
