### ISSUE TITLE
Allow repository endpoint to be defined by a variable

### ISSUE THREAD

**Issue by HowardvanRooijen** [microsoft/azure-pipelines-yaml#327]
Hi,

We're currently in the process of open sourcing lots of our internal IP and I've been working on creating common reusable build templates:

https://github.com/endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub

I could be missing a trick, but the only thing we can't parameterize is the Repository Endpoint service connection name:

https://github.com/ais-dotnet/Ais.Net/commit/51213e3af95aedebbc1e6d6cd8d5c7728f63db3f

```yaml
resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: ${{ Endjin_Service_Connection_GitHub }}
```

This results in a "A template expression is not allowed in this context" error.

Hardcoding, works as expected!

```yaml
resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: ais-dotnet-github
```

Is this a known limitation, if so is there a workaround?

Thanks!
