### ISSUE TITLE
Using succeeded() in Template Expressions

### ISSUE THREAD

**Issue by JeremyTCD** [Microsoft/azure-pipelines-yaml#33]
## Description
I have a job in a template that depends on a preceding job as well as a template parameter:

```yaml
parameters:
  runTests: true

# omitted for brevity

- job: "Test"
  dependsOn: "Build"
  condition: ${{and(parameters.runTests, succeeded())}}
```
I'm trying to use the `succeeded()` [job status function](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=vsts&tabs=yaml#job-status-functions) within a [template expression](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#template-expressions) to ensure that the job only runs if "Build" succeeded and "runTests" is true. Unfortunately, it seems like this isn't allowed - the job "Test" fails with an error message stating that "succeeded" is invalid. 

I've tried
```yaml
and(${{parameters.runTests}}, succeeded())
```
as well.  

Is there a way to evaluate parameters and job status functions in a single boolean expression?

**Comment by ericsciple** [comment]
No, the `${{ }}` expressions are evaluated when compiling the plan.

It sounds like this is what you want:

```yaml
parameters:
  runTests: true

- ${{ if eq('true', parameters.runTests) }}:
  - job: "Test"
    dependsOn: "Build"
```
