### ISSUE TITLE
PublishBuildArtifacts publishes twice?

### ISSUE THREAD

**Issue by fgervais** [microsoft/azure-pipelines-yaml#334]
This sample pipeline:

```
jobs:
- job: build_arm
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: |
      cp file1 $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(Build.DefinitionName)/arm'


- job: packaging_arm
  dependsOn: build_arm

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: |
      cp file2 $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Publish arm kernel package
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(Build.DefinitionName)/arm/package'
```

Produces these published artifacts.

![Untitled](https://user-images.githubusercontent.com/5411996/65345896-598ed680-dba9-11e9-8822-1793e01d221b.png)

Anyone know why `package` is present 2 times? I'm expecting only the one in the `arm` subfolder but I'm also getting one at the root.
