### ISSUE TITLE
Can't pass variable group names as parameters

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/azure-pipelines-yaml#340]
I have a job template that gets values from distinct variable groups.
I'm able to pass a single group as a single parameter, but not as an array. I need to pass them as an array because these groups may be heterogeneous and their number can differ.

Template:
```
parameters:
  name:
  displayName:
  projects:
  platformVariableGroups: []
  buildPlatforms: []
  buildConfigurations: [ Debug, Release ]
  msbuildArguments: ''
  showVars: false

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}

    variables:
      ${{each group in parameters.platformVariableGroups}}:
       - group: ${{ group }}

    pool:
      vmImage: $(Job.VmImage)

    strategy:
      matrix:
        ${{ each platform in parameters.buildPlatforms }}:
          ${{ each configuration in parameters.buildConfigurations }}:
            ${{ format('{0} {1}', platform, configuration) }}:
              BuildPlatform: ${{platform}}
              BuildConfiguration: ${{configuration}}

    steps:
    ...
```

And the main YAML file:
```
jobs:

  - template: Templates/MSBuild.yml

    parameters:
      # name:
      displayName: Some Test
      project: $(Build.SourcesDirectory)/iOS/Unjammit.iOS.csproj
      platformVariableGroups: [
        'Group1',
        'Group2'
      ]
```

Running this pipeline, I get the following error:
![image](https://user-images.githubusercontent.com/4507319/65572137-f2ac4d00-df1b-11e9-90b7-387ac298ff4e.png)

How can I pass the array of variable groups into the template?
