### ISSUE TITLE
How to target an on-prem azure agent for build/deployment?

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-yaml#352]
I am battling to understand how to build and deploy my app with azure pipelines using on-prem azure agents. I have successfully installed 2 agents `azurebuild` and `azuredeploy` which are working and can execute basic build and tests tasks.

I have assigned the `azurebuild` agent to an Agent Pool and the `azuredeploy` agent to a Deployment Pool and Deployment Group. It seems build agents and pipelines are just for building/compiling and testing my app on a random server from the Agent Pool defined in azure-pipelines.yml and thus useless for deploying since you cannot target a machine.

If I want to deploy to a specific server I cannot therefore use a build pipeline (though certain youtube videos by microsoft suggest otherwise) because it will just run on ANY server in the agent pool and the trigger and pool are hardcoded in the yml and this is the same across all brnaches.

## Questions
* How can I specify a specific agent/machine on which to run my build without hardcoding an agent pool into the yml file? The azure-pipelines.yml file is the same in all branches but I want to build a develop branch on a development server, a test branch on a test server and a master branch on a production server.
* How can I specify a different branch to trigger a release since azure-pipelines.yml is the same in every branch?
* Can pipelines be used to deploy? If so how can I specify the branch and target host to run the deployment on at runtime?

Assuming I cannot use Azure Pipelines to deploy my app how do I do this? If I create a release under Pipelines -> Releases it never asks for a repo nor a branch nor a deployment target (be it machine or pool or deployment group).

## Other issues:
* The documentation does not explain what these agent pools, deployment groups and deployment pools mean and how many you need, when to create one, how they relate to environments etc.
* The documentation nowhere describes multiple pipelines inside a single yml file though the file is called azure-pipelines.yml (plural). Is this possible? If not, how does one create multiple pipelines??

**Comment by guibirow** [comment]
To chose an agent to run a job on, you have to set a demand for the agent name:

```
pool:
      name: Default
      Demands:
      - agent.name -equals $(AGENT_NAME)
```

**Comment by cawoodm** [comment]
Yep, finally figured that one out. However, what if I want to run a build/deploy on multiple hosts? For some reason it only runs on one agent in the pool which sucks for me.

**Comment by guibirow** [comment]
Using Matrix strategy as I've commented in the other issue #353

**Comment by VictorIreri** [comment]
> To chose an agent to run a job on, you have to set a demand for the agent name:
> ```
> pool:
>       name: Default
>       Demands:
>       - agent.name -equals $(AGENT_NAME)
> ```

Sorry to comment on this old issue but is this one half of the solution? How exactly do I set the value that will ultimately end up in `$(AGENT_NAME)`?

**Comment by cawoodm** [comment]
The agent name is set when you install the agent. In the pipeline you can define a variable or better a parameter which you can choose as you run the pipeline.

**Comment by cawoodm** [comment]
Here is an example of a pipeline which let's you run any powershell script on any server you choose:
```yaml
# Ad-hoc execution on any server

trigger:
- none

parameters:
- name: AgentName
  displayName: AGent
  type: string
  values:
  - myserver1
  - myserver2
  - myserver3

jobs:
- job: job1
  displayName: Run any script on any host

  pool:
    name: BUZ-MYB
    demands:
      - agent.name -equals ${{parameters.AgentName}}

  steps:
  - task: PowerShell@2
    displayName: Check a URL
    inputs:
      targetType: inline
      script: |
        Invoke-WebRequest https://curl.haxx.se/
      pwsh: true

```
