### ISSUE TITLE
Run Build Pipeline on all Agents in a Pool?

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-yaml#353]
Is there a way to ensure a build pipeline runs on all agents in an agent pool? If not, how could we use a build pipeline to **deploy** to all agents in a pool? It seems strange to create 20 agent pools for 20 servers.

**Comment by guibirow** [comment]
I don't think there is

The closet you could try is to create a matrix strategy with one value per agent, set parallel to the number of agents.
```
jobs:
- job: Build
  strategy:
    matrix:
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
      Python37:
        PYTHON_VERSION: '3.7'
    maxParallel: 3
```
This does ensure it will run on all of them tough.

Probably you can use the matrix value to define a demand for the pool and each node have one capability with it's name:
```
pool:
      name: Default
      Demands:
      - jobs: $(PYTHON_VERSION)
```

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#strategies

**Comment by cawoodm** [comment]
Who da man, you da man @guibirow - Muchas gracias!

```
trigger:
- develop

jobs:
- job: deploy_apache_dev
  displayName: Deploy Apache on all DEV Servers
  strategy:
    matrix:
      SomeDev1:
        AGENT_NAME: 'foodev1'
      SybitDev2:
        AGENT_NAME: 'foodev2'
      SybitDev6:
        AGENT_NAME: 'foodev6'
      BUZDev:
        AGENT_NAME: 'busta-rhymes'
  pool:
    name: FOO-BAR
    demands:
      - agent.name -equals $(AGENT_NAME)
  steps:
  - powershell: .\deploy.ps1
    displayName: Deployment (deploy.ps1)
  - powershell: .\tests\ApacheTests.ps1 -Verbose
    displayName: Tests (ApacheTests.ps1)
```

PS: This works with `job` but not with `deployment` for some reason.
