### ISSUE TITLE
Problem using 'each'

### ISSUE THREAD

**Issue by synesthesia** [microsoft/azure-pipelines-yaml#356]
I'm not sure if this is a bug, an undocumented feature or just me not understanding YAML well enough...

The problem I am trying to solve is installing to a development environment a set of dependencies each of which is generated as an artifact by another project.

For each dependency there are two steps - an artifact download and a deployment to the environment.  I'm trying to decompose the logic down into a set of templates.

At the lowest level I have `tasks-template.yml` :

```
parameters:
  project: '' 
  pipeline: '' 
  artifactName: '' 
  connectionString: ''  

tasks:
- task: MyToolsInstaller@0

- task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'specific'
          project: ${{ parameters.project}}
          pipeline: ${{ parameters.pipeline }}
          buildVersionToDownload: 'latestFromBranch'
          branchName: 'refs/heads/master'
          downloadType: 'single'
          downloadPath: '$(Pipeline.Workspace)/deps'
          artifactName: ${{ parameters.artifactName }}
        displayName: Download ${{ parameters.artifactName }}@master 

- task: MyInstallerTask@0
        inputs:
          connectionString: ${{parameters.connectionString}}
         # etc...
```

I want to call this from `jobs-template.yml`:

```
parameters:
  connectionString: ''
  dependencies: []

jobs:
- ${{ each dependency in parameters.dependencies}} 
  - job:  # this is the line that is flagged as in error (see later)
    variables:
    - name: connectionString
      value: ${{ parameters.connectionString }}
      
    steps:
    - template: tasks-template.yml
      parameters:
        project:                ${{ dependency.project }}
        pipeline:               ${{ dependency.pipeline }}
        artifactName:           ${{ dependency.artifactName }}
        connectionString: $(connectionString)
```

and then call that from `pipeline.yml`:

```
trigger: none

pool:
  name: Hosted VS2017
variables:
- group: AGroup

resources:
  repositories:
    - repository: templates
      type: git
      name: PROJECT/REPO

stages:
- stage: InstallDepsInDev
  variables:
   connectionString: 'A CONNECTION STRING BUILT FROM VARS'
 
  jobs:
  - template: jobs-template.yml@templates
    parameters:
      connectionString: $(connectionString)
      dependencies:
        - project: 'A GUID'
          pipeline: 'AN INT'
          artifactName: 'ARTIFACT1'

        - project: 'ANOTHER GUID'
          pipeline: 'ANOTHER INT'
          artifactName: 'ARTIFACT2'

```

When I try to run this pipeline I get an error message pointing to the indicated line in `jobs-template.yml` :

**Mapping values are not allowed in this context.**

I'm trying to avoid exposing the detail of the download and install steps to the top level template - not least because later I would like to refactor the dependencies out into a data file that can be shared across other pipelines in the same project.

Any clues much appreciated!

**Comment by synesthesia** [comment]
Edited to fix obvious typo but the code still throws same error about mapping values not allowed

**Comment by matteotumiati** [comment]
I haven't tested it yet to be honest, but I would do the following changes:
- Assign a name to the job in `jobs-template.yml`: it's not required AFAIK, but it's a best practice;
- Remove the "double" assignment of the connection string: I'm not quite sure on this, but probably expansion of the variable happens at a different time. 

I would replace that file with:

```yaml
parameters:
  connectionString: ''
  dependencies: []

jobs:
- ${{ each dependency in parameters.dependencies}} 
  - job:  ${{ dependency.artifactName }}     # TODO: ensure generated names are unique values or use a different name
    steps:
    - template: tasks-template.yml
      parameters:
        project: ${{ dependency.project }}
        pipeline: ${{ dependency.pipeline }}
        artifactName: ${{ dependency.artifactName }}
        connectionString: ${{ parameters.connectionString }}
```
