### ISSUE TITLE
Independent stages should start in the order declared

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-yaml#360]
My build has a unit-test stage and three other stages that depend on it. Of the latter three, the one declared first is the one whose job usually takes the longest. However, it never starts until the other two stages' jobs are all started, which increases the total time from push to snapshot release without saving any VM-minutes. Shouldn't I have been able to fix this by declaring it first? (If Azure Pipelines is attempting automatic longest-job-first scheduling, then it is using out-of-date data.)

**Comment by matteotumiati** [comment]
I'm not sure how the service picks up each job, so I cannot really answer your question, but one thing I'd do is to specify the order manually using the `dependsOn` keyword:

```yaml
stages:
- stage: StageA
  jobs:
  - job: jobA
    steps:
    - script: echo "Stage A"

- stage: StageB
  dependsOn: StageA
  jobs:
  - job: jobB
    steps:
    - script: echo "Stage B"

- stage: StageC
  dependsOn: StageA
  jobs:
  - job: jobC
    steps:
    - script: echo "Stage C"

- stage: StageD
  dependsOn: StageA
  jobs:
  - job: jobD
    steps:
    - script: echo "Stage D"
```

If I understood correctly, the `StageA` here represents your unit tests stage while `StageB/C/D` represents the other three. In this case I said explicitly to the service that I want to execute those three after `StageA` is completed (successfully). All three will run in parallel:

![image](https://user-images.githubusercontent.com/3147566/71666778-b67e5900-2d62-11ea-9782-97f09244886b.png)

Keep in mind that all of this is still dependent on how many agents you can run in parallel, so if you want to be sure that `StageB,` assuming it's the one that takes the longest to complete, runs first, you can eventually specify that `StageC` and `StageD` depends on `StageB` while `StageB` depends on `StageA.`
