### ISSUE TITLE
Add the possibility to include/exclude pipelines names for schedules

### ISSUE THREAD

**Issue by agneszitte-nventive** [microsoft/azure-pipelines-yaml#361]
At the moment, if I'm adding a scheduled trigger in my yaml file, I don't have the possibility to include/exclude pipelines names.
For example, I'm adding this schedule and use the same yaml for multiple pipelines but I want to exclude one specific pipeline to use this schedule.

```
schedules:
- cron: "30 09 * * Mon-Fri"
  displayName: 'Nightly weekdays build - 4:30 EST'
  always: false
  branches:
    include:
    - master
```

Related issue for the documentation: https://github.com/MicrosoftDocs/vsts-docs/issues/6055
