### ISSUE TITLE
job <> deployment

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-yaml#364]
The docs (and feedback from you guys) indicates that `job` and `deployment` are structurally equivalent i.e. they are to a large degree interchangable. However the following YAML is not accepted by Azure DevOps:

```
jobs:
- deployment: deploy_apache_dev
  displayName: Deploy Apache on all DEV Servers
  strategy:
    matrix:
      SybitDev1:
        AGENT_NAME: 'buhlerdev1'
      BUZDev:
        AGENT_NAME: 'ecom-app02-dev'
  pool:
    name: BUZ-MYB
    demands:
      - agent.name -equals $(AGENT_NAME)
  steps:
  - powershell: .\deploy.ps1
    displayName: Deployment (deploy.ps1)
  - powershell: .\tests\ApacheTests.ps1 -Verbose
    displayName: Tests (ApacheTests.ps1)
```

![image](https://user-images.githubusercontent.com/498834/67202133-35bceb80-f408-11e9-8395-83fe4c9716a4.png)

>  /deploy-dev.yml (Line: 12, Col: 5): Unexpected value 'matrix',/deploy-dev.yml (Line: 21, Col: 3): Unexpected value 'steps'

Change `deployment` to `job` and it runs without a hitch.

So... either make them interchangable or add examples of how to use `deployment` with `strategy` and `steps` properly.

Thx

**Comment by guibirow** [comment]
AFAIK, Currently, the only possible strategy for deployments is runOnce.

If you change like this should work:

```
jobs:
- deployment: dev
  environment: dev
  pool:
      vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:

        - download: current
          displayName: 'Download: Artefacts'
          artifact: artefact_name
```
