### ISSUE TITLE
Specify zip file location for ExtractFiles@1

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-yaml#365]
Hi,

I want to extract a zip file which is under a folder structure like so under Build.SourceDirectory

folder1\folder2\folder3\abcd.zip

I am using this format which works fine. Is there a way to be more specific about abcd.zip in the archiveFilePatterns instead of a wildcard *.zip

```
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '*.zip'
        destinationFolder: '$(PublishLocation)'
        cleanDestinationFolder: false
      displayName: 'extracting files from published app "PublishApp"'
      condition: succeeded()
```

Thanks

**Comment by matteotumiati** [comment]
Yes, you can specify the full path of the zip file:

```yaml
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'folder1/folder2/folder3/abcd.zip'
    destinationFolder: '$(PublishLocation)'
    cleanDestinationFolder: false
```
