### ISSUE TITLE
Excluding paths from trigger not working as expected

### ISSUE THREAD

**Issue by simonvane** [microsoft/azure-pipelines-yaml#366]
I have the following trigger in my yml build file.
```
trigger:
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - readme.md
    - Deploy/*
```
The way I would expect that to work is that I get a build if the branch is master or develop unless the only files changed are readme.me or are file in the Deploy folder.

Is my expectation correct?

I made a commit to develop where the only changes were in Deploy but this resulted in a build.

I am wondering if I'm misinterpreting the documentation.

Thanks.

**Comment by yesoreyeram** [comment]
Have u tried removing the * ? (In your exclude paths, Just specify Deploy/)

**Comment by simonvane** [comment]
I need to do a bit more digging but I think this is actually working fine and I just need a similar section for PRs i.e.
'''
pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - readme.md
    - Deploy/*
'''

I don't think the `/*` is required in `Deploy/*` as you suggest but I think it makes the intent clearer.

**Comment by AElharouny** [comment]
I have the same issue exactly and I don't want to have the same setting in PR trigger as I want PR triggers to work from `- Deploy/*`. 
Any information about what's happening?

**Comment by simonvane** [comment]
So I think there are a few issues of usability here but it looks like things are working as intended.

The usability issues are:

- Having to duplicate the inclusions / exclusions in `trigger` and `pr`.
- `pr` doesn't work Azure DevOps git repos (see https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pr-trigger), we have to specify it in branch policy instead which leads to confusion and duplication.
- There is no error or warning to tell you that `pr` doesn't work in Azure DevOps.

**Comment by AElharouny** [comment]
I found out that in my case what was causing the pipeline to run when I expected otherwise is having `- path/to/excluded/*` instead of `- path/to/excluded` in exclude list in `trigger` I didn't have to change `pr`

**Comment by AElharouny** [comment]
And yes trying to diagnose the problem was really hard.

**Comment by simonvane** [comment]
@AElharouny Are you using Azure DevOps repos?

**Comment by AElharouny** [comment]
No we're using Github.

**Comment by Raffaello** [comment]
i have the same issue with the following configuration more or less:

```
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    #- .gitignore
    - .github/
    - README.md
    - appveyor.yml
    - LICENSE
    - codecov.yml

  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    #- .gitignore
    - .github/config.yml
    - README.md
    - ./appveyor.yml
    - LICENSE
```

the pipeline is in a `azure-pipelines` folder, i have also tried, using a `../` relative path, as i (wrongly?) guessed the root path might be the `azure-pipelines` folder. 
From the documentation there are few bits that are not really clear. 

basically what i would like to achieve is really simple as: if i change a readme, i do not want to trigger the CI ...... but it is always triggered.. 
not sure i think i might have missed something, but at the same time i think should be fairly more straight-forward, or it is slightly buggy and the `paths.exclude` is being overridden somehow?

---

from my extra little investigation, the triggers and commit checkout are not just working on the single commit, at least for PR, but is like accumulative for all the commits, that imply if there is:
- 1st commit that should trigger the PR
- 2nd commit that should not, azure pipelines 

the result is:
the triggers detect the change as a whole, so triggering the pipeline like if it was 1 "merged" commit of 1st and 2nd and then the resulting file changes are valid for the PR. 

i guess. 
For me is not really the expected behavior and should be more on fine grained PR commit

reported also here: 
https://developercommunity.visualstudio.com/content/problem/1046653/azure-pipelines-triggers-pathsexclude-in-pr-is-not.html

---

just need a clarification

**Comment by sdg002** [comment]
Hi all,
Very late in the day - but sharing what worked for me.


# Project structure


```
--c:\work\
    |
    ---aks
    |    |
    |    |
         | ---project1
         |         |
         |         |---cicd.yaml
         |         
         |         
         | ---project2
         |         

```

## trigger and pr elements from my project1/cicd.YAML

```yaml
trigger: 
  branches:
    include:
    - master
    - main
  paths:
    include:
    - 'aks/project1/*'
    exclude:
    - aks/readme.md


pr:
  paths:
    include: 
    - 'aks/project1/*'
    exclude:
    - aks/readme.md

```

## Caveat about PR path exclusion 

The PR path trigger examines all the files in union of all commits. If commit2 has a file in the exclusion list but there was a commit1 which had a file that was in the inclusion list, the PR will get trigerred.
This was not obvious to me first.  But, I found this post which sort of made sense:
https://developercommunity.visualstudio.com/t/azure-pipelines-triggers-pathsexclude-in-pr-is-not/1046653
