### ISSUE TITLE
eq and ne Not working

### ISSUE THREAD

**Issue by duttasantanu** [microsoft/azure-pipelines-yaml#367]
I have created a pipeline build variable "svctag" and assigned its value to blank (empty string). Now trying to execute below script inside a job in yaml file. Every time it prints "svctag is not blank". Not sure what I am doing wrong. 
 Please help.
```
- ${{ if eq('$(svctag)', '') }}:
   - script: echo 'svctag is blank'
- ${{ if ne('$(svctag)', '') }}:
   - script: echo 'svctag is not blank'
```

**Comment by guibirow** [comment]
Try with `variables['svctag']` or `variables.svctag` instead of `'$(svctag)'`

**Comment by matteotumiati** [comment]
If the pipeline is defined as the following, then it will show '_svctag is blank_' as @guibirow said.

```yaml
trigger: none

variables:
  svctag: ''

steps:

- ${{ if eq(variables.svctag, '') }}:
   - script: echo 'svctag is blank'
   
- ${{ if ne(variables.svctag, '') }}:
   - script: echo 'svctag is not blank'
```
