### ISSUE TITLE
Multi-stage YAML template "agent demand" not honored

### ISSUE THREAD

**Issue by andyofengland** [microsoft/azure-pipelines-yaml#370]
I have a series of build agents in my self-hosted pool.  Some of them have additional capabilities (Docker, Java, Visual Studio etc.)

I have a build stage that has certain agent demands and a release phase that may have different demands.

The behaviour that I am seeing is the release phase is only using the pool name and ignoring the demands that are passed in; as such, the deployment phase fails.

The YAML is:

```
stages:
    -   stage: Build
        displayName: Build and Test
        jobs:
            -   job: Build
                displayName: 'Execute the build and run the tests'
                pool:
                    name: Default
                    demands:
                        - docker
                        - msbuild
                        - visualstudio
                        - java
                        - Cmd
                steps:
                    -   template: 'azure-build.yaml'
                        parameters:
                            targetSubscription: '$(testSubscription)'

    -   stage: ReleaseToDev
        displayName: Release to Development
        dependsOn: Build
        jobs:
            -   deployment: deployToDevelopment
                displayName: Perform the Deployment
                environment: development
                continueOnError: false
                variables:
                    -   group: Dev Variables
                pool:
                    name: Default
                    demands:
                        - docker
                        - msbuild
                        - visualstudio
                        - java
                        - Cmd
                strategy:
                    runOnce:
                        deploy:
                            steps:
                                -   template: 'azure-deploy-template.yaml'
                                    parameters:
                                        targetSubscription: '$(developmentSubscription)'
```

In the above example, the demands are the same (but not in all cases) however, the behaviour I am seeing is that the ``docker`` demand is ommitted and the deploy fails.

The template YAML item has nothing other than the steps and parameters. No agent specifications.

Any ideas at all?  I'm sure I'm missing something in the template/master yaml
