### ISSUE TITLE
Multi-Stage Pipeline YML Unexpected value 'stages'

### ISSUE THREAD

**Issue by FelipeMiranda** [microsoft/azure-pipelines-yaml#377]
I Have this yml:

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - release/v*
    - develop
    exclude:
    - master
    - hotfix
    - feature/*
  paths:
    include:
    - /*

workspace:
  clean: outputs

stages:
- stage: develop
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
  - job: BuildApplication
  displayName: Build Application
  pool:
    name: 'infraestrutura'
  steps:
  - task: Npm@1
    displayName: 'Cache Verify'
    inputs:
      command: custom
      verbose: false
      customCommand: 'cache verify'
  - task: Npm@1
    displayName: 'rebuild node-sass'
    inputs:
      command: custom
      verbose: false
      customCommand: 'rebuild node-sass'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'run build'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: dist/
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: avalia-mais-web'
    inputs:
      ArtifactName: 'avalia-mais-web'
- stage: stage
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/release/*'))
  jobs:
  - job: BuildApplication
  displayName: Build Application
  pool:
    name: 'infraestrutura'
  steps:
  - task: Npm@1
    displayName: 'Cache Verify'
    inputs:
      command: custom
      verbose: false
      customCommand: 'cache verify'
  - task: Npm@1
    displayName: 'rebuild node-sass'
    inputs:
      command: custom
      verbose: false
      customCommand: 'rebuild node-sass'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'build-staging'
    inputs:
      command: custom
      verbose: false
      customCommand: 'build-staging'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: dist/
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: avalia-mais-web'
    inputs:
      ArtifactName: 'avalia-mais-web'
- stage: production
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/release/*'))
  jobs:
  - job: BuildApplication
  displayName: Build Application
  pool:
    name: 'infraestrutura'
  steps:
  - task: Npm@1
    displayName: 'Cache Verify'
    inputs:
      command: custom
      verbose: false
      customCommand: 'cache verify'
  - task: Npm@1
    displayName: 'rebuild node-sass'
    inputs:
      command: custom
      verbose: false
      customCommand: 'rebuild node-sass'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'run build-prod'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build-prod'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: dist/
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: avalia-mais-web'
    inputs:
      ArtifactName: 'avalia-mais-web'


```
When I run this it gives me this error:

/azure-pipelines.yaml (Line: 22, Col: 1): Unexpected value 'stages'

**Comment by olehs0** [comment]
Any news about this ?

**Comment by julie-ng** [comment]
Have you checked if you have the multi-stage pipeline feature turned on? It's a preview feature and not on by default.

For details, see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml

**Comment by matteotumiati** [comment]
There is no way to set the `workspace` at pipeline level looking at the schema reference:

```yaml
name: string  # build numbering format
resources:
  pipelines: [ pipelineResource ]
  containers: [ containerResource ]
  repositories: [ repositoryResource ]
variables: { string: string } | [ variable | templateReference ]
trigger: trigger
pr: pr
stages: [ stage | templateReference ]
```

Anyway you should be able to set it at job level:

```yaml
- stage: develop
  jobs:
  - job: BuildApplication
    displayName: Build Application
    workspace:
      clean: all
    steps:
    - task...
```

As described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace).

Otherwise, it should be supported, but it is not documented anywhere, also at `pool` level inside the YAML file (but you won't get autocomplete as well):

```yaml
- stage: develop
  jobs:
  - job: BuildApplication
    displayName: Build Application
     pool:
      name: 'infraestrutura'
      workspace:
       clean: all
      steps:
      - task...
```
