### ISSUE TITLE
Set environment variables through bash

### ISSUE THREAD

**Issue by ElvenSpellmaker** [microsoft/azure-pipelines-yaml#382]
Hey there,

I have a currenty problem whereby everytime I set a varable using the correct syntax it's prefixing all variables with `BASH<number>` instead of plainly setting the variable like the docs say it does.

Example:
```yml
parameters:
  unique_values:
  - key: 'FOO'
    value: 'servicename1'
  - key: 'BAR'
    value: 'bronze'

steps:
- ${{ each var in parameters.unique_values }}:
  - bash: |
      echo "##vso[task.setvariable variable=BAZ_${{ var.key }};isOutput=true]${{ var.value }}"

- bash: |
    env | grep BAZ_
```

Outputs:
```
BASH2_BAZ_BAR=bronze
BASH1_BAZ_FOO=servicename1
```

The document doesn't nention anything about prefixes being added, why is this happening?

Document: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script

Looking into the builds it doesn't have the prefix when it comes to run it:
```
##[debug]script=echo "##vso[task.setvariable variable=BAZ_FOO;isOutput=true]servicename1"
```
