### ISSUE TITLE
Powershell Task in Linux Agent(ubuntu-16.04) fails for nuget install package with the reason `xdg-open: unexpected argument 'install'`

### ISSUE THREAD

**Issue by NivedhaChellam** [microsoft/azure-pipelines-yaml#384]
I'm using the Powershell script to install the nuget. After that will use, nuget.exe to install the package. However the task fails with the reason `xdg-open: unexpected argument 'install'`
The RCA is some how the invoke expression is treated as 
 `xdg-open nuget.exe install PackageName -source https://api.nuget.org/v3/index.json -version 0.35.0 ` which is incorrect.  That is the reason for the error. 

Code snippet from .ps1 (Tried with Invoke-Expression and & as well)
**First Package**
```
Invoke-Expression "$nuGetExePath install $credentialProviderPackage -source $packageSourceUrl -version $credentialProviderVersion" 
```
**Second Package**
```
& $nuGetExePath install $commonToolsPkg -source $vigilanceCommonScriptsSource -version $commonToolsVersion
```

**Yaml Task**
```
- task: PowerShell@2
  displayName: 'Initialize Scripts'
  inputs:
    filePath: '$(Build.SourcesDirectory)/init.ps1'
    pwsh: true
```
In Dev box, when I tested with Ubuntu 18.04  and WSL2.0 the same scripts runs with no issues.

Appreciate any pointers/hints for this.
