### ISSUE TITLE
Allow determining whether to batch CI triggers based on the branch

### ISSUE THREAD

**Issue by rygo-msft** [microsoft/azure-pipelines-yaml#395]
Currently the `batch` setting is global to the whole trigger definition. I would like to batch changes on the develop branch while triggering a build on ever commit to master.

I tried using a parse time expression, but I received a warning in VSCode. Presumably trigger evaluation happens too early to support such expressions?

Perhaps allowing defining multiple trigger objects would work? Something like 
```
triggers:
- trigger:
  batch: true
  branches:
    include:
    - develop
- trigger:
  batch: false
  branches:
    include:
    - master
```
