### ISSUE TITLE
checkout step does not checkout LFS files in submodules

### ISSUE THREAD

**Issue by hillin** [microsoft/azure-pipelines-yaml#397]
```yaml
  - checkout: self
    lfs: true
    submodules: true
```

This does not checkout LFS files in submodules. 

A possible workaround is install LFS (globally) before checking out:

```yaml
  - script: git lfs install
```
