### ISSUE TITLE
Resource pipeline default trigger(s) does not work

### ISSUE THREAD

**Issue by meastp** [microsoft/azure-pipelines-yaml#404]
From pipeline resource trigger in `azure-pipelines-yaml/design/pipeline-triggers.md`:

```yaml
resources:       
  pipelines:
  - pipeline: string 
    source: string  
    trigger:     # Optional; Triggers are enabled by default.
      branches:  # branch conditions to filter the events, optional; Defaults to all branches.
        include: [ string ]  # branches to consider the trigger events, optional; Defaults to all branches.
        exclude: [ string ]  # branches to discard the trigger events, optional; Defaults to none.
      stages: [ string ]  # trigger after completion of given stage, optional; Defaults to all stage completion. stages are OR'd
      tags: [ string ]  # tags on which the trigger events are considered, optional; Defaults to any tag or no tag. tags are OR'd
```

I am experimenting with this, and, as I want to trigger a build from every build of *mypipeline*, my yaml looks like this (later steps removed as they are not relevant):

```yaml
trigger: none # this job must not be triggered by pushes to git, but by mypipeline builds
resources:
  pipelines:
  - pipeline: mypipeline
    source: mypipeline
jobs: 
- job: build
  pool: 
    name: mypool
  steps:
    - download: mypipeline # pipeline resource identifier.
      artifact: drop  # artifact to download, optional; defaults to all the artifacts from the resource.
```

However, the pipeline above is **never** triggered when mypipeline builds finish.

If I add

```yaml
    trigger:     # Optional; Triggers are enabled by default.
      branches:  # branch conditions to filter the events, optional; Defaults to all branches.
        - master
        - release/*
```
to my pipeline above, the pipeline is triggered when mypipeline is finished building (the specified branches only). However, I'd like builds on all branches to trigger a build, which is supposed to be the default behaviour (Pull Request builds, for example), but this does not work.

Is this a documentation error? Is this the right place to file this bug? If not, could you point me in the right direction? :)

**Comment by martijnvink** [comment]
Hi, I'm running into the same issue when trying to trigger my deployment pipeline after all builds (including pull request builds). I tried using the asterisk as branch filter and removing the trigger part completely, but I can not get the trigger to fire at all:

```
trigger: none
resources:
  pipelines:
  - pipeline: MyDeploy
    source: MyBuild
    trigger:
      branches:
        include:
        - '*'
```

Did you by any chance make progress in finding a solution to this issue?

**Comment by meastp** [comment]
@martijnvink Unfortunately, I haven't found a workaround. I'm waiting for this bug to be triaged/accepted/fixed in Azure DevOps :)

**Comment by jwmiller5** [comment]
I'm having similar issues with pipeline triggers. This was working as recently as yesterday. I haven't been making changes to the pipeline, and I reverted any recent changes, but still nothing when the prereq pipeline completes.

```
resources:
  pipelines:
    - pipeline: KeyVaultPreReq
      source: Example_1_KeyVault
      trigger: true

variables:
- template: ../../../../all.pipeline.variables.${{ variables['Build.SourceBranchName'] }}.yaml

trigger:
  branches:
    include:
      - '*'
    exclude:
      - master
  paths:
    include:
      - Modules/LogAnalytics/2.0
```
