### ISSUE TITLE
Yaml list not working as main pipeline variable

### ISSUE THREAD

**Issue by EtienneDeneuve** [microsoft/azure-pipelines-yaml#406]
Hi Azure DevOps !

I'm working on a multistage pipeline with some template.

I wanted to create a list in variables like :

```
variables:
   deploy_services:
    - 'service'
    - 'serverfunction'
```

and use it in as template parameters:

```
stages:
  - stage: Build
    jobs:
    - template: jobs/template-build.yml
      parameters:
        pool: "Azure Pipelines"
        DEPLOY_SERVICES: $(deploy_services)
  - stage: Deploy
    jobs:
    - template: jobs/template-deploy.yaml
      parameters:
        deploy_services: $(deploy_services)
```

I tried with some [] and other format but Azure devops don't like it.

Is there a way to manage that ?

**Comment by matteotumiati** [comment]
Unfortunately looking at how the pipeline is built, it doesn't seem to be possible. 

```yaml
name: string  # build numbering format
resources:
  pipelines: [ pipelineResource ]
  containers: [ containerResource ]
  repositories: [ repositoryResource ]
variables: { string: string } | [ variable | templateReference ]
trigger: trigger
pr: pr
stages: [ stage | templateReference ]
```

As you can see, variables can only be of type `string` or reference a template or a variable group. 
Even if you reference a template, it won't work because you will use again the keyword `variables` that won't work like `parameters`.
