### ISSUE TITLE
Deployment job do not execute preDeploy

### ISSUE THREAD

**Issue by EtienneDeneuve** [microsoft/azure-pipelines-yaml#407]
Hi,

I tried to  use the following :

```
jobs:
  # - ${{ each app in parameters.deploy_services }}:
  - deployment: frameworkfull #${{ app }}
    displayName: frameworkfull #${{ app }}
    pool: 
      vmImage: 'Ubuntu-16.04'
    environment: 'demo.demo'
    strategy:
      runOnce:
        preDeploy:
          steps:
            - bash: "curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"
              displayName: "Install Azure CLI"
            - bash: |
                echo $(BUILD.SOURCEBRANCHNAME)-$(BUILD.SOURCEVERSION)
                DOCKER_IMAGE_TAG=$(BUILD.SOURCEBRANCHNAME)-$(BUILD.SOURCEVERSION)
                echo "##vso[task.setvariable variable=DOCKER_IMAGE_TAG]${DOCKER_IMAGE_TAG}"
```

But Azure DevOps don't execute anything

Do I missed something ?

**Comment by matteotumiati** [comment]
Hi!

I made some (small) changes to your YAML, just for the sake of testing different scenarios. Here's my pipeline:

```yaml
jobs:
- deployment: frameworkfull
  displayName: frameworkfull
  pool: 
    vmImage: 'Ubuntu-16.04'
  environment: 'demo'
  strategy:
    runOnce:
      preDeploy:
        steps:
        - bash: echo "Hello from preDeploy section"
          displayName: "PreDeploy"
        
      deploy:          
        steps:
        - bash: echo "Hello from deploy section"
          displayName: "Deploy"
```

As you can see I changed the environment name to be only "_demo_" (I don't have the resource "_demo_") and also changed bash scripts to only print a kind of hello world instead of your scripts (but it shouldn't matter, I think). 

In this scenario the `preDeploy` lifecycle hook is triggered correctly and executed:

![image](https://user-images.githubusercontent.com/3147566/71643903-f6d8cb00-2cbf-11ea-9bf1-26df8b9356eb.png)

For test #2, I tried removing the `deploy` hook and I get the "_Deployment strategy should contain life cycle hook of type 'Deploy'_" error. I expected that though, as it is required.  

In third and last try, I created a resource called "_demo_" in a Kubernetes cluster (in the environment called "_demo_") so the pipeline now looks more similar to yours:

```yaml
# ...
environment: 'demo.demo'
strategy:
  runOnce:
    preDeploy:
      steps:
      - bash: echo "Hello from preDeploy section"
        displayName: "PreDeploy"
        
    deploy:          
      steps:
      - bash: echo "Hello from deploy section"
        displayName: "Deploy"
```

The pipeline executes both `preDeploy` and `deploy` steps correctly as expected.

Are you still experiencing the issue?
