### ISSUE TITLE
Azure Pipelines and Releases and Branches

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-yaml#411]
Hi,

I am having difficulty in setting up my project for dev and release work. I have gone through various articles but I am unable to come to a definitive conclusion about how to setup up my dev and release pipelines for different branches. I need help in this area.

As an example, say I have a Dev branch with a pipeline DevPipeline in /azure-pipelines.yml. 
This pipeline has CI triggers like so:

trigger:
- Dev
- features/*

Now, when I create a branch Release/R1.0 what exactly do I need to do? Do I create a new pipeline say Release-R1.0. Where should the .yml for this pipeline be? Should it overwrite /azure-pipelines.yml or should I create /Release-R1.0.yml? I am also having confusion in setting up the triggers for this Release-R1.0 pipeline.

Any help is really appreciated.

Thanks

**Comment by matteotumiati** [comment]
Hi!

It really depends on what you really need to achieve. 

If the `Release/R1.0` branch is created from the `Dev` branch where the pipeline has been created, then you can trigger the pipeline manually choosing the release branch. The pipeline will run against that branch. 

I think it's important for you to understand that:
1. The YAML pipeline moves between branches like any other file in the repository: if you create the pipeline in branch `A` and try to run it against branch `B`, it won't work because the file describing the pipeline won't exists there, unless branch `B` is created from branch `A` (after the pipeline has been created);
1. You don't need to create multiple pipelines if the only thing that changes are branches: in this scenario, you can trigger the pipeline manually and you will have the same behavior that you have in the `Dev` or any `features/*` branches. In case you want to have different behaviors for release branches instead, then you may want to either make use of [conditions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml) inside the same pipeline or create multiple pipelines (that again will start from `Dev` branch and then flow into different branches);
1. In case you want the pipeline to run automatically against release branches, then you have to specify these branches inside the trigger section of the pipeline definition, like you are already doing for `Dev` and `features/*` branches:

```yaml
trigger:
- Dev
- features/*
- Release/*
```

You can read more about how it works from the getting started guide on the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?view=azure-devops&tabs=yaml).

**Comment by saxenark** [comment]
Thanks. 

I think I am beginning to form some understanding with the help of your reply. But some loose ends remain

This is how my current "DevelopPipeline" looks like in my Dev branch. This is azure-pipelines-developpipeine.yml

```
trigger:
- Dev
- features/*

variables: 
  majorVersion: 0
  minorVersion: 1
  patchVersion: 0
  buildNumber: 0
  MBld_Version: $(majorVersion).$(minorVersion).$(patchVersion).0
  revision: neverrelease
  branch: $(Build.SourceBranchName)
```

Now, to create a Release branch R1.0, I have the following options (where major, minor versions change from Dev branch)

**Option 1:**
1. Create a Release branch R1.0

2. Create a new pipeline R1.0. This will require me to make a copy of azure-pipelines-developpipeline.yml say azure-pipelines-R1.0.yml for the new pipeline

trigger:
```
// Since I don't want R1.0 pipeline to be triggered due to changes in Dev, I have removed it
#- Dev

// Since I don't want R1.0 pipeline to be triggered due to changes in features/*, I have removed it
#- features/*

// Any R1.0 specific feature requests need to be done under features/R1.0 folder
- features/R1.0/*

// I will be doing bug fixes for R1.0 branch in bugfix/R1.0/*, I have added a new path filter
- bugfix/R1.0/*

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
// Changes version numbers to what R1.0 must have
  majorVersion: 1
  minorVersion: 0
  patchVersion: 0
  buildNumber: 0
  MBld_Version: $(majorVersion).$(minorVersion).$(patchVersion).0
  revision: R1.0
  branch: $(Build.SourceBranchName)
```

Qn: As a best practice, should azure-pipelines-R1.0.yml be merged back to Dev branch?

Option 2:
1. Create a Release branch R1.0

2. Don't create azure-pipelines-R1.0.yml and R1.0 pipeline. Instead modify azure-pipelines-developpipeline.yml in R1.0 branch. 

```
// Since I don't want R1.0 pipeline to be triggered due to changes in Dev, I have removed it
#- Dev

// Since I don't want R1.0 pipeline to be triggered due to changes in features/*, I have removed it
#- features/*

// I will be doing bug fixes for R1.0 branch in bugfix/R1.0/*, I have added a new path filter
- bugfix/R1.0/*

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
// Changes version numbers to what R1.0 must have. But how to use conditions here?
  majorVersion: 0
  minorVersion: 1
  patchVersion: 0
  buildNumber: 0
  MBld_Version: $(majorVersion).$(minorVersion).$(patchVersion).0
  revision: R1.0
  branch: $(Build.SourceBranchName)

Qn: How do I use conditions to define my variables for versions (comment in the code snippet above)

Qn: Which option is preferred (Option 1 or Option 2) from a long term perspective?

Qn: Is it the right way to conceptualize that bug fixes for R1.0 branch (or hotfixes) will be under - bugfix/R1.0/* and hence set a trigger for it? Likewise for features/R1.0/*? 
Is there a recommendation on this aspect of git branching and pipeline concepts for Azure DevOps?

Sorry, if this is not clear, I am glad to get in to a conference call or any other suitable option.

Thanks,
Anubhav.

**Comment by matteotumiati** [comment]
I'll try to answer all your questions 😄 

> Qn: As a best practice, should azure-pipelines-R1.0.yml be merged back to Dev branch?

It really depends only if you think you will need this again in the future. What if you need to create, for example, `Release/R2.0` in the future to release an update of your software? Do you still need the pipeline (don't consider minor differences like build number and such)?

> Qn: What is the use of azure-pipelines-developpipeline.yml in R1.0 branch. It seems wastesful to me since it will never be used for building R.10 branch, at least as per what I am thinking.

It might be just because you aren't using it directly. But again, it depends on what you need and how much do you care about it. It might sound as optional to have it there, but to me it is still valuable because I can see from the git history where it came from. 

> Qn: How do I use conditions to define my variables for versions (comment in the code snippet above)

You cannot use conditions in variables, but you can create variables with a PowerShell script:

```yaml
# Create a variable
- script: |
    echo "##vso[task.setvariable variable=sauce]crushed tomatoes"

# Use the variable
# "$(sauce)" is replaced by the contents of the `sauce` variable by Azure Pipelines
# before handing the body of the script to the shell.
- script: |
    echo my pipeline variable is $(sauce)
```

In this case I'm just creating a variable, but in your case you can setup different if-else statement and declare variables depending on that. Please refer to [this documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-job-scoped-variable-from-a-script) on how to get started.

> Qn: Which option is preferred (Option 1 or Option 2) from a long term perspective? What are the pros and cons? Any documentation or reference material here?

> Qn: Are there any other options other than Option 1 and Option 2 which I may be missing?

I don't know and I don't think there is a best practice for it because it really depends only on your solution and on how you manage the build and release process. 

I can tell you that from my experience, I prefer to have just one pipeline and have conditions applied wherever changes are needed based on the agent I'm running or the branch I'm building and so on and so forth. As you said:

> There could be many more differences as the product evolves

It is totally true, and that's why YAML pipelines will become handy: with just a single file you can have full traceability of your pipeline over time and you can modify it when you need it, just like any other file you have in your repository. 

Based also on this question:

> Qn: Is it the right way to conceptualize that bug fixes for R1.0 branch (or hotfixes) will be under - bugfix/R1.0/* and hence set a trigger for it? Likewise for features/R1.0/*?
Is there a recommendation on this aspect of git branching and pipeline concepts for Azure DevOps?

It seems to me that you need to better review your process from an high level perspective first. Try to ask yourself questions like:
. Where do I need to deploy my code?
. Will the code be deployed always in the same place for the same branch?
. How is the versioning supposed to work? Should it work the same way across branches?
. What are the differences in the process between dev branches, feature branches and release branches?
. How do I want to manage bug fixes? Can the process be different when the bug is happening in the dev environment rather than in a production environment?
. How fast do I need to release?

When you have all this (and probably way more) questions answered, then you can choose the best strategy that will work for you and your projects.

Again, for my experience what I'm seeing working the best is [GitFlow](https://danielkummer.github.io/git-flow-cheatsheet/) because it's probably the simplest to get started and because it's very similar to the approach you are using, but there are others git branching strategies like [GitHub Flow](https://guides.github.com/introduction/flow/) that are great anyway. I cannot suggest what will be better for you, because you need to understand your needs first 😄 

Once you defined that, you can probably choose also a versioning system, so that it will be the same across branches to avoid confusion. For example, you can probably use [GitVersion](https://gitversion.readthedocs.io/en/latest/input/docs/git-branching-strategies/gitflow-examples/) to automatically calculate the version number of your application based on the branch that you are building from the pipeline. Again, it depends on your needs because you may have different version numbers that reflects the current date, the "business" version and so on. 

Please review the documentation on how to get started with Azure YAML Pipelines [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/?view=azure-devops). From there you can also understand key concepts, read many how-to guides and review some case studies.
