### ISSUE TITLE
Allow for setting pool on stages

### ISSUE THREAD

**Issue by denravonska** [microsoft/azure-pipelines-yaml#413]
Since it's not possible to use conditions on templates or use conditional inserts on queue time variables we have to resort to splitting a job up into multiple jobs, each with the appropriate `condition` set. This leads to a lot of repetition as you have to specify the pool on each of the jobs.

It would be a nice quality of life if you could set the pool on the stage, or even better: on the entire pipeline, allowing for override on a per-stage or job basis.

**Comment by matteotumiati** [comment]
> It would be a nice quality of life if you could set the pool on the stage, or even better: on the entire pipeline, allowing for override on a per-stage or job basis.

You can set the pool at pipeline, stage and job level if you need to. 
Here's a valid YAML pipeline:

```yaml
trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: FirstStage
  jobs:
  - job: FromWindows
    steps:
    - script: echo "hello from Windows (pool not specified, inherited from pipeline)!"
  
  - job: FromLinux
    pool:
      vmImage: 'ubuntu-18.04'
    steps:    
    - script: echo "hello from Ubuntu (pool specified at job level)!"

- stage: SecondStage
  pool:
    vmImage: 'macOS-10.13'
  jobs:
  - job: FromMacOS
    steps:    
    - script: echo "hello from macOS (pool not specified, inherited from stage)!"
```

Right after the definition of the triggers and before setting stages, I've set the pool default image for the entire pipeline. This means that every job that will get executed will run on that default image (see the Windows case in `FromWindows` job) if pool aren't specified at other levels. 

When you have to change and specify a different agent, you can change the `pool` at job or stage level to better refine your pipeline (see `FromLinux` and `FromMacOS` examples). 

You can read more about pools [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pool) and specifically for stages [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml).
