### ISSUE TITLE
MultiCheckout Yaml Trigger and Schedules

### ISSUE THREAD

**Issue by nreddipalle** [microsoft/azure-pipelines-yaml#418]
I do have my yamls in one repo and source code in different repo.. 
How does triggers and cron schedules work in this case.. 

If I set trigger on develop.. will it work based on my yaml repo... same for schedules..
How Can I set triggers and schedules to execute based on my second repo??
Does this work? https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md#schema-1
repositories:
  - repository: myPHPApp      
    type: GitHub
    connection: myGitHubConnection
    source: ashokirla/phpApp
    trigger:
      branches:
      - master
      - releases/*

**Comment by matteotumiati** [comment]
Schedules are working based on time, so you shouldn't have any issue there. You can set the schedule on repo A (where YAML lives) and checkout content from repo B (where source code is) using the [multi-checkout feature](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops). Once the code is checked out from the pipeline in repo A, then you can eventually switch to the desired branch you want to build. 

Regarding CI triggers, the approach I usually follow is a bit different. As you said, you can eventually use triggers in repo A (to checkout `master` branch for example), but that is referring only to the branch in repo A (not the one containing the source code) so you won't be able to detect any changes from repo B. 

What I do instead, is creating a very basic pipeline in repo B where I specify only the CI trigger (for example again the `master` branch), then from that pipeline I use a [template](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops) stored in repo A where I do all the work needed to the pipelines.

**Comment by nreddipalle** [comment]
Thank you. Schedules worked fine and invoking on repo A with out any issues...
But setting up a template in repo B to call the YAML file (same YAML file as above)  in repo A is throwing me errors like Unexpected value "variables", unexpected value "stages" etc.. looks like I need to create a different yaml template file in repo A removing variables,triggers,repositories sections. Is it the case??

**Comment by matteotumiati** [comment]
Sorry for the late reply, was on vacation 😄 
Can you share your YAML files to reproduce the issue?

In my opinion you only have to create a YAML file in repo A where you add all the triggers, stages and so on and where you need something to the repo B, you can reference the template there. 

Something similar to this one (note that it might not work as I wrote it without proper testing):

```yaml
# YAML file in repoA representing the pipeline
trigger:
- master
 
resources:
  repositories:
    - repository: repoB
      type: git
      name: repoB
 
stages:
 
- template: 'MyYamlTemplate.yaml@repoB'
  parameters:
    param1: 'this is a param value'
    param2: 'this is another param value'
```

```yaml
# MyYamlTemplate.yaml file in repoB representing the template
parameters:
- param1: ''
- param2: ''

stages:
- stage: myStageFromTemplate
  jobs:
  - job: myJobFromStage
    steps:
    - script: echo 'this is written in template from repoB but executing from repoA'
```

Otherwise, if you want everything to be stored in repoB, then you can use the keyword `extends` released recently (Sprint 162 for Azure DevOps). More info available [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-162-update#use-extends-keyword-in-pipelines)
