### ISSUE TITLE
Multistage artifact download doesn't work

### ISSUE THREAD

**Issue by vikpck** [microsoft/azure-pipelines-yaml#419]
Hi, 

I have a multi-stage pipeline:

Stage 1: Build
Stage 2: Deploy into AKS

Stage 1 produces correct artifacts. I can verify that by downloading them via Azure DevOps UI.
Stage 2 downloads artifacts by name (or at least it should), but instead it downloads the source which is used in the Stage 1. According to the docs, specifying download as current along with artifact name should suffice, but this is not the case. 

Stage 1 publish snippet:

`    - publish: $(System.DefaultWorkingDirectory)/artefacts/ci
      artifact: bob`

Stage 2 download snippet:

`strategy:
      runOnce:
        deploy:
          steps:
          - download: current  # refers to artifacts published by current pipeline
            artifact: bob`

Artifacts should contain files from Stage, but instead they contain source. It also appears that the download happens regardless of whether I have that task or not. Is there some hidden/not documented behaviour here?

Thank you,
Viktor

**Comment by matteotumiati** [comment]
Hi!

Not sure what you exactly mean by:
>  instead it downloads the source which is used in the Stage 1

Do you mean the source code (the repository)? This should be expected when you have a non-deployment job in the pipeline. You can disable that behavior by adding the keyword `checkout: none` to the job steps:

```yaml
jobs:
- job: Build
  steps:
  - script: echo "doing my build and publishing my artifacts here..."

- job: Deploy
  steps:
  - checkout: none 
  - script: echo "nothing will be downloaded now from your repository..."
```

You can read more about it [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout).

Unfortunately it's hard to me to say what's really happening without the YAML pipeline, so I'm just guessing 😄  

Anyway, it seems to me that you are trying to use the "_deployment job_", so I expect your pipeline to be done similarly to this one:

```yaml
jobs:
- job: Build
  steps:
  - script: echo "doing my build and publishing my artifacts here..."

- deployment: Deploy
  environment: demo
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo "all the artifacts will be downloaded automatically..."
```

In this scenario source code shouldn't be checked out, instead all the artifacts produced by previous jobs are automatically downloaded because a download step is injected in your pipeline. That's why:

> It also appears that the download happens regardless of whether I have that task or not.

 The documentation is available [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#artifacts-in-release-and-deployment-jobs).

If you want to prevent this from happening, you need to slightly change the pipeline to first disable the automatic behavior, then to select the artifacts you need to download. For example:

```yaml
- deployment: Deploy
  environment: demo
  strategy:
    runOnce:
      deploy:
        steps:
        - download: none #disable the behavior
        - script: echo "nothing will be downloaded now..."
        - download: current 
          artifact: bob
        - script: echo "only the artifact named bob will be downloaded..."
```

You can read more about how artifacts work from [this page](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml).
