### ISSUE TITLE
Unsupported scenario in pipeline resource triggers

### ISSUE THREAD

**Issue by aee11** [microsoft/azure-pipelines-yaml#423]
I've been experimenting with the pipeline resource trigger but I'm unable to define a simple build dependency graph. The scenario:

* I would like to trigger my test pipeline when an artifact is published by `Frontend` pipeline _and_  `Backend` pipeline.

If my test pipeline has the resource trigger 

```yaml
resources:
  pipelines:
  - pipeline: Frontend
    source: Frontend-CI 
    trigger:
      branches:
      - master
  - pipeline: Backend
    source: Backend-CI 
    trigger:
      branches:
      - master
```

and I get a a commit on master that triggers both `Frontend` and `Backend`, my test pipeline would get fired twice. Is there some way to specify that I want to wait for both pipelines to finish so that my test pipeline only runs once with artifacts from the same version?
