### ISSUE TITLE
Condition in template not evaluated correctly with runtime variable

### ISSUE THREAD

**Issue by agolovenko** [microsoft/azure-pipelines-yaml#425]
Here's the example: 

Main 'azure-pipelines.yml':
```yml
stages: 
- stage: Test
  jobs:
  - job: test
    pool:
      name: 'Hosted Ubuntu 1604'
    steps:
    - bash: |
        echo "##vso[task.setvariable variable=cnd;]none"
      displayName: 'Set condition'

    - template: condition-step.yml
      parameters:
        cnd: $(cnd)
```

Template 'condition-step.yml':
```yml
parameters:
  - name: cnd
    type: string

steps:
  - bash: |
      echo "Condition value: ${{ parameters.cnd }}"
    displayName: 'Test condition'
    condition: ne('${{ parameters.cnd }}', 'none')
```

Main pipeline sets a runtime variable `cnd` and then passes its value as a parameter to `condition-step`. The step checks this parameter in order to decide whether to run or skip.

**Expected result:** the `condition-step` is skipped since `cnd` == `none`
**Actual result:** the `condition-step` is executed with the following output: 
```
##[section]Starting: Test condition
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.159.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
echo "Condition value: none"
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/a28eb750-51ce-49a9-ba8a-ae52dcc4bce8.sh
Condition value: none

##[section]Finishing: Test condition
```

Sidenotes:
+ Please note the output of the step that renders `cnd` with correct value: `Condition value: none`
+ Also if the template is invoked with a static value the condition works as one would expect, but it's not what's needed unfortunately:
```yml
    - template: condition-step.yml
      parameters:
        cnd: 'none'
```
+ If one changes the condition to `condition: eq('${{ parameters.cnd }}', 'none')` an interesting hint comes up: 
![Screen Shot 2020-01-09 at 11 01 12](https://user-images.githubusercontent.com/1433977/72057871-6b6ac580-32cf-11ea-9528-c1f1d1d49d6f.png)

**Comment by denravonska** [comment]
The parameter syntax when used in combination with templates is finicky at best. Try this:

```
# azure-pipelines.yml
- template: condition-step.yml
      parameters:
        cnd: variables['cnd']

# condition-step.yml
...
condition: ne(${{ parameters.cnd }}, 'none')
```

Hint: You might also want to include the pipeline status in that condition if you don't want it to run on pipeline failure:
`condition: and(not(failed(), not(canceled()), ne(${{ parameters.cnd }}, 'none'))`
