### ISSUE TITLE
Can't get variables to be available in YAML file

### ISSUE THREAD

**Issue by LeonidasFettikus** [microsoft/azure-pipelines-yaml#426]
I have a bunch of variables defined in my Azure DevOps Library:

![image](https://user-images.githubusercontent.com/8888670/72076042-2e192e80-32f5-11ea-838e-f6a01c74723f.png)

I then have the following build pipeline:

```
...
variables:
  - group: Android_Build_Pipeline

  steps:

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/*droid*.csproj'
      outputDirectory: $(OUTPUT_DIRECTORY)
      configuration: $(BUILD_CONFIGURATION)
      msbuildVersionOption: latest

  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      apksignerKeystoreFile: $(KEYSTORE_FILE)
      apksignerKeystorePassword: $(KEYSTORE_PASSWORD)
      apksignerKeystoreAlias: $(KEYSTORE_ALIAS)
      apksignerKeyPassword: $(KEY_PASSWORD)
...
```

And Azure DevOps either keeps telling me that the secure file 'KEYSTORE_FILE' can't be fround or it just outputs $(KEYSTORE_FILE) instead of the actual value of the variable. This is driving me crazy. I have tried enclosing them in single quotes, without parenthesis, etc. and nothing works! If I want to output them in PS or BASH, then it works just fine so what am I doing wrong?
