### ISSUE TITLE
Extending a template doesn't seem to work if any YAML is used outside a few 

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/azure-pipelines-yaml#430]
I'm playing around with moving our custom build scripts into a single template that existing builds can extend instead of every project having a series of YAML steps to perform. I took this YAML

```yaml
resources:
   …

trigger:
   batch: true
   branches:
      include:
      - master

pool:
   vmImage: windows-latest

steps:
- template: yaml/build/initialize-build-variables.yml@templates
```

I want to replace everything after the `trigger` by using `extends` so I created a new YAML file in my build tools repo and copied everything from `pool` on into it. Then I modified the source repo's build to look like this.

```yaml
resources:
   …

trigger:
   batch: true
   branches:
      include:
      - master

extends:
   template: yaml/main-build.yml@templates
```

When the build is run it says `pool` is unexpected. This is referring to the element in my template I wanted to extend. So I assumed that you couldn't put `pool` inside the template so I moved it back to the source repo.

```yaml
resources:
   …

trigger:
   batch: true
   branches:
      include:
      - master

pool:
   vmImage: windows-latest

extends:
   template: yaml/main-build.yml@templates
```

I get the same error. So using `pool` before `extends` doesn't work. So I tried moving it after.

```yaml
resources:
   …

trigger:
   batch: true
   branches:
      include:
      - master

extends:
   template: yaml/main-build.yml@templates

pool:
   vmImage: windows-latest
```
This says `extends` is unexpected now. It doesn't seem like `extends` can be used with anything other than maybe `resources` and `triggers`. What are the rules around where `extends` can be used and what can go into it? At this point I don't see any place where I can put `pool` and so I cannot see how I can use this in a build.

**Comment by beatcracker** [comment]
I'm experimenting with `extends` and this works in template:
```
trigger:
  branches:
    include:
      - develop
      - master

# Fails: Unexpected value 'pr'
# pr: none

resources:
  containers:
    - container: node
      image: node:10

stages:
  - stage: Common

    jobs:
      - job: Build

        pool:
          vmImage: 'ubuntu-latest'
          workspace:
            clean: all

        steps:
          - checkout: self
            clean: true

          - bash: echo "IT'S ALIVE ! ---==:[~ $BUILD_SOURCEBRANCHNAME ~]:==---"
            target: node
```
I'd appreciate a better docs for `extends` too.

**Comment by Bibz87-CG** [comment]
Any new info on this? I'm trying to do the same thing and I too get the `Unexpected value 'extends'` error.

**Comment by Bibz87-CG** [comment]
@CoolDadTx I've been able to fix my pipeline templates by moving the `pool` entry to each stage definition instead of having it in the root yaml file.

@beatcracker haven't tried with `pr`, though.

**Comment by aglorei** [comment]
Echoing everyone else, also have this problem, with pools and container resources as well.

**Comment by vtbassmatt** [comment]
`extends` currently requires an explicit `jobs:` or `stages:` wrapper even in the case of a single job. We are looking into whether we can relax this restriction to be more in line with how non-`extends` pipelines can be written. (See below for some history.) The two rules are:
1. If a pipeline contains `extends`, then only `trigger`, `pr`, `schedule`, and `resources` can appear at the top level alongside `extends`.
2. If a pipeline template will be the target of `extends`, then it must have at least a `jobs` level specified.

Taking the example from the top of this issue:
```yaml
resources:
   …

trigger:
   batch: true
   branches:
      include:
      - master

pool:
   vmImage: windows-latest

steps:
- template: yaml/build/initialize-build-variables.yml@templates
```

You'd have to write that as:
```yaml
# azure-pipelines.yml
resources:
   …

trigger:
  batch: true
  branches:
    include:
    - master

extends:
  template: yaml/main-build.yml@templates

# yaml/main-build.yml
jobs:
- job:
  pool:
    vmImage: windows-latest

  steps:
  - ...
```
---

In case you're interested in the history, we introduced "level elision" very early on. The thinking was, it would make YAML pipelines more approachable. If you only have a single job, why bother with the boilerplate of "jobs:" and "job:"? In practice, this has mostly led to confusion for users and complication every time we add language features. If I had a time machine, I'd go back and remove level elision. Notably, GitHub Actions (designed by some of the same people who designed Azure Pipelines YAML) doesn't allow for level elision, and it hasn't been a problem.

In the case of `extends`, we didn't complete all the necessary refactoring to make bare-single-jobs work as an extends target. We believed that `extends` would not commonly be used for single-job pipelines, and thus it would be wasted effort and increased risk of introducing bugs. But this feedback makes it clear that we were wrong, and we'll get an item on the backlog to bring it to parity.
