### ISSUE TITLE
Build variables not parsed in container options

### ISSUE THREAD

**Issue by Beakster** [microsoft/azure-pipelines-yaml#431]
I am using Azure DevOps Server 2019 Update 1.  Using classic pipelines I was able to launch Docker containers with volumes mounted to my source directory.  It seems this is not possible using Yaml Pipelines as the variables are not parsed.

Consider the following YAML:

```
trigger:
- master

pool:
  name: 'Linux'

container: 
  image: adoptopenjdk/maven-openjdk11
  options: --rm -v $(Build.SourcesDirectory):/app -v $(Build.BinariesDirectory):/app/target -v /home/agent/.m2:/root/.m2 -w /app

steps:
- script: echo $(Build.SourcesDirectory)
  displayName: 'Maven Package'
```

The purpose of this build script is to build a maven project in the Source Directory, put the output in the Binaries Directory, and use the Maven repository in the home directory so that all the artifacts are not downloaded on every run.

It fails with the messsage: 

> Error response from daemon: create $(Build.BinariesDirectory): "$(Build.BinariesDirectory)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path

However, if the container section is removed then the script at the end correctly outputs the Source directory.  It seems that the options section of the container element does not have variables parsed.  This is a massive impediment as it means I cannot get any code in or out of my containers rendering the useless for building.
