### ISSUE TITLE
Dynamically expand variable names based on other variables

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/azure-pipelines-yaml#432]
We have a pipeline that provisions resources in different subscriptions in different azure tenants. In each tenant/subscription we have a keyvault with secrets used in provisioning so we have a central place to store secrets for that environment. We want to be able to provision for all our tenants from one pipeline. Our plan was to create a centralized keyvault with config values but not secrets for each tenant containing tenant name, subscription name and service connection name prefixed with a unique key for each customer. Using a queue time variable we would device for which customer we are provisioning. To be able to do this we have to expand variables based on variable names that themselves are based on variables. Ex:

```yml
variables:
 #  CustomerKey: 'TEST'                      # Set at pipeline queue time in azure devops
 - group : ProvisionKeyvault
 - name: TenantName
   value: $($(CustomerKey)-tenantname)
 - name: SubscriptionName
   value: $($(CustomerKey)-subscriptionname)

stages:
 - deployment: Provisioning
    displayName: Provision
    environment: $(CustomerKey)
    strategy:
     runOnce:
       deploy:
         steps:
         - checkout: self
         - task: AzureCLI@2
           inputs:
             azureSubscription: 'PROVISION_$(CustomerKey)_AzureSubscription' # Gets the Service Connection with the appropriate name
             scriptType: 'ps'
             scriptLocation: 'scriptPath'
             scriptPath: '$(System.DefaultWorkingDirectory)/provisioning/New-Provisioning.ps1'
             workingDirectory: '$(System.DefaultWorkingDirectory)/provisioning/'
             arguments: '-TenantName $(TenantName) -SubscriptionName $(SubscriptionName) -CustomerKey $(CustomerKey)'

```

So specifically I want to achieve something like `$($(CustomerKey)-subscriptionname)`.

We have a key vault with secret TEST-subscriptionname and as value for example 'TEST_TEST_SUB_RD02'
and secret TEST-tenantname with as value 'TEST_CUST.onmicrosoft.com'

$(CustomerKey) is a queue time variable, which could be set to 'TEST'
$(CustomerKey)-tenantname should expand to 'TEST-tenantname' which is a variable in the pipeline because we have a keyvault linked through a variable group
$($(CustomerKey)-tenantname) should expand to 'TEST_CUST.onmicrosoft.com'

Anyone have any suggestion how to do this, and if not are there any plans to make something like this possible?
