### ISSUE TITLE
Checking out multiple repos in a deployment job is not working

### ISSUE THREAD

**Issue by ivan-sam** [microsoft/azure-pipelines-yaml#433]
Deployment job schema allows using checkout [Deployment jobs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)

So I want to use checkout step in deployment job in order to specify ARM template from a separate repository ([Check out multiple repositories in your pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)).

I've got an error: **Checkout of repository '*******' is not supported. Only 'self', 'none', or a repository alias are supported.** Note: converting the job to a regular job fixes the problem.
But then I loose the features of deployment jobs: strategies, hooks, environment deployment history.

I created simple yaml pipeline that reproduces the issue:

```
resources:
  repositories:
  - repository: azureinfrastructure
    name: AzureInfrastructure
    type: git

stages:
- stage: TestWithCheckoutOnDeploy
  jobs:
  - deployment: 'Deploy_to_Test'
    pool:
      vmImage: 'ubuntu-16.04'
    environment:
      name: Test
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: azureinfrastructure
            
- stage: TestWithCheckoutOnPredeploy
  condition: always()
  jobs:
  - deployment: 'Deploy_to_Test_with_predeploy'
    pool:
      vmImage: 'ubuntu-16.04'
    environment:
      name: Test
    strategy:
      runOnce:
        preDeploy:
          steps:
          - checkout: azureinfrastructure
          - script: echo predeploy test
        deploy:
          steps:
          - script: echo deploy test

- stage: TestWithCheckoutRegularJob
  condition: always()
  jobs:
  - job: 'Deploy_to_Test_with_regular_job'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - checkout: azureinfrastructure
    - script: echo deploy test
```
When running the pipeline above I got the following errors:
![110686-bug-2019-12-19-102424](https://user-images.githubusercontent.com/4918115/72610587-13177180-3928-11ea-9af8-26a60b156fa1.png)
