### ISSUE TITLE
Azure DevOps Pipelines - Stuck in Job is pending...

### ISSUE THREAD

**Issue by aymond** [microsoft/azure-pipelines-yaml#434]
Hi All,

I have three pipelines configured that use different .yml files within the same repo. 
Agent Pool is a single self-hosted agent. The status of the agent is Online, and Idle. The Azure DevOps portal only tells me: 

> 1 .   Job is pending...

I manually scheduled the three pipeline runs, and the first one ran and completed successfully. The jobs are not configured to run in parallel. My expectation is that the queued jobs would run sequentially when the agent pool becomes available. The second and third jobs are stuck in a Pending state. 

I have tried cancelling the jobs, and then re-running the pipelines with no success, I have also tried restarting the self-hosted agent and then re-running the pipelines also without success. The jobs remain in a Pending state.

Many thanks for your help, template below without steps.

``` yml
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - packer/azure/CO7-template.json
    - scripts/azure/CO7-azure-pipelines.yml
variables:
  - group: baseimages
  - name: ImageVersion
    value: $(Build.BuildNumber).0
schedules:
  - cron: "0 1 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true

pool: Default

steps:
```
