### ISSUE TITLE
System.PullRequest.TargetBranch not available to templates

### ISSUE THREAD

**Issue by dopry** [microsoft/azure-pipelines-yaml#435]
The documentation say System variables are available to templates.

Our user case was templating some global variables for different branches in a single pipeline. 

```
parameters:
  DEV_BRANCH: refs/heads/dev
  MO_BRANCH: refs/heads/mo
  PROD_BRANCH: refs/heads/master

variables:
  ## booleans to identify target environment for build.
  ${{ if or(eq(variables['Build.SourceBranch'], parameters.DEV_BRANCH), eq( variables['System.PullRequest.TargetBranch'] , parameters.DEV_BRANCH)) }}:
    BUILD_TARGET: 'DEV'

  ${{ if or( eq( variables['System.PullRequest.TargetBranch'] , parameters.MO_BRANCH),   eq(variables['Build.SourceBranch'], parameters.MO_BRANCH)  ) }}:
    BUILD_TARGET: 'MO'

  ${{ if or( eq( variables['System.PullRequest.TargetBranch'] ), eq(variables['Build.SourceBranch'], parameters.PROD_BRANCH) ) }}:
    BUILD_TARGET: 'PROD'
```

We were ultimately about to do with with a script... but we're forced to include that script with every steps, and the data isn't available at stage and global levels where we'd also like to use those variables.
