### ISSUE TITLE
Predefined variables cannot be accessed by property dereference syntax in runtime expressions

### ISSUE THREAD

**Issue by peter-bloomfield** [microsoft/azure-pipelines-yaml#436]
The [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops) outlines two ways of referring to variables in expressions:

* Index syntax: variables['MyVar']
* Property dereference syntax: variables.MyVar

Both syntaxes work when referring to variables defined within the pipeline. However, only the index syntax seems to work when referring to predefined variables, such as `Build.SourceBranch`.

**Example**
Here is a simple pipeline which demonstrates the problem. It tries to store the source branch in two variables (one for each syntax), and then output them both in a script step:

```
variables:
  sourceBranchViaIndex: $[ variables['Build.SourceBranch'] ]
  sourceBranchViaProperty: $[ variables.Build.SourceBranch ]

steps:
- script: |
    echo "sourceBranchViaIndex=$(sourceBranchViaIndex)"
    echo "sourceBranchViaProperty=$(sourceBranchViaProperty)"
  displayName: Display source branch
```

(This is deliberately a very simplified example. The same issue occurs when the expressions are more complex though.)

**Expected behaviour**
Based on the documentation, I think both methods of referring to predefined variables should work. As such, I would expect this output:

```
sourceBranchViaIndex=refs/heads/master
sourceBranchViaProperty=refs/heads/master
```

**Actual behaviour**
The pipeline appears to execute successfully. However, the actual output is:

```
sourceBranchViaIndex=refs/heads/master
sourceBranchViaProperty=
```

This suggests that only the index syntax is working in the runtime expressions.
