### ISSUE TITLE
Environments - resourceType: appService

### ISSUE THREAD

**Issue by michaeldtaylor** [microsoft/azure-pipelines-yaml#442]
The docs for environment say that 'resourceType: appService' should work?

https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/environment.md

I have 7 Function Apps - currently with individual pipelines (I will have a unified one eventually, this is a refactor from something else to YAML multi-stage pipelines).

I'd like to be able to have the environment defined as:
````
environment:
  name: Dev1
  resourceName: myfunctionapp      <--- this will be a real Function App name
  resourceType: appService
  tags: Tag1
````
I only see VirtualMachine and Kubernetes in the Azure Pipelines Environments UI. So is appService supported as a resourceType, and if so how do I use it?
