### ISSUE TITLE
Conditional template execution based on environment variable

### ISSUE THREAD

**Issue by nosalan** [microsoft/azure-pipelines-yaml#444]
How to execute template conditionally based on env variable value?
I was able to do similar thing by checking template parameter like this:

```
  - ${{ if eq( parameters.DRY_RUN_MODE_FLAG, false) }}:
    - template: /azure/pipelines/common/templates/assert_deployment.yml
```
But, given that `DRY_RUN_MODE_FLAG` is an env variable and not a parameter how to achieve such condition? I tried `variables.DRY_RUN_MODE_FLAG` it was executed by Azure but it didn't work.

**Comment by Justin-DynamicD** [comment]
So I learned the hard way that the final pipeline is "assembled" before any parameters are applied which get applied at run time.

So if you want a parameter to prevent an entire template to trigger, your best bet is to move the template into a unique job/stage (depending on how your template is assembled) and then you can apply a condition to that parent step.

Example of how I currently handle it:

```
- job: doAThing
  displayName: Do a thing
  condition: eq(dependencies.preflight.outputs['setVarStep.result'], 'true')
  dependsOn: preflight
  workspace:
    clean: all
  steps:
    - template: doathing.yml@templates
      parameters:
        <...>
```

So here I have a template that will only trigger if a previous job output is true.  I had to set `dependsOn` so it didn't run in parallel, and then make sure I exported the variable for consumption, but the result is what you're asking: the template only runs if the condition is met.  As the template tasks are expanded under the `doAThing` job ... they all fall under the stated condition.
