### ISSUE TITLE
Possible to set task properties like continueOnError dynamically?

### ISSUE THREAD

**Issue by 686d7066** [microsoft/azure-pipelines-yaml#445]
Hi,

I am trying to use variables to dynamically set task-properties like "continueOnError" and am unable to get this to work. I am not even sure if it´s possible to get this to work.

I am currently setting up a build pipeline based on YAML to reduce build times in pull requests by only building and testing the applications that have actual changes (based on git diff entries). The actual build job then uses a matrix and its value is a generated json-dictionary containing the applications that need to be build.
This looks something like this:
```yaml
{
  "some_application_name": {    
    "type": "netcore",    
    "continueOnErrors": true,    
    ...
  },
  "some_other_application_name": {
    "type": "nodejs",
    "continueOnErrors": false,
    ...
  }
}
```

This works pretty well and the build step replicates itself for each entry and executes successfully. I am able to access and use properties like the "type" in e.g. the condition property of tasks:
```yaml
condition: and(succeeded(), eq(variables['type'], 'nodejs'))
```
However I am unable to set other task-properties like the initially mentioned "continueOnError" dynamically:
```yaml
continueOnError: ${{ variables['continueOnErrors'] }}
```
or
```yaml
continueOnError: ${{ eq(true, variables['continueOnErrors']) }}
```

The expression itself correctly returns true or false, e.g. through this test:
```yaml
- powershell: Write-Host "Equals true";
  condition: eq(true, variables['continueOnErrors'])
- powershell: Write-Host "Equals false";
  condition: eq(false, variables['continueOnErrors'])
```
When running the pipeline the correct tasks trigger.

Trying to use runtime expansion returns an error saying the $-sign is unexpected:
```yaml
continueOnError: $[variables['continueOnErrors']]
```

Is there anyway to achieve what I am trying?

**Comment by 686d7066** [comment]
My current workaround is duplicating the tasks and use the condition to run them with or without "continueOnError" but this causes some clutter as the changes need to be made twice and both tasks show up in the UI but only one is ever executed.

Example:
```yaml
- powershell: |
    # Do something
  condition: and(succeeded(), eq(false, variables['continueOnErrors']))
  inputs:
    ...
- powershell: |
    # Do something
  condition: and(succeeded(), eq(true, variables['continueOnErrors']))
  continueOnError: true
  inputs:
    ...
```

**Comment by afeblot** [comment]
Same workaround for me :-( 
I wish we'll have someday consistent substitutions and notations in those pipelines...

**Comment by rettichschnidi** [comment]
After wasting too many hours, this seems to work in Azure DevOps:

```
continueOnError: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
```

But I wish for you to have already moved on from DevOps - it's a truly terrible experience IMHO.

**Comment by salmira** [comment]
> If someone is still struggling with this, one thing is that all variables are strings in Azure, so comparison must be done with single quotes. I.e. ${{ eq(true, variables['someVar']) }} will always return true regardless of what 'someVar' is (except unassigned then it will be false). Use ${{ eq('true', variables['someVar']) }} then the comparison will be correct

Unfortunately, it does not work now, and continueOnError is ignored...

```
stages:
- stage: StaticMartix
  jobs:
    - job: MyMatrixJob
      strategy:
        matrix:
          config1:
            myContinueOnError: true
          config2:
            myContinueOnError: false
      steps:
      - checkout: none
      - script: |
            echo "This is a test script."
            echo  Simulate a failure
            echo myContinueOnError=$(myContinueOnError)
            echo myContinueOnError=${{ eq('true', variables['myContinueOnError']) }}
            exit 1
        continueOnError: ${{ eq('true', variables['myContinueOnError']) }}

      - script: echo next step
```

Variant with `${{ eq('true', variables['myContinueOnError']) }}` always gives `false` despite of actual value defined by Strategy Matrix:

myContinueOnError=true   # for $(myContinueOnError)
myContinueOnError=False   # for ${{ eq('true', variables['myContinueOnError']) }}

![Image](https://github.com/user-attachments/assets/ce89c55e-7e83-4914-8513-861f3e332f8d)
