### ISSUE TITLE
Resources > Repository triggers not firing and default triggers not disabled

### ISSUE THREAD

**Issue by nealAR** [microsoft/azure-pipelines-yaml#448]
I have a triggers set up in our `azure-pipelines.yml` like so below: 

1. the `scriptsconn` represents a connection to the default/`self` repo that contains the deployment pipeline yaml.

2. the `serviceconn` represents a microservice repo we are building and deploying using the template and publish tasks. 

We have multiple microservices with similar build pipelines, so this approach is an attempt to lessen the amount of work needed to update these steps. 

Right now the issue we're running into is two fold: 

1. no matter what branch we specify in the `scriptsconn` resources -> repositories section the build triggers for every commit to every branch in the repo. 

2. no matter how we configure the trigger for `serviceconn` we cannot get the build to trigger for any commit, PR created, or PR merged.  

According to the link below this configuration should be pretty straighforward. Can someone point out what mistake we're making?

https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md#repositories

```
resources:
  repositories:
    - repository: scriptsconn
      type: bitbucket
      endpoint: BitbucketAzurePipelines
      name: $(scripts.name)
      ref: $(scripts.branch)
      trigger:
        - develop
    - repository: serviceconn
      type: bitbucket
      endpoint: BitbucketAzurePipelines
      name: $(service.name)
      ref: $(service.branch)
      trigger:
        - develop
      pr:
        branches:
        - develop
    

variables:
  - name: service.path
    value: $(Agent.BuildDirectory)/s/$(service.name)
  - name: scripts.path
    value: $(Agent.BuildDirectory)/s/$(scripts.name)
  - name: scripts.output
    value: $(scripts.path)/$(release.folder)/$(release.filename)
  - group: DeploymentScriptVariables.Dev

stages:
- stage: Build
  displayName: Build and push an image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: 'Private Ubuntu 1804 LTS'
    steps:   
    - checkout: scriptsconn
    - checkout: serviceconn
```

I've also written the triggers like so however I'm seeing the same behavior (no builds triggered to commits/PRs to `serviceconn` and builds being kicked off for commits to any branch of `scriptsconn`).

```
resources:
  repositories:
  - repository: serviceconn
    type: bitbucket
    endpoint: BitbucketAzurePipelines
    name: templumdigital/reconciliationservice
    ref: develop
    trigger:
      batch: true
      branches:
        include:
        - develop
    pr:
      - develop
  - repository: scriptsconn
    type: bitbucket
    endpoint: BitbucketAzurePipelines
    name: templumdigital/primarydeploymentscripts
    ref: azurepipeline_nr
    trigger:
      batch: true
      branches:
        exlude:
        - azurepipeline
```
