### ISSUE TITLE
`UniversalPackages@0` cannot specify views

### ISSUE THREAD

**Issue by Justin-DynamicD** [microsoft/azure-pipelines-yaml#451]
When downloading a universal package using `UniversalPackages@0`, I'm unable to filter the version by view.  As such, if a version is promoted to "@Release" I cannot filter by said release as part of a deployment pipeline.

I seem to be able to do this in the release pipeline GUI, but I think being able to do this from YAML would be ... wonderful.

Sample desire:

```
- task: UniversalPackages@0
  displayName: Download Artifacts
  inputs:
    command: download
    downloadDirectory: $(System.DefaultWorkingDirectory)/$(tfPath)
    feedsToUse: internal
    vstsFeed: <...>
    vstsFeedPackage: my-artifact
    vstsFeedVersion: '@Release'
    vstsPackageVersion: *
```

The ask is simple enough: let me filter the package download by more than simply the version.

Bonus points (though likely outside this request): let me add an artifact feed as a resource so I can trigger deployments with it (ohhhh fancy) :)

<Edited to fix sample syntax>

**Comment by Justin-DynamicD** [comment]
This can be closed.  Turns out you _can_ download by views, you simple include the @view when specifying the feed.  Example:

```
- task: UniversalPackages@0
  displayName: Download Artifacts
  inputs:
    command: download
    downloadDirectory: $(System.DefaultWorkingDirectory)/$(tfPath)
    feedsToUse: internal
    vstsFeed: <...>@PreRelease
    vstsFeedPackage: my-artifact
    vstsPackageVersion: *
```

A documentation update would go a long LONG way in making this info easier to find.
