### ISSUE TITLE
clean up work dir on self hosted agent

### ISSUE THREAD

**Issue by dvescovi1** [microsoft/azure-pipelines-yaml#453]
My pipeline build on my self hosted agent creates incremental folders in the _work directory (1, 2, 3 etc). These eventually fill up my hard disk as they are not cleaned after pipeline completion. I suspect I can add a final task to clean up but I can not find any documentation on how to do this.
Any suggestion, pointers or documentation?

**Comment by f2calv** [comment]
Specifically you are looking for
```yaml
workspace:
  clean: all
```
Yes it's all in the docs, https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job
```yaml
jobs:
- job: string  # name of the job (A-Z, a-z, 0-9, and underscore)
  displayName: string  # friendly name to display in the UI
  workspace:
    clean: outputs | resources | all # what to clean up before the job runs
  steps: [ script | bash | pwsh | powershell | checkout | task | templateReference ]
...
```
