### ISSUE TITLE
Support for githubenterprise endpoint in repository template mechanism

### ISSUE THREAD

**Issue by maci3jka** [microsoft/azure-pipelines-yaml#456]
Azure service endpoint type githubenterprise is not supported in template mechanism when using template from other repository.

In yaml file:
```
resources:
  repositories:
    - repository: commons
      type: github
      name: User/commons
      ref: refs/tags/v1.0
      endpoint: githubenterpriseEndpointName
```
results in:
```
Repository commons specifies endpoint githubenterpriseEndpointName which is of type githubenterprise but an endpoint of type GitHub is required
```

**Comment by mozts2005** [comment]
Change your repo type.

```YAML

resources:
  repositories:
    - repository: commons
      type: githubenterprise
      name: User/commons
      ref: refs/tags/v1.0
      endpoint: githubenterpriseEndpointName

```
