### ISSUE TITLE
Variable implicitly marked as secret by docker task

### ISSUE THREAD

**Issue by GeeWee** [microsoft/azure-pipelines-yaml#457]
I have a variable in a resource group that corresponds to the tenant ID for a given Azure Keyvault instance.

However, even when I don't mark this variable as secret it seems to be marked as secret. I have been able to reproduce it when calling the Docker@2 BuildAndPublish task, but I do not know if it is limited to this

# Example

I can define a variable in a resource group like this: (the tenant id has been edited a bit to censor it)
`KeyVaultTenantId: b97df5-ef00-2e-816d-ebfc94f92`
Not that this variable is **not marked as secret**

I noticed that the variable started being marked as secret sometimes when changing my pipeline. I have managed to reduce it to this example, but I do not know if I can provoke it in other ways

This example will use printenv to demonstrate the variable is secret
```yaml
trigger:
  batch: true
  branches:
    include:
      - "*"
pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: "templates/shared-vars.yml"
  - group: dev

# The next two tasks don't matter, and uncommenting them out makes no difference,
#but my dockerfile requires them
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    displayName: "Build projects"
    inputs:
      command: "publish"
      zipAfterPublish: false
      arguments: -c=Release -o=build
      projects: BulkHarmonizer.Test/*.csproj

# This builds the docker image and somehow overrides the variable
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      command: buildAndPush
      dockerFile: devops/Dockerfile.BulkHarmonizer # TODO fix this
      buildContext: "."
      containerRegistry: $(CONTAINER_REGISTRY_STRING)
      repository: $(IMAGE_REPOSITORY)
      tags: |
        $(Build.BuildId)
        latest
        $(BRANCH)

  - script: printenv
```
The example above results in printenv printing out
`KEYVAULTTENANTID=***`

This example, with removing the added docker PushAndBuild, and **nothing else changed** will correctly print out the variable
```yaml
# Trigger this pipeline on development branch
trigger:
  batch: true
  branches:
    include:
      - "*"
pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: "templates/shared-vars.yml"
  - group: dev

# This stage builds the docker image, and publishes it to
# Azure Container Registry
steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    displayName: "Build projects"
    inputs:
      command: "publish"
      zipAfterPublish: false
      arguments: -c=Release -o=build
      projects: BulkHarmonizer.Test/*.csproj

# No docker build here!
#  - task: Docker@2
#    displayName: Build and Push Docker Image
#    inputs:
#      command: buildAndPush
#      dockerFile: devops/Dockerfile.BulkHarmonizer # TODO fix this
#      buildContext: "."
#      containerRegistry: $(CONTAINER_REGISTRY_STRING)
#      repository: $(IMAGE_REPOSITORY)
#      tags: |
#        $(Build.BuildId)
#        latest
#        $(BRANCH)
##        

  - script: printenv
```
This correctly results in printing out (tenant id censored)
`KEYVAULTTENANTID=b97df5-e0-4e-816d-ebfc948692`

This is supremely weird to me. I have tried renaming the variable, but it seems to be the _content_ of the variable, as the naming doesn't matter, but if I provide it with a different value, it will go through no problem.
