### ISSUE TITLE
Runtime parameter not working "Pipeline parameters not enabled"

### ISSUE THREAD

**Issue by bamb00** [microsoft/azure-pipelines-yaml#458]
The parameters is set in the azure-pipelines.yml.

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14

trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
    - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}
```

Run the pipeline.

![Screen Shot 2020-03-04 at 6 36 00 PM](https://user-images.githubusercontent.com/486660/75936278-487c0e00-5e47-11ea-8e08-85efb4220306.png)

**Comment by matteotumiati** [comment]
Looking at the YAML schema available [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pipeline) it's not possible to add parameters there, but only variables:

```yaml
name: string  # build numbering format
resources:
  pipelines: [ pipelineResource ]
  containers: [ containerResource ]
  repositories: [ repositoryResource ]
variables: # several syntaxes, see specific section
trigger: trigger
pr: pr
stages: [ stage | templateReference ]
```

Otherwise, to reach your goal and use parameters you should be [referencing a template](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#template-references).
