### ISSUE TITLE
Pipeline resource shows inconsistent behavior with partially successful builds.

### ISSUE THREAD

**Issue by DanielBMann9000** [microsoft/azure-pipelines-yaml#459]
Agent version:  2.165.0
Artifacts being downloaded via  
Task         : Download pipeline artifact
Version      : 1.2.4

Let's say I have a multi-stage pipeline that is consuming a different pipeline:

```
resources:
  pipelines:
  - pipeline: Build
    source: Foo Build
    branch: master
    trigger:
      branches:
        include: [master]
```

Let's say that `Foo Build` **never** fully succeeds; it's always a partially successful build. There is not a single fully successful build for this, ever. 

The trigger on build completion will pick up the latest partially successful build when the multi-stage pipeline kicks off. This is okay. 

A manually queued build will fail with this error: `The pipeline is not valid. Unable to resolve latest version for pipeline Build. This could be due to inaccessible pipeline or no version is available.`

Basically, manually queuing **ignores** all of the partially successful runs, but the pipeline resource trigger **includes** partially successful run. This means that you get inconsistent behavior when running manually versus running from a trigger.

Now, the even worse scenario is this: Let's say I have *one* successful build, from a few months ago. We'll say it's build ID 1234. We've done a ton of builds since then, so our next build ID is 6789.

I commit. The build runs. The pipeline trigger fires. It picks up and deploys build 6789.

I decide I want to re-run the pipeline. There have been no builds since the trigger ran; 6789 is still the most recent build on that branch.

I manually queue the build. It picks up and deploys **build 1234**. This is a very old build and is completely unexpected behavior when the pipeline has been happily finding and deploying more recent, partially successful builds.

IMO, consistent behavior is mandatory. The *desired* behavior (for me, at least) would be for partially successful builds to be picked up in both cases. The ability to specify whether to include partially successful builds have that rule consistently applied across triggers and manual invocations would be best.

Two pipelines that repro the issue:

Build:
```
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "##vso[task.logissue type=warning]foo"
    exit 1
  continueOnError: true

- publish: $(Pipeline.Workspace)
  artifact: foo
```

Multistage pipeline:
```
trigger: none
pr: none
resources:
  pipelines:
  - pipeline: Build
    source: YAMLTest
    branch: master
    trigger:
      branches:
        include: [master]

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DEV
  jobs:
  - deployment: DEV
    displayName: DEV
    environment: DEV
    strategy: 
      runOnce:
        deploy: 
          steps: 
          - script: echo $BUILD_BUILDNUMBER!
            displayName: 'Run a one-line script'
```
