### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by alexandermujirishvili** [microsoft/azure-pipelines-yaml#460]
I try to conditionally import my variable groups in my pipeline. It looks like this:

```
variables:
 ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
 - group: variables-shared
 - group: variables-production
 ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
 - group: variables-shared
 - group: variables-staging
```

The problem I have is that I get 'Object reference not set to an instance of an object' error. If I remove conditionals, everything works fine. If I remove group imports, I get the errors (other type of errors), that are natural because variables have not value.

So the pair of conditionals and group imports make this error to arise. 

![image](https://user-images.githubusercontent.com/46314872/76158793-1f06ff00-6133-11ea-9e4f-b07efeaa19c1.png)

![image](https://user-images.githubusercontent.com/46314872/76158798-275f3a00-6133-11ea-9c7f-6d42cbafde38.png)

**Comment by esoler-sage** [comment]
Hi @alexandermujirishvili I think that you can use it but with a list schema:

```yaml
variables:
 - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
   - group: variables-shared
   - group: variables-production
 - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
   - group: variables-shared
   - group: variables-staging
 - group: variables-staging-default
```

as the variables expects a list of variables
