### ISSUE TITLE
Access iterator inside each loop

### ISSUE THREAD

**Issue by djpugh** [microsoft/azure-pipelines-yaml#463]
Is it possible/can the index be accessed inside a `${{ each...}}` loop?

I'm using an array to hold a list of names for repeated stages, and I'd like to set the dependency based on the previous one

e.g. in jinja 2 there is an index option - `loop.index`

**Comment by JoeGaggler** [comment]
I'd love this as well. For now, you may have a bit of luck attempting to detect the index using a hack I posted in a related issue:

https://github.com/microsoft/azure-pipelines-yaml/issues/427#issuecomment-580372308

**Comment by Hkyx** [comment]
have the same issue, @djpugh how did you solve this?

**Comment by djpugh** [comment]
@Hkyx I gave up with trying, and just manually put stuff in...

**Comment by Hkyx** [comment]
Thanks @djpugh  :/

**Comment by sijucm** [comment]
Another Microsoft rabbit hole. I try to use the loop and run a job, but then the job name has to be unique. To give a job name I try to find the index, but no. Why I need a job (instead of without a job), yeah because some tasks has to be server tasks and some has to be agent tasks. Microsoft world is all about these complex and illogical matrixes. Microsoft is about these rabbit holes and people working with their technology are just enjoying the job security

**Comment by jesselang** [comment]
This issue moved here: https://developercommunity.visualstudio.com/t/access-iterator-inside-each-loop/1192557
It appears to have gone very stale.

**Comment by bew** [comment]
NOTE: I'm using this workaround to get the index:
```yaml
- ${{ each itemValue in parameters.myListOfValues }}:
  - pwsh: |
      $currentIndex = [array]::IndexOf(($env:FULL_LIST| ConvertFrom-Json), "${{ $itemValue }}")
      # ... do something with the index
    env:
      FULL_LIST: ${{ convertToJson(parameters.myListOfValues) }}
```
