### ISSUE TITLE
Broken Repository Simple Syntax

### ISSUE THREAD

**Issue by nickmladenov** [microsoft/azure-pipelines-yaml#464]
It seems as if the most recent Azure Pipelines release (Sprint 166) on March 16th 2020 has broken the simple syntax for repository triggers.

An [example](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md#examples--repo-triggers) of the syntax which has broken majority of my existing YAML pipelines:
```
resources:         
  repositories:
  - repository: myPHPApp      
    type: GitHub
    connection: myGitHubConnection
    source: ashokirla/phpApp
    trigger:
      branches:
      - master
      - releases/*
```

When trying to execute the pipeline manually it will result in the following error message: `/.../pipeline.yaml (Line: 15, Col: 7): A sequence was not expected`

It also causes the repositories CI trigger to become ignored:
```
trigger: none
```

Resulting in every commit made into the repository creating an associated build that will immediately fail with the following error message: `Unexpected type '' encountered while reading 'include exclude filters'. The type 'MappingToken' was expected.`

The current resolution for me was to use the complete syntax by specifying the appropriate `include` and `exclude` keys with their branch values:
```
resources:         
  repositories:
  - repository: myPHPApp      
    type: GitHub
    connection: myGitHubConnection
    source: ashokirla/phpApp
    trigger:
      branches:
          include:
          - master
          - releases/*
```
