### ISSUE TITLE
Use a runtime generated value in a pipeline counter

### ISSUE THREAD

**Issue by guillaume86** [microsoft/azure-pipelines-yaml#465]
Is it possible to simplify these 2 jobs into 1?
The difficulty lies in invoking a pipeline counter with a value generated from a script.
I tried adding a pwsh step in the first job and using the counter variable runtime expression to set a `env: ` value but it didn't get expanded.

Any other suggestion to simplify the process is welcome too.

```yml
jobs:
  - job: Version_Number_Prepare
    pool:
      vmImage: "windows-2019"
    steps:
      - checkout: none
      - pwsh: |
          $VersionComputed = Get-SomeComputedValue
          "##vso[task.setvariable variable=Value;isOutput=true]" + $VersionComputed
        name: VersionComputed

  - job: Version_Number
    dependsOn: Version_Number_Prepare
    pool:
      vmImage: "windows-2019"
    variables:
      VersionComputed: $[ dependencies.Version_Number_Prepare.outputs['VersionComputed.Value'] ]
      VersionPatch: $[ counter(variables['VersionComputed'], 1) ]
      Version: $(VersionComputed).$(VersionPatch)
    steps:
      - checkout: none
      - pwsh: '"##vso[task.setvariable variable=Value;isOutput=true]" + $env:Version'
        name: VersionNumber

# use dependsOn and variable outputs in dependants job

```
