### ISSUE TITLE
How to check if a jobList is empty?

### ISSUE THREAD

**Issue by PedroLamas** [microsoft/azure-pipelines-yaml#467]
Consider the following example template:

```
parameters:
  - name: buildJobs
    displayName: 'Build jobs'
    type: jobList
    default: []
  - name: deploymentJobs
    displayName: 'Deployment jobs'
    type: jobList

stages:
  - stage: build
    displayName: 'Build'
    jobs:
      - ${{ parameters.buildJobs }}
  
  - stage: deploy
    displayName: 'Deploy'
    jobs:
      - ${{ parameters.deploymentJobs }}
    dependsOn: build
```

As it is right now, if we omit `buildSteps` it will have a default values of `[]` and thus we will get an error on the build stage saying that at least 1 job is required.

So I'm now trying to make the build stage optional by checking the content of `buildSteps` like this:

```
parameters:
  - name: buildJobs
    displayName: 'Build jobs'
    type: jobList
    default: []
  - name: deploymentJobs
    displayName: 'Deployment jobs'
    type: jobList
    default: []

stages:
  - ${{ if parameters.buildJobs }}:
    - stage: build
      displayName: 'Build'
      jobs:
        - ${{ parameters.buildJobs }}
  
  - stage: deploy
    displayName: 'Deploy'
    jobs:
      - ${{ parameters.deploymentJobs }}
    ${{ if parameters.buildJobs }}:
      dependsOn: build
```

Unfortunately, `${{ if parameters.buildJobs }}` will always return true as an empty array is (correctly) evaluated to true as it is not `null`.

The parameter `jobList` type forces us to pass an array, so setting it to `null` is not an option - unless we instead use `object` type, then it works as expected.

So I was wondering if there is any way to check for an empty jobList (or any parameter list for that matter)?

**Comment by kvpt** [comment]
Encountered the same problem today.

This seems to work for me :
`if eq(parameters.myArray, '')`

I think Equal function implicitly convert the array to a string, but if not, we can use join like this to do it explicitly :
`if eq(join('', parameters.myArray), '')`

**Comment by PedroLamas** [comment]
Hi @kvpt thank you for your comments.

Can you confirm that you actually defined `myArray` with type `jobList` as per my sample? So something like this:

```yaml
parameters:
  - name: myArray
    type: jobList
    default: []
```
I ask this as I believe I did try comparing with an empty string and it didn't work for me...

**Comment by kvpt** [comment]
Hi @PedroLamas,

You're right I think it's the problem, my issue was with an array of string.
I see in the documentation that complex object (a job in this case) are converted to empty string by the join function so my advice will not work.

So for your case, the only workaround I see is to have boolean Build, to control if build run or not, with default value for the most common case.
I often have booleans to control if I run build, test or deploy step.

Another workaround would be to have a blank job and concat your job list after but it will add useless noise to the build, so it's not a valuable solution.

They should really add a length function or something similar for case like this.

**Comment by PedroLamas** [comment]
Agreed, I can see multiple reasons when someone would require a length/count function for arrays (this is a good example), let's hope that someone with power to act on it actually reads this!

**Comment by mamillapallirk** [comment]
Set the default value of your buildJobs array to some dummy value... something like this

parameters:
  - name: buildJobs
    displayName: 'Build jobs'
    type: jobList
    **default: ['none']**

and validate your 'if' condition like this

  **${{ if ne(parameters.buildJobs[0], 'none') }}:**
    dependsOn: build

**Comment by pedrolamas** [comment]
Though I haven't yet tried it, it seems that a `length` function has been available for a while, so this might be an actual this fix for this issue! https://github.com/MicrosoftDocs/azure-devops-docs/commit/bcdd81f69f744dd7c7f9fb6ea0088a2ba98b8e30#diff-cd027f7dbe3a3b0b075ac724f0de8318b105875dadfb16fb45b0ecf1d19b2640R270

**Comment by musukvl** [comment]
`length`  really works: 
```
parameters:   
  - name: extraSteps
    type: stepList
    default: []

steps:
  - script: echo "Got ${{length(parameters.extraSteps)}}"

  - ${{ if ne(length(parameters.extraSteps), 0) }}:
    - ${{ parameters.extraSteps }}
```
