### ISSUE TITLE
Pipeline resource trigger never fires and pipeline says "This pipeline has no specified resources" even though it does

### ISSUE THREAD

**Issue by danquirk** [microsoft/azure-pipelines-yaml#478]
I've created a new multi-stage pipeline called MyRelease with this as the first lines in the file:
```yml
resources:
  pipelines:
  - pipeline: MyTestPipeline
    source: MyTestPipeline-CI
    branch: users/myBranch
    trigger:
      branches:
        include:
          - users/myBranch
```
In this same branch I've defined a new build pipeline called MyTestPipeline-CI which produces a build artifact that should trigger the MyRelease pipeline above. I've set MyRelease's 'Default branch for manual and scheduled builds' in the pipeline settings to users/myBranch as well. However, when I create a new build from MyTestPipeline-CI it never triggers the MyRelease pipeline. 

In attempting to debug what's going on I click 'Run pipeline' and then click Resources to see if my resource is even registering as something I could configure (let alone trigger) and I just see this:
![image](https://user-images.githubusercontent.com/7121557/78626290-2e1cc200-7843-11ea-95bd-c2f14847d004.png)
which suggests something fundamentally wrong with my resources syntax. But if I change the value of ```source``` above to a pipeline that actually doesn't exist then I get a relatively clear error message that there's no resource matching that name. Likewise if I remove the ```branch``` value I get a pretty clear error message that MyTestPipeline-CI either doesn't exist or is inaccessible (since it's not in the repo's default branch). So clearly something is working looking up the difference between a valid and invalid pipeline resource and yet I can't get any actual functionality from it.

Am I missing something obvious?

**Comment by rink72** [comment]
@danquirk - Quite a few people are having this issue. There's another documentation issue logged for it here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/7635

I've also just logged a support ticket for it so if I hear anything back from that I'll update here as well.

**Comment by JordanReyesLeger** [comment]
I had the same problem, any idea how to solve it?

**Comment by danquirk** [comment]
@JordanReyesLeger a workaround that works is this: quote the branch names.
```
resources:
  pipelines:
  - pipeline: MyTestPipeline
    source: MyTestPipeline-CI
    branch: 'users/myBranch'
    trigger:
      branches:
        include:
          - 'users/myBranch'
```
My trigger works correctly in this case. It appears per the link above from @rink72 that the Resources UI screenshot is misleading as that functionality isn't actually supported yet even though the resource pipeline triggers can work.

**Comment by ashokirla** [comment]
Apologies for the inconvinience. We are fixing this issue on priority. With the next deployment, you will see the version picked up by default and you will also get the ability to manually pick any other version.

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.

**Comment by kutsyk-neocles** [comment]
Hello, I'm still having errors with resources tab.
I have build pipeline and deploy pipeline.
I want developers to be able to choose which version of build pipeline to use during deployment, as this:
`tag: $(resources.pipeline.build-ci.runID)`

My resource description:
```
resources:
  pipelines:
  - pipeline: build-ci
    source: build-CI
    branch: 'master'
```

How can I do this?
