### ISSUE TITLE
Allow if expressions in resources section

### ISSUE THREAD

**Issue by DrBushyTop** [microsoft/azure-pipelines-yaml#479]
Currently it would seem that if-conditions are not available in the resources section of a YAML pipeline. Is this something that's planned to happen in the future? Or am I just doing something wrong in the example below?

Here's an example of what I would want to do.

```
# Runtime parameters to select artifacts
parameters:
- name : artifactBranch
  displayName: Artifact Branch (e.g. feature/myfeature)
  type: string
  default: $(Build.SourceBranch)
- name : deploymentBuildId
  displayName: Deployment-Artifacts-YAML Build Id (e.g. run Id for the build to download). Overrides Artifact Branch if not "latest".
  type: string
  default: latest

# Set up build pipeline to trigger release on completion
resources:
  pipelines:
  - pipeline: deployment_artifacts
    source: Deployment-Artifacts-YAML
    ${{ if ne(parameters.deploymentBuildId, 'latest') }}:
      version: '${{ parameters.deploymentBuildId }}'
    ${{ if eq(parameters.artifactBranch, '$(Build.SourceBranch)') }}:
      branch: '$(Build.SourceBranch)'
    ${{ if ne(parameters.artifactBranch, '$(Build.SourceBranch)') }}:
      branch: 'refs/heads/${{ parameters.artifactBranch }}'
    trigger:
      branches:
      - rel/*
      - master
```

The if-expressions show the following error: `Unexpected property ${{ if ne(parameters.deploymentBuildId, 'latest') }}`

Also trying to run leads to `/Deployment/Pipelines/release-main.yaml (Line: 20, Col: 5): A template expression is not allowed in this context`

I've come up with a workaround by just using the download artifacts task on each job separately, but this would make it a bit cleaner to implement in deployment jobs as I could just specify the downloads at the beginning and allow the deployment jobs to use the default download-functionality.
