### ISSUE TITLE
DownloadPipelineArtifact@2  -- Advice needed

### ISSUE THREAD

**Issue by greengumby** [microsoft/azure-pipelines-yaml#482]
Hi,

I use DownloadPipelineArtifact@2 to retrieve the latest artifacts from multiple pipelines and package it up in another pipeline. I am wondering though how would I go about identifying the different version numbers from each of the artifacts that I am downloading.

Would be ideal if there was a way to write it out to a markdown file something like.

Pipeline 123:  3.0.0
Pipeline 232:  7.0.1
etc
etc

Extra points would be to bring in the commit messages but I'm guessing that would be difficult

Thanks

**Comment by ArtjomP** [comment]
It seems patters option would fit for you:
```
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific' # Options: current, specific
    project: 'MyProj'
    pipeline: 'MyPipeline'
    runVersion: 'latest' 
    artifact: 123
    patterns: '*3.0.0'
    path: '$(Pipeline.Workspace)' 
```

**Comment by greengumby** [comment]
@ArtjomP According to the documentation patterns limit what files are downloaded. I don't see how this will help.

**Comment by ArtjomP** [comment]
Have you tried using a variable for artifact name:
```
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific' # Options: current, specific
    project: 'MyProj'
    pipeline: 'MyPipeline'
    runVersion: 'latest' 
    artifact: $(MyPipelineArtifactVersion)
    path: '$(Pipeline.Workspace)' 
```
