### ISSUE TITLE
Adding pipeline resources does not automatically download artifacts

### ISSUE THREAD

**Issue by elam-osi** [microsoft/azure-pipelines-yaml#483]
I have a pipeline with a pipeline resource declared like so
```yaml
resources:
  pipelines:
    - pipeline: DummyBuildArtifacts
      source: DummyBuild
      trigger: true
```

`DummyBuild` publishes an artifact via the `PublishPipelineArtifact@1` task to an internal file share. 

When the pipeline consuming `DummyBuild` actually runs, it doesn't automatically download the artifacts from `DummyBuild` nor does it download them when I specifically specify it to via
```yaml
steps:
- download: DummyBuildArtifacts
```

But I know the consuming pipeline is aware of the artifact because in the pipeline run, it displays an artifact is being consumed. 
![image](https://user-images.githubusercontent.com/17784785/79226060-9c005500-7e12-11ea-9422-0458f46e89ad.png)

Am I missing something necessary to download pipeline resource artifacts?
