### ISSUE TITLE
How can we make templates commit not to trigger a build

### ISSUE THREAD

**Issue by Mattzr** [microsoft/azure-pipelines-yaml#488]
Hi,

I am trying to migrate my old release based deployment into pipeline in yaml format but facing some problems. I have converted task groups into a structure of job templates. The main pipeline file import those templates with arbitrary variables and it seems to work.

However, every time I push a change, Azure devops tries to trigger not only the main pipeline but also the templates. I tried to add triggers: none to the template but because it's not in the schema, I get an error.

What's the correct way to mark yaml file as template and prevent Azure devops from trying to build them please ?

**Comment by matteotumiati** [comment]
Hi,

I'm not sure why templates are triggered in this case, it shouldn't happen AFAIK.
 
However, can you try simply setting one of these tags in the git commit?
https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/pipelines/sprint-148-update#skip-continuous-integration-ci-for-a-commit 

With those comments the CI build shouldn't be triggered anymore.

**Comment by Mattzr** [comment]
Thanks for quick reply @matteotumiati 

Yes ! this is actually my workaround to prevent this, to add a [skip ci] into my commit message, but that would happen upond merging a PR or anybody else from my team pushing to the repository. So as a temporary solution it works but I think we need a way to avoid it.

To clarify - the templates are located in the same repository as the main pipeline and not another remote repository (for now but will probably be moved in a global core repo).

**Comment by mozts2005** [comment]
@Mattzr I think what you want is to exclude a path in your repo form triggering a build. Please see this for that hep https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#paths

**Comment by Mattzr** [comment]
thanks @mozts2005 for your input, I will give it a go now and let you know

**Comment by Mattzr** [comment]
It turns out excluding the path fixed the intermittent build attempts on templates. thanks a lot @mozts2005.

However - I still feel that there should be an **easier way to mark the yaml file as being template** (old task groups) so Azure devops doesn't try to run them if not specified in the main pipeline.

**Comment by matteotumiati** [comment]
Just out of curiosity, can you please share here one of those templates or at least a small repro of it?
I'm a bit concerned that there could be something more hiding somewhere as I don't have the same behavior on my side, but I could have a different configuration compared to yours. 

Regarding the feedback, you can log it on:
https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by Mattzr** [comment]
Sure here is one of the template that does a terraform output and then interpolate the specified path:

Path in my repo: terraform/steps
```
parameters:
  - name: terraformCodePath
    type: string
  - name: tokenReplacementFilter
    type: string

steps:
  - task: TerraformInstaller@0
    displayName: 'Use Terraform 0.12.9'
    inputs:
      terraformVersion: '0.12.9'

  - task: replacetokens@3
    displayName: 'Perform Token Replacement [ ${{ parameters.terraformCodePath }}/${{ parameters.tokenReplacementFilter }} ]'
    inputs:
      rootDirectory: '${{ parameters.terraformCodePath }}'
      targetFiles: '${{ parameters.tokenReplacementFilter}}'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      useLegacyPattern: false
      enableTelemetry: true

  - script: |
     cd ${{ parameters.terraformCodePath }}

     terraform init
    displayName: 'Terraform - Init [ ${{ parameters.terraformCodePath }} ]'

  - task: terraform-outputs@0
    displayName: 'Terraform - Outputs [ ${{ parameters.terraformCodePath }} ]'
    inputs:
      workingDirectory: '${{ parameters.terraformCodePath }}'
```

then I get the following error if not excluded from the main pipeline:

<img width="908" alt="Screenshot 2020-04-22 at 17 58 07" src="https://user-images.githubusercontent.com/5974051/80010850-f52b5100-84c2-11ea-9064-b6d6e0836256.png">
