### ISSUE TITLE
Support for 2-Dimensional Insertion into Matrix Strategy

### ISSUE THREAD

**Issue by JamesAllen16** [microsoft/azure-pipelines-yaml#489]
Essentially this is a similar request to a cross-product insertion, but in which the sub-values of each type are explicit and different for each top level value.

I'll use an OS Platform and Python version as an arbitrary example to help explain. Let's use:

Platforms: Linux and Windows
Python Versions: 2.7.15, 3.6.10 and 3.8.2 on Linux, 2.7.12, 3.7.3 and 3.59 on Windows

**Top Level Definition:**
```yaml
jobs:
- template: buildProduct.yml
  parameters:
    PLATFORMS: ['linux', 'windows']
    VERSIONS: ['2.7.15', '3.6.10', '3.8.2', '2.7.12', '3.7.3', '3.59']
```

**buildProduct.yml**
```yaml
parameters:
  PLATFORMS: []
  VERSIONS: []

- job: buildThing
  strategy:
    matrix:
      ${{each PLATFORM in parameters.PLATFORMS}}
         ${{each VERSION in parameters.VERSIONS}}
            PLATFORM: ${{PLATFORM}}
            VERISION: ${{VERSION}}
```
For the matrix outcome I desire, a nested each wouldn't work with 2 separate parameters as demonstrated above because it would expand too many unwanted permutations (Linux would build versions that are for Windows and vice versa).

While this YAML example isn't functional, it should demonstrate what I would like to do to expand correctly:
**Top Level Definition:**
```yaml
jobs:
- template: buildProduct.yml
  parameters:
    BUILDS:
      linux: ['2.7.15', '3.6.10', '3.8.2']
      windows: ['2.7.12', '3.7.3', '3.5.9']
```

**buildProduct.yml**
```yaml
parameters:
  - name: BUILDS
    type: object

- job: buildThing
  strategy:
    matrix:
      ${{each PLATFORM in parameters.BUILDS}}
         ${{each VERSION in PLATFORM}}
            PLATFORM: ${{PLATFORM}}
            VERISION: ${{VERSION}}
```

If something of this nature would be supported it would enable explicit nested expansion for jobs that may not have symmetrical sub-values for every platform (which a cross-product implicitly assumes). 

There may also be other approaches to this problem that might solve my problem too. I would prefer not having to duplicate the top-level template definition to be per-platform as my pipeline already has a fair amount of other data types being passed through that remain the same. The less duplication, the better :).
