### ISSUE TITLE
Using a Step Template within a Phase Template (nested templates)

### ISSUE THREAD

**Issue by lifesoccult** [Microsoft/azure-pipelines-yaml#49]
Is it possible to nest templates? My first attempt at doing this is throwing an error of `android-modules.yml (Line: 1, Col: 1): Unexpected value 'resources'` within the top level phase template. This seems to be not a possible option then. Would it be better to use conditions within the phase template to decide whether or not to execute a step?

Thanks,

Jonathan

**Comment by ericsciple** [comment]
You can nest templates but `resources` can currently only appear in your root file.

Why do you need to define a resources section in your template? (I may have a workaround)

**Comment by lifesoccult** [comment]
Do I not need to define the resources again inside the nested template? The main config has resources defined, I didn't know if that is adequate for nested templates too. If so, then great.

**Comment by lifesoccult** [comment]
TIL: Only need to define the resource in the root yaml, gets inherited to all templates underneath. This also means you can only use that initial template resource as a source for your templates and do not need to include the `@repository-resource` when defining those nested templates.

**Comment by beatcracker** [comment]
TWIMC: it seems that you can have multiple `resources` if you use new [extends](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates#extend-from-a-template) keyword. This works:

- azure-pipelines.yml
```
resources:
   containers:
      - container: node_latest
        image: node:latest

extends:
  template: template.yml
```

- template.yml
```
resources:
   containers:
      - container: node_lts
        image: node:lts
```
