### ISSUE TITLE
Unexpected value 'CmdLine@2' / 'Bash@3' when using extends feature

### ISSUE THREAD

**Issue by bijopunnoose** [microsoft/azure-pipelines-yaml#499]
My azure-pipelines.yml looks like below and extends from pythonparameter-template.yml
```
#azure-pipelines.yml
trigger: none

resources:
  repositories:
  - repository: CI-CD-Templates
    type: git
    name: /CI-CD-Templates
    ref: refs/heads/master

extends:
  template: /pythonparameter-template.yml@CI-CD-Templates
  parameters:
    buildSteps:
    - script: echo This is my first step
    - script: echo This is my second step
    - bash: echo Test #Passes
      displayName: succeed
    - bash: echo "Test"
      displayName: succeed
    - task: CmdLine@2
      displayName: Test 3 - Will Fail
      inputs:
        script: echo "Script Test"
```

#pythonparameter-template.yml
```
parameters:
- name: buildSteps # the name of the parameter is buildSteps
  type: stepList # data type is StepList
  default: [] # default value of buildSteps
stages:
- stage: secure_buildstage
  pool: Hosted VS2017
  jobs:
  - job: secure_buildjob
    steps:
    - script: echo This happens before code 
      displayName: 'Base: Pre-build'
    - script: echo Building
      displayName: 'Base: Build'

    - ${{ each step in parameters.buildSteps }}:
      - ${{ each pair in step }}:
          ${{ if ne(pair.key, 'script') }}:
            ${{ pair.key }}: ${{ pair.value }}
          ${{ if eq(pair.key, 'task') }}:
            '${{ pair.value }}': error

    - script: echo This happens after code
      displayName: 'Base: Signing'
```

When I validate my  azure-pipelines.yml why do I get an error as below and is there a way to fix it?

/pythonparameter-template.yml@CI-CD-Templates (Line: 16, Col: 7): Unexpected value 'CmdLine@2' /pythonparameter-template.yml@CI-CD-Templates (Line: 16, Col: 7): Unexpected value 'CmdLine@2' /pythonparameter-template.yml@CI-CD-Templates (Line: 16, Col: 7): Unexpected value 'Bash@3' /pythonparameter-template.yml@CI-CD-Templates (Line: 16, Col: 7): Unexpected value 'Bash@3' /pythonparameter-template.yml@CI-CD-Templates (Line: 16, Col: 7): Unexpected value 'CmdLine@2'
