### ISSUE TITLE
Issue expanding pre-defined Azure DevOps variables in the variable group section

### ISSUE THREAD

**Issue by jazzytoor** [microsoft/azure-pipelines-yaml#503]
### Description
When creating the yaml templates and it comes to the variable section where you can define what variable groups you require for that particular stage, when declaring pre-defined variables i.e. `$(Build.DefinitionName)` doesn't get expanded. 

### What I'm trying to achieve
Let's look at the yaml template:
```
......
- stage: Prod
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - deployment: DeployWeb
    pool:
      vmImage: 'Ubuntu-18.04'
    environment: $(DefinitionName)-prod
    variables:
      - name: Environment           
        value: prod
      - group: $(Build.DefinitionName)-${{ variables.Environment }}
```

**Note**
`jt-api` is the name of the build definition.

As you can see here is the section where I'm defining stages for each of my environments, the variable `${{ variables.Environment }}` gets extracted just fine as `Environment` is just a string. However, when it comes to `$(Build.DefinitionName)` it doesn't get extracted and stay as is.

### Expected Outcome:
`- group: $(Build.DefinitionName)-${{ variables.Environment }}` should result in the following `jt-api-prod`

### Actual Outcome:
`- group: $(Build.DefinitionName)-${{ variables.Environment }}` results in the following: `$(Build.DefinitionName)-prod`

Like so:
![image](https://user-images.githubusercontent.com/32848916/86625156-89825b80-bfbc-11ea-8751-716489106b56.png)
As you can see it hasn't expanded the pre-defined variable from Azure DevOps and just left as is. 

I have tried another ways declaring `$(Build.DefinitionName)` but all result in the same error. Am I not doing something right? Is this not supported for variables groups? Do **note** that pre-defined variables like these do work elsewhere just not in the variables section.
