### ISSUE TITLE
default aks cluster version when creating aks cluster doesn't work with for deployment example here.

### ISSUE THREAD

**Issue by raboley** [microsoft/azure-pipelines-yaml#508]
When following the example documentation for [azure environments deployments](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops) the `Deploy to Kubernetes cluster` step will fail on the error

> no matches for kind "Deployment" in version "apps/v1beta1"

which is due to the default aks version as of time of writing using kubernetes 1.16 which takes `Deployment` out of version `apps/v1beta1` and into `apps/v1`
kubernetes versions have been updated making the ./manifests/deployment.yml out of date. it currently

## Workaround

update the ./manifests/deployment.yml to reference apps/v1 instead of `apps/v1beta1` adn add a selector field that matches the template metatdata label. example:

```yaml
#./manifests/deployment.yml
apiVersion : apps/v1
kind: Deployment
metadata:
  name: raboleypipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raboleypipelinesjavascriptdocker 
  template:
    metadata:
      labels:
        app: raboleypipelinesjavascriptdocker 
    spec:
      containers:
        - name: raboleypipelinesjavascriptdocker 
          image: rabenvcr.azurecr.io/raboleypipelinesjavascriptdocker
          ports:
          - containerPort: 8080
```

## Fix 

Pin the version the kubernetes cluster will use, and then update the Deployment version to whatever works in that version. and update the deployment.yml example manifest generated to use the correct syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbceb1f5-05c3-487d-6e21-dc1b4936a55c
* Version Independent ID: 35355737-9ad9-9df5-b612-806d9df2462b
* Content: [Deploy to Azure Kubernetes Service - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/kubernetes/aks-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/kubernetes/aks-template.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

This repo is for working in the open on Azure Pipelines YAML features. It's not a great place to make [new feature requests](https://developercommunity.visualstudio.com/spaces/21/index.html), [report problems](https://developercommunity.visualstudio.com/spaces/21/index.html), or [get support](https://azure.microsoft.com/en-us/support/devops/). Issues you open here may sit unreviewed for a very long time.
