### ISSUE TITLE
How to reference steps-templates from other branches?

### ISSUE THREAD

**Issue by evertonmc** [microsoft/azure-pipelines-yaml#523]
I want to deploy to environment `staging` & `production` from branched steps-templates
e.g.
bein this my `head` extendable template (see last line)
```
stages:
- stage: dev
  variables:
  - template: ../variables/common-vars.yml
  - template: ../variables/dev-vars.yml
  dependsOn: build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment:
    environment: dev.${{ parameters.service_project_name }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../templates/generic-service-deployment.yml

- stage: staging
  variables:
  - template: ../variables/common-vars.yml
  - template: ../variables/staging-vars.yml
  dependsOn: build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  jobs:
  - deployment:
    displayName: deploy ${{ parameters.service }}
    environment: staging.${{ parameters.service_project_name }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../templates/generic-service-deployment.yml@my-staged-branch
```

This throws an error of course because I can't attach resources to extended templates
