### ISSUE TITLE
Are multi-line template expressions possible?

### ISSUE THREAD

**Issue by LachlanMarnham** [microsoft/azure-pipelines-yaml#533]
Dear community,

I have the following template expression inside a `variables` block:

`${{ if and(eq(variables['Build.Reason'], 'IndividualCI'), startsWith(variables['Build.SourceBranchName'], 'test_')) }}`

Which I would love to be able to write like this:

```yaml
variables: 
  - name: version
       ${{ if 
             and(
                     eq(variables['Build.Reason'], 'IndividualCI'), 
                     startsWith(variables['Build.SourceBranchName'], 'test_')
                    ) 
       }}
         value: test
...
```
but after reading the documentation I was unable to work out how to do this.

Alternatively, I would be happy to instead write:

```yaml
variables:
  - name: newCommits
     value: $[ eq(variables['Build.Reason'], 'IndividualCI') ]
  - name: isTestBranch
     value: $[ startsWith(variables['Build.SourceBranchName'], 'test_') ]
  - name: ${{ if and(variables.newCommits, variables.isTestBranch) }}
 ```
But I've had issues accessing `variables.newCommits` and `variables.isTestBranch` inside the templates. This doesn't fail per se, but does not give the correct behaviour (I think this is because the execution order of `$[...]` vs `${...}` maybe?).

Are either of these two methods possible? Many thanks.

**Comment by max-zaytsev** [comment]
Hi @LachlanMarnham, multi-line template expressions are not supported. And, yes, there is some difference in expanding variables in Template expressions and Runtime expressions (Please see more details [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#template-expression-syntax))

In your case, I think you can try this:

```yaml
variables:
  ${{ if eq(variables['Build.Reason'], 'IndividualCI') }}:
    newCommits: True
  ${{ if startsWith(variables['Build.SourceBranchName'], 'test_') }}:
    isTestBranch: True
  ${{ if and(eq(variables['newCommits'], True), eq(variables['isTestBranch'], True)) }}:
    version: Test
  ${{ if not(and(eq(variables['newCommits'], True), eq(variables['isTestBranch'], True))) }}:
    version: Prod
```
