### ISSUE TITLE
Resource webhook trigger is misdocumented?

### ISSUE THREAD

**Issue by joshspicer** [microsoft/azure-pipelines-yaml#535]
I am working on connecting an ADO YAML pipeline to be triggered by a webhook via service connection.

Looking at the documentation here on [how to supply a `filter`](https://github.com/microsoft/azure-pipelines-yaml/blob/482280dc85ecf3311f22e0cb49721b5a9ef10ead/design/pipeline-triggers.md#example-1)

is not correct, as visible through the YAML intellisense.

![image](https://user-images.githubusercontent.com/23246594/115048466-96b36b80-9ea7-11eb-8353-e94a79abca66.png)

I've been unable to get filtering to work on my ADO pipeline - some advice here would be appreciated :)

**Comment by mjroghelia** [comment]
@joshspicer This is telling you that you need a `-` in front of `"$.action"`. Filters is an array of mappings, not a mapping.

**Comment by joshspicer** [comment]
I was just copying the docs on this repo to illustrate the problem. Adding a `-` doesn't help :(
![image](https://user-images.githubusercontent.com/23246594/115066783-00d70b00-9ebe-11eb-8d5d-28752129a8c0.png)

I don't get any syntactic errors when I set it up like below, but that doesn't actually work (my incoming webhooks are not filtered by this key/value pair
![image](https://user-images.githubusercontent.com/23246594/115067042-5a3f3a00-9ebe-11eb-8303-a423ed562026.png)

**Comment by joshspicer** [comment]
Am I missing something on how `filters` is supposed to behave in the first place?  I want to filter based on the JSON webhook data that I receive on this pipeline. From GitHub, when a "release" webhook is sent, it's sent 3 times (with _three_ distinct `actions`.)

The JSON looks like this:

```
{
  "action": "SOME_VALUE",
 ...
 ...
}
```

When `SOME_VALUE` == "released" I want this pipeline to run, otherwise I don't want it to run.

**Comment by mjroghelia** [comment]
@joshspicer Sorry I can't help more. The document you are referring to is a design doc and as stated in the [README](
https://github.com/microsoft/azure-pipelines-yaml/tree/master/design#azure-pipelines-yaml---design-docs) not maintained as permanent documentation of the product.

**Comment by joshspicer** [comment]
Hey @mjroghelia - I understand that perhaps this repo isn't the best source of information for how to use this feature. I've also tried referencing the permanent documentation on docs.microsoft.com (found [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-webhooks) and announced [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-172-update#generic-webhook-based-triggers-for-yaml-pipelines)).

As you can see from my screenshot above, i've copied what is in the docs, but the filter does not get applied (My pipeline runs 3 times, even when my filter's value at the given path does not equal what is in the YAML.

**Comment by joshspicer** [comment]
For reference, this is what the docs say vs what I have in my pipeline.  The JSON webhook body is sent as I shared above.

I am sent three requests from [Github when a `release` is created](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release), with three different actions.  My goal is to filter by the `action` key.

## The documentation 
```yaml
resources:
  webhooks:
    - webhook: MyWebhookTrigger          ### Webhook alias
      connection: MyWebhookConnection    ### Incoming webhook service connection
      filters:
        - path: repositoryName      ### JSON path in the payload
          value: maven-releases     ### Expected value in the path provided
        - path: action
          value: CREATED
```

## My pipeline
```yaml
# Triggered on a webhook sent from 
# a GitHub repo
resources:
  webhooks:
    - webhook: DefaultImageCreationWebhook
      connection: DefaultImageCreationConnection
      filters:
        - path: "action"
          value: "released" 

```
