### ISSUE TITLE
how to use "Each" Template Expression for a json array text in variable

### ISSUE THREAD

**Issue by anilsamuel** [microsoft/azure-pipelines-yaml#539]
I have a json array in ip_addrs task variable as below. Is it possible to iterate through this array using Each or similar ?

```
- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
      name: getIPAddrs
      displayName: 'Obtain EC2 IP Addresses'
      inputs:
        awsCredentials: 'test'
        regionName: 'ap-southeast-2'
        scriptType: 'inline'
        inlineScript: |
          sudo apt-get -y install jq
          ip_addrs=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[LaunchTime,InstanceId,ImageId,PrivateIpAddress,Tags[?Key==`Name`] | [0].Value][] | sort_by(@, &[4])' --output json --filters Name=instance-state-name,Values=running | jq -c '.[] | select(.[4]|startswith("PHREDC"))' | tr -s '\r\n' ',')
          echo "##vso[task.setvariable variable=ip_addrs;isOutput=true]"["${ip_addrs::-1}"]""
```
