### ISSUE TITLE
Are pipeline triggers for the same pipeline supported?

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/azure-pipelines-yaml#546]
My intention of creating an issue here is to understand if my scenario is supported; if it is, I'll follow up with DevOps support; if not, I'll open a feature request on Developer Community.

My question is: **Can I create a pipeline resource that triggers on itself?**

For example, let's say my multi-stage pipeline is called "ci-test" with stages "build" and "deployPPE", plus an additional "deployProd" stage that only triggers if Build.Reason == "ResourceTrigger", and has a pipeline resource as follows:
```yaml
resources:
  pipelines:
  - pipeline: self
    source: ci-test
    trigger:
      stages:
      - deployPPE
      branches:
        include:
        - main
```

**Is this scenario supported?**

It was working when I was testing it out in a branch, but after adding the "branches: [ main ]" constraint and merging to main, the trigger is no longer...triggering. Hence my question.

(For context, we are trying to do this because we have a scheduled pipeline that picks up artifacts that this pipeline produces, and it is non-trivial for us to use the DownloadPipelineArtifact task because of https://github.com/microsoft/azure-pipelines-agent/issues/3511.)
