### ISSUE TITLE
npm publish based on new tags

### ISSUE THREAD

**Issue by ryx** [microsoft/azure-pipelines-yaml#55]
It would be great to have an example about how to publish an npm module to the public npmjs.com registry from a github repository. Ideally, this would illustrate how to trigger a new CI build on any commit, while running the `npm publish` command only when a new tag has been committed to the master branch.

I could imagine that such an example might really improve the adoption of Azure CI as build solution for npm-based Javascript projects. Right now it is very difficult to find useful documentation for this individual problem.

Thanks in advance :)

**Comment by ryx** [comment]
I came up with a (kind of) working solution, maybe it is of help to someone else. I'd also really appreciate any comments or feedback on this, since I have been using Azure CI for not more than 3 hours now ;) ... 

This approach uses a conditional task execution which only triggers the npm publish task when the source branch is a new release (create via github). This still has some disadvantages (e.g. manual versioning), but works for a simple publishing workflow when using the github UI for creating releases.

```
# Build and publish a node.js-based library from a github repository. Only
# publish anything to npm if the tests succeeded (so the build was ok)
# and the build is spawned from a new release in github.

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run test
    displayName: 'Npm install and test'

  - task: Npm@1
    # only execute this task when the sourceBranch is a new release
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    inputs:
      command: publish
      publishEndpoint: npmjs.com
    displayName: 'Publishing to npmjs.com'
```

**Comment by wichert** [comment]
I suspect the preferred approach is to use a different pipeline YAML file for releases, and give that a trigger that only looks for tags. You can combine that with a template to prevent duplication. For example I use these three files:

## templates/test.yml
```yaml
  jobs:
  - job: test
    displayName: Run tests

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          command: install

      - task: Npm@1
        displayName: 'npm test'
        inputs:
          command: custom
          customCommand: 'test'
```

## test.yml
```yaml
jobs:
  - template: templates/test.yml
```

## release.yml
```yaml
trigger:
  branches:
    exclude:
      - "*"
  tags:
    include:
      - v*

jobs:
  - template: templates/test.yml


  - job: docker
    displayName: Docker image
    dependsOn:
      - test

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: azr-crypho

      - task: Docker@2
        displayName: Build and Push
        inputs:
          command: buildAndPush
          repository: crypho/nexmock
          tags: |
            $(Build.BuildId)
            $(Build.SourceBranch)
```
