### ISSUE TITLE
Is there a way I can define the azure pipeline template to be imported from a tag? [resources/repository/git]

### ISSUE THREAD

**Issue by saurabh-sp-tripathi** [microsoft/azure-pipelines-yaml#554]
Consider a yaml based pipeline 

```
resources:
  repositories:
    - repository: templates
      type: git
      name: My-Proj/azure-build-templates
...

```

This will refer to repository `azure-build-templates` in branch `master`. Is there a way I can declare to refer a tag instead of `master`?

**Context of its utility**: Recently we pushed something in master which consequently broke all the pipelines. As a fix we had to rollback with git operations. I wonder if there would be a way to refer from tag like jenkins and rollback would be just point from one git tag to another. (Downside on every release you have update all the pipelines, so I am up for any suggestions for templates release management). Thanks.

ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-repositories-resource

**Comment by KarolSiedlik** [comment]
```
resources:
  repositories:
    - repository: templates
      type: git
      name: My-Proj/azure-build-templates
      ref: refs/tags/<your tag>
```

you can use any ref here, like feature or commit
