### ISSUE TITLE
pipeline-triggers.md conflicts with the same information on docs.microsoft.com

### ISSUE THREAD

**Issue by TomBailey-N** [microsoft/azure-pipelines-yaml#560]
I'm trying to use PR triggers as per https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md#schema-2

However it doesn't work. I'm using Azure Pipelines and Github. PR/CI workflow normally works when not called under resource.repositories

The docs.microsoft.com Schema for the same resource doesn't include the PR trigger:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-repositories-repository?view=azure-pipelines

Can someone help me understand what's going on here and if PR triggers are possible as per pipeline-triggers.md please?

My pipeline code excerpt:
```
schedules:
- cron: '30 07 * * 1-5'
  always: true
  branches:
    include:
    - master
    - main
  displayName: pipelineName

resources:
  repositories:
  - repository: repo-name
    type: github
    endpoint: repo-endpoint
    name: full-repo-name
    pr:
      drafts: false
      branches:
        include:
        - '*'
        exclude:
        - main
        - master      
      paths:
        include:
        - 'folder/*'
        exclude:
        - 'folder/README.md'
```
