### ISSUE TITLE
Parameter or variable of type object or list that can be set from a script

### ISSUE THREAD

**Issue by anilsamuel** [microsoft/azure-pipelines-yaml#567]
Hooping to do something similar but looking for a way to set the list value of parameters.StackNames using command below prior to Delete ${{ stack }}

`aws cloudformation describe-stacks --query "reverse(Stacks[? starts_with(StackName,'boomi-')] | sort_by(@, &CreationTime) | [].StackName)"
`
```
parameters:
- name: stackNames
  type: object

steps:
- ${{ each stack in parameters.stackNames }}:
  - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
      displayName: Delete ${{ stack }}
      inputs:
        awsCredentials: ${{ parameters.awsCredentials }}
        regionName: $(region)
        scriptType: inline
        inlineScript: |
           aws cloudformation delete-stack --stack-name ${{ stack }}
           aws cloudformation wait stack-delete-complete --stack-name ${{ stack }}

```
