### ISSUE TITLE
YAML Extend Stage Template 

### ISSUE THREAD

**Issue by deckerbr1979** [microsoft/azure-pipelines-yaml#568]
Hello All,

Looking to try and get some help figuring out a solution to what seems like a simple task. I am trying to develop some extend YAML templates for security within our ADO pipelines but first I have to get passed this error I am experiencing. 

The error being returned by ADO when I try to validate or run the pipeline is `"/ADO_Stage_Restrictions_Dev.yml@AdoRestrictions (Line: 7, Col: 3): Unexpected value 'job'"`.  

***Working Extend Template YAML***
<sub>This template validates and executes without issue, which to me means I am successfully passing the stages object into the extends template</sub>
```
parameters:
  - name: stageObjs
    type: stageList
    default: []

stages:
- ${{ each stage in parameters.stageObjs }}:
    ${{ stage }}
  
```

***Broken Extend Template YAML***
<sub>This template does not validate and throws the 'Unexpected value job' exception. based on the [stage schema ](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/stages-stage.md) I would assume that I would be able to loop the jobs property within the stage.</sub>
```
parameters:
  - name: stageObjs
    type: stageList
    default: []

stages:
- ${{ each stage in parameters.stageObjs }}:
  - ${{ each job in stage.jobs }}:
    - ${{ job }}
```

***Build YAML***
<sub>
The main yaml file that extends stages
</sub>
```
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/Development
      
    - repository: AdoRestrictions
      type: git
      name: utl-yaml-templates
      ref: refs/heads/main

trigger: none

pool:
    name: PROD    

extends:
  template: ADO_Stage_Restrictions_Dev.yml@AdoRestrictions
  parameters:
    stageObjs:
      - stage: 'BuildStage'
        displayName: 'Build Test'
        jobs:
          - job: 'BuildJob'
            displayName: 'Build'
            steps:
            - task: PowerShell@2
              displayName: 'Hello World'
              inputs:
                targetType: inline
                script: |
                  Write-Host "Hello World"
```
