### ISSUE TITLE
Coalesce operator breaks iteration of objects in nested array

### ISSUE THREAD

**Issue by jadzdtc** [microsoft/azure-pipelines-yaml#569]
Following pipeline won't run
```
parameters:
- name: array
  type: object  
  default:
  - nestedArray: 
    - nestedArrayObject: foo
    - nestedArrayObject: bar
- name: otherArray
  type: object  
  default:
  - bar
  - baz
      
jobs:
- ${{ each item in parameters.array }}:
  - ${{ each nestedItem in coalesce(item.nestedArray, parameters.otherArray) }}: 
    - job: baz
```
yielding following error:
![image](https://user-images.githubusercontent.com/65334140/172403061-1352feba-55d5-4864-80bc-27510ca8834f.png)

If coalesce operator is removed, pipeline works as expected (fails due to not unique job names). Also if nested array consist of simple types, there will be no type conversion issues.

Please fix this behavior cause it is not obvious why such a construct would not work.
