### ISSUE TITLE
Pipeline parameters from template are not rendered in Run pipeline UI

### ISSUE THREAD

**Issue by jvmlet** [microsoft/azure-pipelines-yaml#570]
````yml
.azure-pipelines.yml
extends: 
   template: template.yml
   parameters:
     skipInspection: ${{ parameters.skipInspection }}
     releaseScope: ${{ parameters.releaseScope }}
````

````yml
.template.yml
parameters:
  - name: test
    default: "false"
    type: boolean
````

![image](https://user-images.githubusercontent.com/6664858/176694487-0da9f2fb-7fa7-491a-98c7-b02f47ef5973.png)
