### ISSUE TITLE
Repository triggers doesn't trigger when batch is enabled

### ISSUE THREAD

**Issue by mblaschke-daimlertruck** [microsoft/azure-pipelines-yaml#571]
I'm trying to setup a pipeline which should trigger when changes in multiple repositories are detected but with a batched job:

```yaml
resources:
    repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        clean: true
        fetchDepth: 1
      trigger:
        batch: true
        branches:
          include:
            - main
        paths:
          include:
            - configuration/*

    - repository: repo1
      name: project/repo1
      type: git
      checkoutOptions:
        clean: true
        fetchDepth: 1
      trigger:
        batch: true
        branches:
          include:
            - main
```

This pipeline triggers when changes in self are detected but not in repo1. 
If i disable `batch: true` on repo1 then also the pipeline runs for commits in repo1, but doesn't care if there is already job running.
