### ISSUE TITLE
Dynamic display name with variables doesn't work on template.

### ISSUE THREAD

**Issue by fuxiuyin** [microsoft/azure-pipelines-yaml#574]
I'm using YAML stage template and trying to make my stage display name dynamic. But the display name is variable itself not the variable value like:

```bash
publish $(packageType) pkgs
```

I made a minimal pipeline to reproduce it:

```yaml
parameters:
  - name: distro
    displayName: "Linux distro"
    default: "Ubuntu18.04"
    values:
      - "RHEL7"
      - "RHEL8"
      - "Ubuntu18.04"
      - "Ubuntu20.04"
  - name: pool
    displayName: "pool"
    type: string

resources:
  repositories:
    - repository: self
      clean: true
      ref: "main"

variables:
  - name: packageType
    ${{ if eq(parameters.distro, 'RHEL7') }}:
      value: "rpm"
    ${{ elseif eq(parameters.distro, 'RHEL8') }}:
      value: "rpm"
    ${{ elseif eq(parameters.distro, 'Ubuntu18.04') }}:
      value: "deb"
    ${{ elseif eq(parameters.distro, 'Ubuntu20.04') }}:
      value: "deb"

pool:
  name: ${{ parameters.pool }}

stages:
  - template: templates/display_name.yml
    parameters:
      packageType: $(packageType)
```

And the template is:

```yaml
parameters:
  - name: packageType
    type: string
    displayName: "deb or rpm"

stages:
  - stage: publish
    displayName: "publish ${{ parameters.packageType }} pkgs"
    jobs:
      - job: "publish"
        displayName: "publish ${{ parameters.packageType }} pkgs"
        container:
          image: ubuntu:18.04
        steps:
          - bash: echo "publish ${{ parameters.packageType }} pkgs"
            displayName: "Log"
```
