### ISSUE TITLE
Possibility to use runtime variable in condition

### ISSUE THREAD

**Issue by tapika** [microsoft/azure-pipelines-yaml#577]
By default yaml does permit use of compile time variables in conditions.

For example:

```
steps:
    -   checkout: self
        lfs: true
        fetchDepth: 1
        condition: parameters.runTests
```

this syntax is supported.

But this syntax is not supported:

```
steps:
    -   checkout: self
        lfs: true
        fetchDepth: 1
        condition: variables.runTests
```

https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml

this page mentions this as a limitation of yaml language:

`For example, if you have a job that sets a variable using a runtime expression using $[ ] syntax, you can't use that variable in your custom condition.`

Would it be possible to add support for runtime variable evaluation in condition ?
