### ISSUE TITLE
Resource webhook filters with paths which contain special keys.

### ISSUE THREAD

**Issue by cokeSchlumpf** [microsoft/azure-pipelines-yaml#579]
Hi everyone,

I have detected a potential issue with the webhok filters. We have an incomming JSON which contains keys with dots. Example:

```json
{
  "resource": {
    "fields": {
      "System.State": "Something"
    }
  }
}
```

There is no chance that the suggested notation of the filter could work, e.g.,

```yml
resources:
  webhooks:
    - webhook: webhook_name
      connection: connection_name
      filters:
        - path: resource.fields.System.State
          value: Ready to Deploy UAT
```

I tried the bracket notation, but without success:

```
resources:
  webhooks:
    - webhook: webhook_name
      connection: connection_name
      filters:
        - path: resource.fields["System.State"]
          value: Ready to Deploy UAT
```

Is there any way to get this working?
