### ISSUE TITLE
How to use `Build.SourceVersionAuthor`?

### ISSUE THREAD

**Issue by RussKie** [microsoft/azure-pipelines-yaml#583]
I need to conditionalise the build based on whether it is a pull-request from a branch name with a specific name submitted by a specific author.

I able to express the first two conditions but I can't figure out the last one.
These work
```yml
variables:
  - name: A_IsPullRequest
    value: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
  - name: A_PullRequestSourceBranch
    value: $[ variables['System.PullRequest.SourceBranch'] ]
  - name: A_IsDarcPullRequestSourceBranch
    value: $[ startsWith(variables['System.PullRequest.SourceBranch'], 'darc-main-') ]

  - name: A_SourceVersionAuthor
    value: $(Build.SourceVersionAuthor)
```

I can use `$(Build.SourceVersionAuthor)`, however, more matter what I do I can't figure out how to apply a condition to it. E.g., none of these work:
```yml
variables:
  # These are unset
  - name: A_SourceVersionAuthor2
    value: $[ variables['Build.SourceVersionAuthor'] ]
  - name: A_SourceVersionAuthor3
    value: ${{ variables['Build.SourceVersionAuthor'] }}

  # These are false
  - name: A_IsMaestroAuthor1
    value: ${{ eq(variables['Build.SourceVersionAuthor'], 'dotnet-maestro[bot]') }}
  - name: A_IsMaestroAuthor3
    value: ${{ eq('$(Build.SourceVersionAuthor)', 'dotnet-maestro[bot]') }}
  - name: A_IsMaestroAuthor4
    value: $[ eq(variables['Build.SourceVersionAuthor'], 'dotnet-maestro[bot]') ]
  - name: A_IsMaestroAuthor5
    value: $[ eq('$(Build.SourceVersionAuthor)', 'dotnet-maestro[bot]') ]
```

![image](https://user-images.githubusercontent.com/4403806/221069002-c2860b83-9c6e-4480-b50c-4f2f76332b21.png)

I can evaluate the whole thing using a script task, but it feels lame...
```yml
- pwsh: |
      function Export { param($i); Write-Host "$i"; Write-Host "##$i" }

      $isPullRequest = '${{ eq(variables['Build.Reason'], 'PullRequest') }}';
      $sourceBranchName = "$($env:SYSTEM_PULLREQUEST_SOURCEBRANCH)";
      $sourceBranchAuthor = "$($env:BUILD_SOURCEVERSIONAUTHOR)";
      $isMaestroBuild = $isPullRequest -and $sourceBranchName.StartsWith('darc-main-') -and ($sourceBranchAuthor -eq 'dotnet-maestro[bot]')
      Export "vso[task.setvariable variable=isMaestroBuild]$isMaestroBuild"
```
