### ISSUE TITLE
Azure YAML Pipelines - Using template expression variables at non-global scope

### ISSUE THREAD

**Issue by puya-ms** [microsoft/azure-pipelines-yaml#593]
Using the [template expression variable syntax][1] for a [job-scoped variable][2] is resulting in it being resolved to empty string. It seems that the compiler is not able to find a replacement value:
> Template variables silently coalesce to empty strings when a replacement value isn't found.

Is this expected behavior? I could not find any mention of this in the documentation. Code example:
```yaml
# Global variables are correctly replaced
variables:
  globalVar1: hello

extends:
  template: template.yml
    stages:
    - stage: stage1
      jobs:
      - job: job1
        variables:
          localVar1: world
        steps:
        - task: DisplayString
          inputs:
            stringToDisplay: ${{ variables.globalVar1}} ${{ variables.localVar1}}
            # This shows "hello "
```

  [1]: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#template-expression-syntax
  [2]: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#variable-scopes
