### ISSUE TITLE
Support for conditions in templates?

### ISSUE THREAD

**Issue by woeterman94** [microsoft/azure-pipelines-yaml#600]
Same way as

```
- task: SonarQubeAnalyze@5
  condition: and(succeeded(), ${{parameters.runSonarQube}} )
```

I'd like to use conditions in templates
```
 - template: templates/build-server.yml
   condition: and(succeeded(), ${{parameters.runSonarQube}} )
          parameters:
            enableLongRunningTests: false
            runSonarQube: false
            runOwaspDependencyCheck: false
```
