### ISSUE TITLE
Error running pipeline after renaming default GitHub branch from 'master' to 'main'

### ISSUE THREAD

**Issue by jzabroski** [microsoft/azure-pipelines-yaml#606]
I recently changed my repository github.com/fluentmigrator/fluentmigrator to use "main" instead of "master". In Azure Pipelines, I am getting the following error when I click **Run Pipeline** from the web UI: 

> Encountered error(s) while parsing pipeline YAML:
> Could not get the latest source version for repository fluentmigrator/fluentmigrator hosted on https://github.com/ using ref refs/heads/master. GitHub reported the error, "No commit found for SHA: refs/heads/master"

My pipeline file is https://github.com/fluentmigrator/fluentmigrator/blob/main/azure-pipelines.yml

When I click **Validate** on this pipeline, it returns OK.

The triggers are configured as:

```
trigger:
  branches:
    include:
    - release/*
    - main
  tags:
    include:
    - v1.*
    - v2.*
    - v3.*
    - v4.*
    - v5.*

pr: none
```

What's strange is Pull Requests in a separate yaml file are working correctly: https://github.com/fluentmigrator/fluentmigrator/blob/main/azure-pipelines-pullrequests.yml

I am honestly stumped as to what went wrong.  It seems as though Azure Pipelines has cached my old default branch as master, hence why I am adding a comment here.

_Originally posted by @jzabroski in https://github.com/microsoft/azure-pipelines-tasks/issues/17552#issuecomment-1934397090_
