### ISSUE TITLE
Pass variables from Build pipeline to Release

### ISSUE THREAD

**Issue by sjdhanasekaran** [microsoft/azure-pipelines-yaml#609]
I have traced many articles but not getting clear idea.

I am using azure build pipeline to set a variables and consume the same variable in azure releases by point the build as artifact in releases.

```
trigger:
  - base

pool:
  name: Default

steps:
  - checkout: self
    persistCredentials: true

  - task: Bash@3
    displayName: "SetVer"
    name: "SetVer"
    enabled: true
    inputs:
      targetType: "inline"
      script: |
        echo "##vso[task.setvariable variable=baseImageTag;isOutput=true]1.0.0"

  - task: Bash@3
    displayName: "printVer"
    enabled: true
    inputs:
      targetType: "inline"
      script: |
        echo "echoinggg"
        echo $(SetVer.baseImageTag)

```

in the second task i am able to consume the baseImageTag but the same variable i am not able to consume in releases.

Thanks all
