### ISSUE TITLE
Enable 'repository.name' for accepting variables 

### ISSUE THREAD

**Issue by brunoviveiros-dev** [microsoft/azure-pipelines-yaml#612]
I have plenty of Azure functions that have similar pipelines (build and release). This scenario leads me to have a bunch of "duplicated" pipelines. They only differ because it's linked to different repos. To achieve cleaner pipelines, I decided to create just one generic pipeline that will be able to build all existing Azure functions. 

This was going well, but now I discovered that YAML **resources:repositories:repository:name** do not accept expressions, which blocked me from moving forward.

I want to ask to make the name possible for expressions as the ref is: https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-212-update

This feature will bring great flexibility in Azure Pipelines, so instead of having 40 build pipelines, I can have only a generic one, which would be amazing.

Below is my current template:

```yml
parameters:
  - name: repositoryName
    type: string
    default: ""
  - name: branch
    type: string
    default: test
    values:
      - test
      - production
trigger:
  branches:
    include:
      - test
variables:
  repositoryPath: DataIntegration/_git/${{ parameters.repositoryName }}
  branchRef: refs/heads/${{ parameters.branch }}
resources:
  repositories:
    - repository: collectorRepository
      type: git
      name: DataIntegration/_git/Media.Collector.Retarget
      ref: ${{ variables.branchRef }}
jobs:
  - template: azure-pipelines-build-template.yml
    parameters:
      repositoryName: ""
      branch: ""
```

I want to use ${{ variables.repositoryPath }} instead of DataIntegration/_git/Media.Collector.Ret, that would be a good feature for sure.
