### ISSUE TITLE
Expected 'dockerregistry' service connection

### ISSUE THREAD

**Issue by fgervais** [microsoft/azure-pipelines-yaml#63]
As seen on [stackoverflow](https://stackoverflow.com/questions/53528439/azure-container-job-service-connection).

I have the following pipeline that runs a container job using an image from a private azure registry:

```
resources:
  containers:
  - container: build_container
    image: gxg08regtest.azurecr.io/ci-build-image:66162
    endpoint: SandboxGXG08

pool:
  vmImage: 'ubuntu-16.04'

container: build_container

steps:
- script: ./build.sh
```

This seems close enough to this [snippet](https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml) but it gives me the following error: 

> Expected 'dockerregistry' service connection type for image registry referenced by build_container, but got azurerm for service connection SandboxGXG08.

Any idea?
