### ISSUE TITLE
Please add Process Parameters

### ISSUE THREAD

**Issue by AceHack** [microsoft/azure-pipelines-yaml#64]
See https://github.com/Microsoft/azure-pipelines-agent/issues/1733
for more info.

I have the following parameter in a yaml build and it's set to 'yes' in VSTS variables tab.
```
parameters:
  buildDebugPackage: '$(BuildDebugPackage)'
```

I would like to do the following
```
- ${{ if eq(parameters.buildDebugPackage, 'yes') }}:
  - ${{ parameters.preBuildDebugProjects }}
  - task: DotNetCoreCLI@2
    displayName: Build Debug Projects
    inputs:
      projects: ${{ parameters.projects }}
      arguments: '--no-restore -c Debug /p:Version=$(ASSEMBLY_VERSION);FileVersion=$(FILE_VERSION)'
  - ${{ parameters.postBuildDebugProjects }}
```

But this does not work because the variable BuildDebugPackage is not expanded to the value 'yes'.

I have to instead do the following
```
- powershell: |
    Write-Host "##vso[task.setvariable variable=BuildDebugPackage]$($env:BuildDebugPackage)"
  displayName: Setup Environment Variables
  env:
    BuildDebugPackage: ${{ parameters.buildDebugPackage }}
  ignoreLASTEXITCODE: false
  errorActionPreference: Stop
  failOnStderr: true

- ${{ parameters.preBuildDebugProjects }}
- task: DotNetCoreCLI@2
  displayName: Build Debug Projects
  condition: and(succeeded(), eq(variables[BuildDebugPackage], 'yes'))
  inputs:
    projects: ${{ parameters.projects }}
    arguments: '--no-restore -c Debug /p:Version=$(ASSEMBLY_VERSION);FileVersion=$(FILE_VERSION)'
- ${{ parameters.postBuildDebugProjects }}
```

This is far inferior as I cannot even condition the pre and post steps.  This also shows up on the UI as a skipped step instead of not showing up at all.  I also have to convert the parameter to a variable in PowerShell as well.  Please fix this bug or give a workaround.  Thanks.

**Comment by martinm82** [comment]
I am as well interested in this feature. The workaround proposed above is not really nice as it adds quite lot complexity for a trivial thing.

**Comment by mbakholdina** [comment]
I have the same problem when using templates. For this particular case, I found a workaround and can use different job templates for different OS. However, this bug blocks me from implementing another required functionality, e.g., applying templates with the number of steps for a particular case depending on build options. Do you have any updates on the status of fixing this?
```
# File: azure-pipeline.yml

trigger:
- master

variables:
  osMacOS: macOS
  osLinux: Linux

jobs:
- template: templates/template-job.yml
  parameters:
    os: $(osMacOS)
    name: macOS_debug
    vmImage: 'macOS-10.13'

- template: templates/template-job.yml
  parameters:
    os: $(osLinux)
    name: Linux_debug
    vmImage: 'ubuntu-16.04'
```

```
# File: templates/template-job.yml

parameters:
  os: ''
  name: '' 
  vmImage: ''
  
jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  
  steps:
  # FIXME: This "if condition" does not give "True" because parameters.os is not set to 'macOS' when it should be
  - ${{ if eq(parameters.os, 'macOS') }}:
    - script: echo Mac
# FIXME: The same problem as above
  - ${{ if eq(parameters.os, 'Linux') }}:
    - script: echo Linux
```
