### ISSUE TITLE
Unable to commit to git through YAML

### ISSUE THREAD

**Issue by cykreng** [Microsoft/azure-pipelines-yaml#7]
Hello,
I'm trying to commit a file that is created during build back into the git repo. I've followed the instructions on [this page](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=vsts&tabs=yaml) to enable rights for Project Collection Build Service and I also made sure that **persistCredentials** is set to true. When I do git config --list in the PowerShell script I can see the line with http.https:(someurl)=AUTHORIZATION: bearer ***, which was set as the last step in **checkout**. However, I'm getting the error below. Do I need to setup the user email (what would that be with respect to the Azure DevOps project?) and the password as the access token or is there something else that I'm missing? Thank you!
![image](https://user-images.githubusercontent.com/37597107/46563011-fcc0e000-c8b3-11e8-8a7d-28bcc1633fd8.png)

```
pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- powershell: |
   git --version
   New-Item -Path "$(System.DefaultWorkingDirectory)" -Name "testfile1.txt" -ItemType "file" -Value "This is a text string."
   Write-Host "new file created, now adding file to git"
   git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" add -A
   Write-Host "git commit with message"
   git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" commit -a -m "Test Commit from Azure DevOps"
   Write-Host "git push"
   git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push

```

**Comment by TingluoHuang** [comment]
@cykreng 
I think the following should work.
```yaml
pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- powershell: |
   git --version
   New-Item -Path "$(System.DefaultWorkingDirectory)" -Name "testfile1.txt" -ItemType "file" -Value "This is a text string."
   Write-Host "new file created, now adding file to git"
   git add -A
   Write-Host "setup author info"
   git config user.email you@you.com
   git config user.name "your name"
   Write-Host "git commit with message"
   git commit -a -m "Test Commit from Azure DevOps"
   Write-Host "git push"
   git push
```
