### ISSUE TITLE
Can variables from variable groups be used for counter names?

### ISSUE THREAD

**Issue by pjboardman** [microsoft/azure-pipelines-yaml#88]
My understanding is that the name of a counter can be set to a variable and that this variable is then expanded to be the counter name. Then, when the variable value changes, the counter re-seeds. Is this correct?

If so, is it supported when the variable is from a variable group?

I have this yaml:
```yaml
variables:
  - group: Build_Identifiers
  - name: BUILD_NUMBER
    value: $[ counter( variables['majorMinorVersion'], 1) ]
```

```majorMinorVersion``` is from the ```Build_Identifiers``` variable group. When the value of ```majorMinorVersion``` is changed, the counter does not reset to 1.
