### ISSUE TITLE
Is there any support for join/concat

### ISSUE THREAD

**Issue by echesakovMSFT** [Microsoft/azure-pipelines-yaml#90]
Is it possible now to join the elements of sequence to a string?

```yaml
items:
- foo
- bar

result: ${{ join(items, ';') }}
```
where `result` would contain `foo;bar` string

One of possible scenarios for this could specifying MSBuild semicolon-separated property values using array syntax (instead of a very long string)

**Comment by vtbassmatt** [comment]
@ericsciple this seems like a decent addition to the expression language. Unless we already have something that will satisfy their scenario? (See the link above.)

**Comment by ericsciple** [comment]
I briefly discussed with @vtbassmatt and understand the scenario better now. Makes sense. I'll discuss further with Matt, so we can nail down the details in a spec somewhere (not strictly yaml; the core expression functions are available in other parts of the system too)

**Comment by echesakovMSFT** [comment]
@ericsciple Thank you for considering to add this feature!

Can't wait to have this in any form in the language and remove ugly workaround introduced by https://github.com/dotnet/coreclr/pull/22173

**Comment by ericsciple** [comment]
@vtbassmatt  @echesakovMSFT @sbomer @chcosta what do you think about this proposed behavior:


### Join function
- Concatenates all elements in the right parameter array, separated by the left parameter string.
- Min parameters: 2. Max parameters: 2
- Each element in the array is converted to string. Complex objects are converted to empty string.
- If the right parameter is not an array, the result is empty string.


Or would this behavior be better:
- If the right parameter is not an array, the result is the right parameter converted to a string.

**Comment by echesakovMSFT** [comment]
I like the second behavior for the right parameter. In this case, I can think about the function as the following two steps transformation:

1. Convert the right parameter to an array of strings. If the original value is not an array, treat it as a singleton array (of one item).
2. Join the resulting array of strings using the left parameter.

**Comment by vtbassmatt** [comment]
Yeah, now that you mention it, the silent conversion to an empty string would be confusing.

**Comment by ericsciple** [comment]
This will roll out with the m148 payload.

**Comment by jontreynes** [comment]
Is there any support to have an append to array. I see the support here converts an array to a string with a delimiter. However, the use case I'm looking for is to append to an array.

For example

```
- name: dependsOn
   default:
     - stage1
     - stage2
- name: additionalDependsOn   
    default: stage0
    
 result: ${{append(parameters.dependsOn, additionalDependsOn)}}
 
 # where result is an array [stage1, stage2, stage0]
     
```
